### ISSUE TITLE
i found new ishu i cant enter password ina  required promt

### ISSUE THREAD

**Issue by nedas2002** [ChrisTitusTech/linutil#10]
i tryed your tool and found this Ishu  i found new ishu i cant enter password ina  required promt

**Comment by TheGamingWinner** [comment]
Same here bro, I have found a fix for it
That is by setting your terminal in raw mode which allows you to enter password
but it  a hard process kitty supports raw mode by default but other terminals need some sheneni ganse to enable it. Don't worry we are finding a way fix it through the prompt it self

**Comment by ChrisTitusTech** [comment]
Fixed
