### ISSUE TITLE
installing new packages failed on `openSUSE`

### ISSUE THREAD

**Issue by salahoued** [ChrisTitusTech/linutil#111]
## Describe the bug
Can't update the system, or setting up `kitty` (not installed on my system)
I use openSuse tumblweed

## To Reproduce
1. run `linutil`
2. try to update the system, or do any actions that requires installing packages
3. See error
```
Using zypper
Usage : grep [OPTION]... MOTIFS [FICHIER]...
Exécutez « grep --help » pour obtenir des renseignements complémentaires.
\033[31mYou need to be a member of the sudo group to run me!\033[0m
```

## Expected behavior
prompting for password and running the update, and installing packages, since there is a `sudo` in the scripts.

## Screenshots
![sip](https://github.com/user-attachments/assets/25fb577b-4477-4192-97ce-0f29019ae878)

**Comment by salahoued** [comment]
It works with latest git, cloning the repo and runing `cargo run`

**Comment by lj3954** [comment]
The issue should be closed if it's already fixed. Linutil is a new project, the pace of development is quite fast and the stable release may be considerably behind.

**Comment by salahoued** [comment]
OK, thanks
