### ISSUE TITLE
Why creating Linuxtoolboxdir in 3-global-theme.sh

### ISSUE THREAD

**Issue by Clutchnp** [ChrisTitusTech/linutil#122]
https://github.com/ChrisTitusTech/linutil/blob/6f865f76efd1645b082b0132831f4f05877a8418/src/commands/system-setup/3-global-theme.sh#L6-L14

Why are we creating the linuxtoolbox directory? It has no practical use,Instead of helping, it is causing problems with

https://github.com/ChrisTitusTech/linutil/blob/6f865f76efd1645b082b0132831f4f05877a8418/src/commands/system-setup/3-global-theme.sh#L73

which calls
https://github.com/ChrisTitusTech/linutil/blob/6f865f76efd1645b082b0132831f4f05877a8418/src/commands/common-script.sh#L61-L68
Here $(realpath "$0") fails everytime since system-setup is not a sub-directory of linuxtoolbox

**Comment by infstate** [comment]
I will test this later and maybe push a PR to fix it if necessary.

**Comment by Clutchnp** [comment]
@infstate  see my pull request, while adding global theming I also addressed this

**Comment by infstate** [comment]
@Clutchnp See my response and let me know if I am wrong and respond with your points.
