### ISSUE TITLE
Rate-mirrors breaks system

### ISSUE THREAD

**Issue by NeoFax75** [ChrisTitusTech/linutil#128]
## Describe the bug
Use the system update menu and now my updates are broken because it does not check to see if the mirrors it selected 404's out.

## To Reproduce
1. Go to 'Full System Update'
2. Run the update
3. See error

`error: failed retrieving file 'core.db' from mirror.rznet.fr : The requested URL returned error: 404
error: failed retrieving file 'extra.db' from mirror.rznet.fr : The requested URL returned error: 404
error: failed retrieving file 'multilib.db' from mirror.rznet.fr : The requested URL returned error: 404
warning: too many errors from mirror.rznet.fr, skipping for the remainder of this transaction
error: failed retrieving file 'core.db' from ftp.belnet.be : The requested URL returned error: 404
error: failed retrieving file 'multilib.db' from ftp.belnet.be : The requested URL returned error: 404
error: failed retrieving file 'extra.db' from ftp.belnet.be : The requested URL returned error: 404
warning: too many errors from ftp.belnet.be, skipping for the remainder of this transaction
error: failed retrieving file 'core.db' from mirror.moson.org : The requested URL returned error: 404
error: failed retrieving file 'multilib.db' from mirror.moson.org : The requested URL returned error: 404
error: failed retrieving file 'extra.db' from mirror.moson.org : The requested URL returned error: 404
warning: too many errors from mirror.moson.org, skipping for the remainder of this transaction
error: failed retrieving file 'core.db' from mirrors.c0urier.net : The requested URL returned error: 404
error: failed retrieving file 'multilib.db' from mirrors.c0urier.net : The requested URL returned error: 404
error: failed retrieving file 'extra.db' from mirrors.c0urier.net : The requested URL returned error: 404
warning: too many errors from mirrors.c0urier.net, skipping for the remainder of this transaction
error: failed retrieving file 'core.db' from mirror.alpix.eu : The requested URL returned error: 404
error: failed retrieving file 'multilib.db' from mirror.alpix.eu : The requested URL returned error: 404
error: failed retrieving file 'extra.db' from mirror.alpix.eu : The requested URL returned error: 404
warning: too many errors from mirror.alpix.eu, skipping for the remainder of this transaction
error: failed retrieving file 'core.db' from mirrors.tuna.tsinghua.edu.cn : The requested URL returned error: 404
error: failed retrieving file 'multilib.db' from mirrors.tuna.tsinghua.edu.cn : The requested URL returned error: 404
error: failed retrieving file 'extra.db' from mirrors.tuna.tsinghua.edu.cn : The requested URL returned error: 404
warning: too many errors from mirrors.tuna.tsinghua.edu.cn, skipping for the remainder of this transaction
error: failed retrieving file 'core.db' from mirrors.jlu.edu.cn : The requested URL returned error: 404
error: failed retrieving file 'multilib.db' from mirrors.jlu.edu.cn : The requested URL returned error: 404
error: failed retrieving file 'extra.db' from mirrors.jlu.edu.cn : The requested URL returned error: 404
warning: too many errors from mirrors.jlu.edu.cn, skipping for the remainder of this transaction
error: failed to synchronize all databases (failed to retrieve some files)
 -> error refreshing databases - exit status 1
`

## Expected behavior
Core/Multilib and extra dbs to be updated and the system to upgrade.

**Comment by Clutchnp** [comment]
Can you run `sudo pacman -Sy` and then run the script again and paste output here

**Comment by NeoFax75** [comment]
Same error:

`error: failed retrieving file 'core.db' from ftp.belnet.be : The requested URL returned error: 404
error: failed retrieving file 'multilib.db' from ftp.belnet.be : The requested URL returned error: 404
error: failed retrieving file 'extra.db' from ftp.belnet.be : The requested URL returned error: 404
warning: too many errors from ftp.belnet.be, skipping for the remainder of this transaction
error: failed retrieving file 'core.db' from mirrors.c0urier.net : The requested URL returned error: 404
error: failed retrieving file 'multilib.db' from mirrors.c0urier.net : The requested URL returned error: 404
error: failed retrieving file 'extra.db' from mirrors.c0urier.net : The requested URL returned error: 404
warning: too many errors from mirrors.c0urier.net, skipping for the remainder of this transaction
error: failed retrieving file 'core.db' from mirror.moson.org : The requested URL returned error: 404
error: failed retrieving file 'multilib.db' from mirror.moson.org : The requested URL returned error: 404
error: failed retrieving file 'extra.db' from mirror.moson.org : The requested URL returned error: 404
warning: too many errors from mirror.moson.org, skipping for the remainder of this transaction
error: failed retrieving file 'core.db' from mirror.alpix.eu : The requested URL returned error: 404
error: failed retrieving file 'extra.db' from mirror.alpix.eu : The requested URL returned error: 404
error: failed retrieving file 'multilib.db' from mirror.alpix.eu : The requested URL returned error: 404
warning: too many errors from mirror.alpix.eu, skipping for the remainder of this transaction
error: failed retrieving file 'core.db' from mirror.accum.se : The requested URL returned error: 404
error: failed retrieving file 'extra.db' from mirror.accum.se : The requested URL returned error: 404
error: failed retrieving file 'multilib.db' from mirror.accum.se : The requested URL returned error: 404
warning: too many errors from mirror.accum.se, skipping for the remainder of this transaction
error: failed retrieving file 'extra.db' from mirrors.jlu.edu.cn : The requested URL returned error: 404
error: failed retrieving file 'multilib.db' from mirrors.jlu.edu.cn : The requested URL returned error: 404
error: failed retrieving file 'core.db' from mirrors.jlu.edu.cn : The requested URL returned error: 404
warning: too many errors from mirrors.jlu.edu.cn, skipping for the remainder of this transaction
`

**Comment by Clutchnp** [comment]
Ok mb, I misenterpreted the error can you do `pacman -Syyu` to refresh the databases and update everything to see if that works?

**Comment by NeoFax75** [comment]
Sorry for the delay, but that does not work. What works is running this alias:

`alias ua-drop-caches='sudo paccache -rk3; yay -Sc --aur --noconfirm'
alias ua-update-all='export TMPFILE="$(mktemp)"; \
    sudo true; \
    rate-mirrors --save=$TMPFILE arch --max-delay=21600 \
      && sudo mv /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist-backup \
      && sudo mv $TMPFILE /etc/pacman.d/mirrorlist \
      && ua-drop-caches \
      && yay -Syyu --noconfirm'`

**Comment by Clutchnp** [comment]
I see, I think we should use something like reflector to avoid this in future.it will be more reliable, to avoid this in future we can either use curl  to check weather the repos are functional or use something like reflector. @lj3954 What do you think?

**Comment by NeoFax75** [comment]
Reflector has always worked for me (EndeavourOS), but Iuse rate-mirrors as it normally creates faster mirrors, but it doesn't always check to see if the mirrors are valid/down.  If this is supposed to be for general usage, or newer users, then I would choose reflector.

**Comment by Kingproone** [comment]
I don't know if it could help, but endeavouros has an option, in its welcome utility, to do a rate mirrors mirror update that works. Could that implementation help with this issue?

![Screenshot_20240817_154555](https://github.com/user-attachments/assets/27ed89b2-90bf-461e-88c8-e1d6322770ba)

Sources:
https://github.com/endeavouros-team/welcome/blob/main/welcome

![Screenshot_20240817_154909](https://github.com/user-attachments/assets/b4357ccf-94d2-4f3d-bdf4-fd0d9a14d12c)
