### ISSUE TITLE
Contribution manual

### ISSUE THREAD

**Issue by Neon021** [ChrisTitusTech/linutil#130]
It seems that the contributing section of the manual is empty right now. I'm a beginner for contributing to open source and I'm confused how to properly test my contributions on the local. 
It would be so good to have a manual for starters like me.

**Comment by lj3954** [comment]
You can build and run the project locally with `cargo run`.

**Comment by Neon021** [comment]
Apparently so, I was trying to do the issue #125 too however I felt kinda lost in the codebase even though it's a relatively simple program. It's due to the fact that I'm new to both open-source and rust.
Do you have any guidance regarding this project or open source overall?

**Comment by Neon021** [comment]
Thanks everyone looks pretty good @afonsofrancof
