### ISSUE TITLE
[Suggestion]  bluetooth

### ISSUE THREAD

**Issue by salehabdullah216** [ChrisTitusTech/linutil#147]
**Is your feature request related to a problem? Please describe.**
Bluetooth controller
**Describe the solution you'd like**
check out  bluetui a tui for Bluetooth coded in Rust and is using Ratatui
**Describe alternatives you've considered**
N/A
**Additional context**

![2024-08-09_14-44](https://github.com/user-attachments/assets/3e353ed2-7458-4308-a39a-ab7de49e7d94)

**Comment by afonsofrancof** [comment]
What is your suggestion?
That we have a command that opens that TUI? 
That we write our own TUI?
I don't know how open @ChrisTitusTech is to linking external projects.

**Comment by SamiSul** [comment]
An option to open an external TUI seems weird tbh
