### ISSUE TITLE
Option to enable/disable num lock on start

### ISSUE THREAD

**Issue by Kingproone** [ChrisTitusTech/linutil#154]
Similar to the one already present in winutil, but for linux.

**Describe alternatives you've considered**
Kde has this option available in their settings menu, I can't comment on other DEs, so this might be very helpful.

**Comment by jeevithakannan2** [comment]
I will work on this

**Comment by jeevithakannan2** [comment]
Should we create a new tab "Tweaks" or add this to utilites tab?

**Comment by Kingproone** [comment]
I think it fits under the utilities banner, other options tweak the system as well yet still live there.

**Comment by jeevithakannan2** [comment]
Agreed
