### ISSUE TITLE
Broken fonts on Alacritty

### ISSUE THREAD

**Issue by tsuza** [ChrisTitusTech/linutil#155]
## Describe the bug
Broken symbols ( probably missing symbols ) on Alacritty after installing both Alacritty and the bash config file from linutil. Latest version at the time of writing.

## To Reproduce
1. Open linutil
2. Applications Setup > Alacritty Setup & Bash Prompt Setup
3. Open alacritty

## Expected behavior
It should show the correct symbols, symbols that we can see on Chris' videos. Kitty works just fine though.

## Screenshots
![2024-08-11_14-47](https://github.com/user-attachments/assets/82241d64-baf3-4114-87f8-405d598245cb)

## Additional context
I've read mixed things about this issue. Some people say that nerd fonts, which is used by the config of this script, are not supported on Alacritty. Elsewhere I read that it should work. 

Nevertheless, whether the issue is due to Alacritty or not, the script should provide a good user experience, so I think that something could be done. [ Hopefully this is not taken the wrong way, not trying to be mean :P ]

**Comment by tsuza** [comment]
> The issue is that the bash prompt script installs the FiraCode Nerd Font by default, but Alacritty is set to use the MesloLGS Nerd Font. I’ve created a [PR](https://github.com/ChrisTitusTech/mybash/pull/75) that might fix this issue. In the meantime, I suggest either downloading the MesloLGS Nerd Font from the [Nerd Fonts Website](https://www.nerdfonts.com/font-downloads) or installing the FiraCode Nerd Font from the same website and updating the font in your Alacritty config, depending on your preference.

Yep, perfect, it works now. Thanks!

**Comment by RazoBeckett** [comment]
@tsuza well as your issue is solved you can close this issue ... thanks!
