### ISSUE TITLE
SFTP issue

### ISSUE THREAD

**Issue by Jaredy899** [ChrisTitusTech/linutil#181]
after running the script and doing a full system update, and applying the bash prompt setup, I can no longer sftp into my system. 

SFTP session can not be started. Reason: Timeout waiting for response from SFTP subsystem

**Comment by Jaredy899** [comment]
I think I fixed the issue. I added this 
if [[ $iatest -gt 0 ]]; then
to check if the shell is interactive.

**Comment by jeevithakannan2** [comment]
I think the issue should be created in https://github.com/ChrisTitusTech/mybash
