### ISSUE TITLE
ArchTitus setup script in linutil

### ISSUE THREAD

**Issue by jsteinbraker** [ChrisTitusTech/linutil#186]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
I apologize if this is already answered but i really need archtitus setup script into linutil as i want to the extreme dump windows for my work load.

**Comment by jsteinbraker** [comment]
Sorry about the above not being right but i would like to have a ArchTitus Script to install from linutil. Also i need it as soon as possible because I am disgusted by windows since 11 came out. I apologize again for the first issue i submitted not being formatted correctly. I will do better next time.

**Comment by gjm19761** [comment]
i would like the nvidia issue fix too...

**Comment by sevu11** [comment]
> i would like the nvidia issue fix too...

What issues with nvidia? I've used Arch-Titus without issues with nvidia gtx 1070.

**Comment by nnyyxxxx** [comment]
Solved with #190 @jsteinbraker

**Comment by jsteinbraker** [comment]
SOLVED! Thanks @ChrisTitusTech
