### ISSUE TITLE
Linutil hung on Reloading Bus connectors crashed 

### ISSUE THREAD

**Issue by rAaLtZ** [ChrisTitusTech/linutil#201]
I was running linutil on my Arch install, and it crashed on realizing bus lanes and now on boot i got stuck on grub and I couldn't boot into arch and my keyboard didn't work not even on bios, I flushed bios to try and restart bus lanes and now my screen wont even turn on.

Help please

**Comment by rAaLtZ** [comment]
> Which script did you use? What crashed, the script or the TUI? And when? There's not much to go off of here. 

Iirc I used the dependencies script after using the update script, after it reached the reloading bus lanes portion at around 11:33am it crashed and when I rebooted my PC was unresponsive.

I spent the whole day trying to fix it, took the disk out flushed the BIOS tried rolling back the bios but to no avail, at one point I finally got back a responsive system that was trying to boot, as soon as I put it my drive thay has my Windows and my Arch system it started boot looping, not even 2 seconds of uptime instantly looped, I took the drive out, still happening, flushed BIOS with CMOS again, boot looping stopped and I'm back at square one where the screen doesnt display anything on boot.

**Comment by rAaLtZ** [comment]
No longer needed, after a whole 24 hours of debugging all of this on the hardware side thinking i had to reflash the bios, reseatting ram worked but then arch grub with dual boot kept boot looping. Took out  the NVME, deleted the arch partitions, reseatted RAM and it booted right up.

Still unsure what caused this.

From running the script it hung on the BUS lanes reloading, and everything became unresponsive, so i'd assume 1 of two things, either it crashed because of dual booting / it being a laptop and not a traditional desktop, or I assumed it crashed since everything was unresponsive for about 5-10 minutes and when I rebooted it, I actually stopped the reloading of the bus lanes myself and cucked myself.

Nevertheless, fully deleting the arch partitions and reseatting RAM worked, unsure as to why, since flushing the bios with the CMOS and battery disconnected for a whole night and then holding the power button for a minute to make sure every last bit of power was out of the system should've made the RAM also "reboot" per se.

**Comment by jeevithakannan2** [comment]
Do you use dual boot with linux and windows??

**Comment by rAaLtZ** [comment]
I was yes, had my C drive split into windows and some other bits and bobs, then I had about 30gb for ROOT 8gb swap and the rest for home for arch

**Comment by jeevithakannan2** [comment]
The new windows update ( August Update ) has broke dual booting. It has issues with grub and other bootloaders after updating. https://www.bleepingcomputer.com/news/microsoft/august-windows-security-update-breaks-dual-boot-on-linux-systems/

**Comment by rAaLtZ** [comment]
Still running W10 and thought that only applies to 11 and with secure boot enabled, which I also have off because of Arch.

Nevertheless after those news broke out I still booted just fine for a while, maybe it was just bad timing or something
