### ISSUE TITLE
Full System Update Breaks mirrorlist

### ISSUE THREAD

**Issue by TsankoTsankov** [ChrisTitusTech/linutil#205]
## Describe the bug
When running full system update core and extra mirrors break.
I am running the script on a fresh install of EndeavourOS. Before running the script yay -Syu and pacman -Syu worked fine. 

## To Reproduce
1. On a fresh install of EndeavourOS update the system and install packages
2. Run linutil
3. Select Full System Update

## Expected behavior
A full system update

## Screenshots
![Screenshot_20240827_180942](https://github.com/user-attachments/assets/ed440642-11a4-4550-a0b3-42ed2dc82fea)

**Comment by fam007e** [comment]
I use this function in my `.zshrc` to update my mirrorlist which is quite handy I think which can be used...
```sh
# Finds and adds fastest mirror lists for pacman
httpsmirrors() {
    temp_mirrorlist=$(mktemp)
    rate-mirrors --allow-root --protocol https arch | awk "/^# FINISHED AT:/ {p=1} p" > "$temp_mirrorlist"
    
    # Check if the output is non-empty
    if [ -s "$temp_mirrorlist" ]; then
        sudo tee /etc/pacman.d/mirrorlist < "$temp_mirrorlist"
        echo "Mirrorlist updated successfully."
    else
        echo "Failed to update mirrorlist. Retaining the previous list."
    fi
    
    rm -f "$temp_mirrorlist"
}
```
