### ISSUE TITLE
Error on line 198 (running on /linuxdev)

### ISSUE THREAD

**Issue by michaeldun123** [ChrisTitusTech/linutil#208]
## Describe the bug
I was installing archtitus on my mini pc and came up with the error after the essential utilities (network manager etc) Exact error says "/bin/bash: line 198 cd /tmp/linutil_scrips.llPufCmADD9g/system-setup/arch no such file or directory"

## To Reproduce
1. Run the dev branch of linutil (christitus.com/linuxdev)
2. Arch setup
3. Try and install archtitus

## Expected behavior
Not to error/continue with install

**Comment by michaeldun123** [comment]
Screenshot![image](https://github.com/user-attachments/assets/5c38e0bc-0579-4360-9722-21daf62d2674)

**Comment by Glen-Sumner** [comment]
I got the same error but I rebooted into arch server ok ( didn't time all this was in the 2 minute region though) and installed plasma back around to linutil for install other bits after I now have fingers crossed but yes that error was there at install...

**Comment by sevu11** [comment]
I was able to replicate this issue as well. However, if you exit out of linutil and reboot your system you'll see that it did install the server.  But the error is dumb and will confuse users.

![2024-08-29_10-18_1](https://github.com/user-attachments/assets/8b681a80-fa3a-40e7-9b3e-8236e2eb2dcd)

**Comment by sevu11** [comment]
Playing around with the script code locally, if adding a `mkdir -p /tmp/` and comment out the cd line inside "Cleaning", seem to resolve this issue. 

I'm not sure if its ommit any of the logic around reverting the sudors though.

**Comment by michaeldun123** [comment]
> I was able to replicate this issue as well. However, if you exit out of linutil and reboot your system you'll see that it did install the server.  But the error is dumb and will confuse users.
> 
> 
> 
> ![2024-08-29_10-18_1](https://github.com/user-attachments/assets/8b681a80-fa3a-40e7-9b3e-8236e2eb2dcd)
> 
> 

And I think that is why it confused me a lot. As the error popped up and didn't even think to test it out if it installed or not

**Comment by michaeldun123** [comment]
@ChrisTitusTech is there any chance that this could be looked into? I know you mainly look at PRs but. Not sure if this is worth a PR. Plus. Not sure what to mainly fix. As I had a look at the code and line 194 doesn't say anything about it

**Comment by ChrisTitusTech** [comment]
> @ChrisTitusTech is there any chance that this could be looked into? I know you mainly look at PRs but. Not sure if this is worth a PR. Plus. Not sure what to mainly fix. As I had a look at the code and line 198 doesn't say anything about it

I think I fixed this and in the next latest release it will work properly.
