### ISSUE TITLE
Exit button or hotkey must be added.

### ISSUE THREAD

**Issue by fam007e** [ChrisTitusTech/linutil#214]
I'm always frustrated when using the linutil utility because pressing `CTRL+C` does not exit the utility as expected. This makes it difficult to exit the program quickly and interrupts the workflow, especially when I want to abort the current operation.

Hence, I would like the utility to include a clear exit option, either through a visible "Exit" button in the UI or by mapping a hotkey (e.g., `CTRL+C` or `ESC`) that immediately exits the utility. This would provide a straightforward way to terminate the program without confusion.

As an alternative, the utility could display a prompt asking for confirmation before exiting when `CTRL+C` is pressed, or it could introduce an additional hotkey that functions solely to exit the utility.

Adding this feature would improve the user experience by allowing users to exit the utility in a more intuitive and expected manner, aligning with common behavior in terminal-based applications.

**Comment by nnyyxxxx** [comment]
( Q ) Is this current keybind to exit Linutil.
