### ISSUE TITLE
Question to all LinUtil Users

### ISSUE THREAD

**Issue by Real-MullaC** [ChrisTitusTech/linutil#222]
Should there be a LinUtil community discord server?

**Comment by rudra-code-creator** [comment]
Sure why not

**Comment by 4yman-0** [comment]
you can make this a discussion.
>We’re using Discussions as a place to connect with other members of our community. We hope that you:
    1. Ask questions you’re wondering about.
    2. **Share ideas.**

[Welcome to linutil Discussions!](https://github.com/ChrisTitusTech/linutil/discussions/185)
BTW name this "make LinUtil Discord server"
