### ISSUE TITLE
sudo group

### ISSUE THREAD

**Issue by abdullahazmy** [ChrisTitusTech/linutil#23]
![image](https://github.com/user-attachments/assets/ca4770e8-7aaa-42a5-9395-3691a97fad52)

Even if i run the command with sudo, the same issue comes ..
Using Debian 12

**Comment by lovwanshichetan** [comment]
To add the user to sudoers group run:
`EDITOR=nvim visudo`

then Uncomment the line (Remove #):
# %wheel ALL=(ALL) ALL

**Comment by abdullahazmy** [comment]
> [!NOTE]
> The user is already in the sudoers group

**Comment by lovwanshichetan** [comment]
Seems like this script has some serious issue, it broke my internet in terminal, now both w3m & pacman are not working here and ping says 100% packet loss although brave is working, maybe 'coz it's a flatpak on my arch.

**Comment by RazoBeckett** [comment]
@arch-holic can you tell us what script did you ran, so that it would be easier to fix.

**Comment by smogan** [comment]
> ![image](https://private-user-images.githubusercontent.com/125517573/348699279-ca4770e8-7aaa-42a5-9395-3691a97fad52.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyODk3MDQsIm5iZiI6MTcyMTI4OTQwNCwicGF0aCI6Ii8xMjU1MTc1NzMvMzQ4Njk5Mjc5LWNhNDc3MGU4LTdhYWEtNDJhNS05Mzk1LTM2OTFhOTdmYWQ1Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxOFQwNzU2NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zM2YxODA5MDc5MzhlMjUxZjQwMzNlMDg3N2VjMmViM2Q0ODk2YTAwNjZmNDQ3Zjc4NzIzZGU5NDg0NWM4YjUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yefkwk19PfD8UFdkF9KlD-t9Vw_VIEPko7GlGjG5CiQ)
> 
> Even if i run the command with sudo, the same issue comes .. Using Debian 12

same here when running the script as a user (dietpi x86_64, based on debian 12). the suggested fix from arch-holic to uncomment the %weel does not work here beause there is no %wheel group on dietpi. I can run the script with no errors when switching via "su" command to root user.

**Comment by abdullahazmy** [comment]
@smogan Yes this is really the solution to the issue, but not sure if it's the only way to solve it, as some people don't like to run scripts as root user

**Comment by smogan** [comment]
> @smogan Yes this is really the solution to the issue, but not sure if it's the only way to solve it, as some people don't like to run scripts as root user

of course this is not a suitable solution 🙂. also there were other problems, but that's likely off topic in this thread.

**Comment by assasen11** [comment]
This also failed on a Fedora 40 install I was testing.

**Comment by jeevithakannan2** [comment]
Can you please confirm whether the issue still persists?

**Comment by assasen11** [comment]
> Can you please confirm whether the issue still persists?

In my testing so far for Fedora 40, I have went through a lot of the options that work on Fedora and I am not seeing this error occur anymore. It appears to be fixed on Fedora 40.

**Comment by abdullahazmy** [comment]
> Can you please confirm whether the issue still persists?

It's now solved. I will close the issue

**Comment by abdullahazmy** [comment]
The issue has been solved in Debian, thank you!
