### ISSUE TITLE
sudo password entry | backspace not working

### ISSUE THREAD

**Issue by pik4li** [ChrisTitusTech/linutil#230]
## Describe the bug
When updating the system or other things, which need the sudo password, you can type in the password. But when you try to delete the last character, it puts in "more characters" instead of deleting the last one.

## To Reproduce
1. Go to 'System Setup'
2. Click on 'Full System Update'
3. Type in your sudo password
4. Try to delete a charakter (i have Defaults pwfeedback configured in /etc/sudoers)
5. See error (more charakters spawning when pressing backspace)

## Expected behavior
Delete the last charakter.

## Additional context
I've tried this in windows wsl, but i guess the behaviour would be the same on a linux system. I'll try to update the issue when I'm home and test the behaviour from a "real" linux box.

I just wanted do say thank you, for such a great tool. About the same time you began doing the linutil, I was getting better in bash scripts and wanted something with the same functionality. Now im practicing to maybe contribute some code as well :)

Excuse my bad English. Greetings from germany though <3

**Comment by maheshrijal** [comment]
Weirdly I can still reproduce this but, I can see it's already merged 🤔

**Comment by pik4li** [comment]
Yeah same here, on my setups, i can also still reproduce this..

@ChrisTitusTech this issue is still relevant.


Systeminformation:

Ubuntu 24.04 LTS
WM: Hyprland
Device: Lenovo Yoga slim 6 | qwertz Layout (Maybe it has to do something with it?)
Terminal: tested in Kitty, Wezterm, also TTY
Shell: zsh
