### ISSUE TITLE
dwm not installing on debian/ubuntu

### ISSUE THREAD

**Issue by Jaredy899** [ChrisTitusTech/linutil#232]
the following happens when trying to install on debian/ubuntu. Doesn't happen on Arch or fedora. Although I can't get dwm to work on fedora either. 

![Screenshot (1)](https://github.com/user-attachments/assets/a2f48d8e-ef03-4886-aa1d-01f08f41fcf1)

**Comment by Jaredy899** [comment]
To get fedora server working with dwm, I had to install all these dependencies. sudo dnf groupinstall "Development Tools" "X Window System" && \
sudo dnf install xorg-x11-server-Xorg xinit xterm libev libev-devel imlib2 imlib2-devel \
xcb-util-image xcb-util-image-devel xcb-util-renderutil xcb-util-renderutil-devel \
xcb-util xcb-util-devel libconfig libconfig-devel libepoxy libepoxy-devel dbus-devel && \
wget https://raw.githubusercontent.com/troydhanson/uthash/master/src/uthash.h && \
sudo mv uthash.h /usr/local/include/

**Comment by nnyyxxxx** [comment]
Will be solved with the merge of #282
