### ISSUE TITLE
Hard to kill

### ISSUE THREAD

**Issue by solomoncyj** [ChrisTitusTech/linutil#236]
## To Reproduce
lauch `./start.sh`
hit CTRL +c
nothing happens
## Expected behavior
script exits

**Comment by nnyyxxxx** [comment]
' Q ' Is the current keybind to exit Linutil.

**Comment by solomoncyj** [comment]
> ' Q ' Is the current keybind to exit Linutil.

but it is not evryone's  first guess to exit an application
