### ISSUE TITLE
Resizing window hides the text. 

### ISSUE THREAD

**Issue by Mxstyz** [ChrisTitusTech/linutil#242]
Hides the contents of the menu until you navigate back up.

1. Run the script.
2. Navigate to the bottom on either side.
3. Resize the window to be very small.
4. Resize the window to full size. 

![image](https://github.com/user-attachments/assets/6e84c504-f3e7-4222-947b-3fde27b406c5)

I'm using Hyprland, Foot terminal and zsh if that makes a difference.  This problem is not severe but i just wanted to mention it.

**Comment by jeevithakannan2** [comment]
Please check if issue still persists

**Comment by Mxstyz** [comment]
> Please check if issue still persists

Yes, this issue still persists on my end.

**Comment by jeevithakannan2** [comment]
It is not specific to Hyprland, Foot terminal and zsh. It happens in dwm and bash too with other terminal emulators. Will dig into this and let you know

**Comment by jeevithakannan2** [comment]
The work around for this will be implemented  #425
