### ISSUE TITLE
Show the commands that are executed.

### ISSUE THREAD

**Issue by maheshrijal** [ChrisTitusTech/linutil#245]
I would love to see an `advanced` or `dev` mode that shows the commands that are going to be run for any selected option. Perhaps this would be more useful to daily Linux users who want to know what happens behind the scenes. 

Also, this tool is amazing. ❤️

**Comment by lj3954** [comment]
Each script is completely separate, so this would be quite involved. The linutil TUI has very little control over the scripts it launches.

**Comment by jeevithakannan2** [comment]
> I would love to see an `advanced` or `dev` mode that shows the commands that are going to be run for any selected option. Perhaps this would be more useful to daily Linux users who want to know what happens behind the scenes.
> 
> Also, this tool is amazing. ❤️

You can press **P** on any selected option and it will show you the commands that will be executed for the selected option

**Comment by maheshrijal** [comment]
> You can press **P** on any selected option and it will show you the commands that will be executed for the selected option

Ah! this is similar to what I needed. Looking at the script can figure out what is going to run. Perhaps an indication to **P** could be added somewhere.

**Comment by jeevithakannan2** [comment]
I am working on this will be added soon

**Comment by nnyyxxxx** [comment]
As jeevi said above this has been implemented and is in the current release.
