### ISSUE TITLE
Bluetooth manager fails on ZorinOS(Debian)

### ISSUE THREAD

**Issue by maheshrijal** [ChrisTitusTech/linutil#246]
## Describe the bug
Bluetooth Manager fails on Zorin OS 17.1

## To Reproduce
1. Go to 'Utilities'
2. Run 'Bluetooth manager'

## Screenshots
![image](https://github.com/user-attachments/assets/9595b7e9-25f9-49fd-a35e-32f97ec5172a)

**Comment by maheshrijal** [comment]
I might have figured this out. I think the redirection `<<<` operator does not work in the `sh` shell it only works on `bash`.

**Comment by maheshrijal** [comment]
Perhaps replacing the line 78 in `bluetooth-control.sh` will fix this? 

Old: `IFS=$'\n' read -r -a device_list <<<"$devices"`
New: `echo "$devices" | IFS=$'\n' read -r -a device_list`

**Comment by guruswarupa** [comment]
at first when i pushed, it was in bash. Later they changed it cause it was not working in ubuntu to use sh instead of bash :)

**Comment by maheshrijal** [comment]
Ah I see. I pushed a patch after I was able to ran it locally.
