### ISSUE TITLE
Issue with autocompletion in portable-pty terminal, used in running scripts.

### ISSUE THREAD

**Issue by guruswarupa** [ChrisTitusTech/linutil#249]
## Describe the bug
Issue with autocompletion in portable-pty terminal, used in running scripts. seems to be an issue with the package portable-pty used as another terminal instance to run other bash scripts such as in utils.

## To Reproduce
1. Go to Utils and run any script
2. if  tab is pressed for autocompletion, it doesn't work.

## Expected behavior
similar behaviour as the terminal which is used.

**Comment by nnyyxxxx** [comment]
Linutil has no support for tab-completion. Also most shells only have support when specifying a command to use before hand.

/close
