### ISSUE TITLE
Exec format error

### ISSUE THREAD

**Issue by mews-se** [ChrisTitusTech/linutil#25]
While trying to run this i get:

`sh: 27: /tmp/tmp.hjqiUgorVk: Exec format error
ERROR: Executing linutil`

Also trying to download the file and run with both bash and sh:

`./start.sh: 27: /tmp/tmp.c44F4VrSUu: Exec format error
ERROR: Executing linutil`

Just a quick question, is this Arch only? This is on a Debian based system.

**Comment by guruswarupa** [comment]
i ran it in debian 12 and it worked perfectly fine

**Comment by mews-se** [comment]
Could it be because of arm?

**Comment by FrostyNick** [comment]
It seems like Rust executable needs to also be compiled for ARM and then it will probably work if your computer uses an ARM processor since below shows "x86-64".

```sh
$ file linutil
linutil: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically link
ed, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=743f2ea0f7f24097882d90
32552ec986d27c3818, for GNU/Linux 3.2.0, not stripped
```
