### ISSUE TITLE
Start.sh on ARM64 is getting an error: ERROR: Downloading linutil

### ISSUE THREAD

**Issue by claymeisman** [ChrisTitusTech/linutil#252]
## Describe the bug
While using a raspberry pi running ubuntu 
When I run start.sh I get "ERROR: Downloading linutil"

## To Reproduce
1. On a Raspberry pi (Or ARM64 processor)
2. Run "curl -fsSL https://christitus.com/linux"
3. See error

## Expected behavior
It to download the linutil-aarch64 file and run it

## Additional context
I notice in the past few releases there is not a linutil-aarch64 file in the release set, if this is deprecated then the start script needs be updated.

**Comment by lj3954** [comment]
https://github.com/ChrisTitusTech/linutil/issues/259#issuecomment-2332967536

**Comment by adamperkowski** [comment]
#496
