### ISSUE TITLE
[Feature request] Change Default Terminal Editor (ex: from vi to nano)

### ISSUE THREAD

**Issue by mathe00** [ChrisTitusTech/linutil#255]
**Title:** Option to change the default terminal editor (ex: from vi to nano)

**Comment:**

**Is your feature request related to a problem? Please describe.**

Using `vi` as the default terminal editor can be challenging, especially for less experienced users. Many users find `nano` much more intuitive and user-friendly for basic text editing.

**Describe the solution you'd like**

Adding an option in Linutil to change the default terminal editor during setup would be great. For instance, allowing users to select between `vi`, `nano`, or another editor would enhance user experience, especially for beginners.

**Describe alternatives you've considered**

Users can manually change the default editor by adjusting the symbolic link in `/etc/alternatives/editor`, but having this option integrated into Linutil would provide a smoother, more user-friendly process.

**Additional context**

This small feature would make the utility even more accessible to a wider range of users. Thank you for considering this, and for all the amazing work you’ve put into Linutil!

---

Thank you so much for all the hard work you've put into this project. Linutil is an amazing tool, and it’s truly making Linux more accessible and user-friendly. I’ve also suggested a few other features in separate issues that might interest you, and I’d be excited to see any of these improvements considered.

Again, I really appreciate the dedication and effort from the development team. Keep up the great work, and thanks for making the Linux experience better for everyone! 🙌

**Comment by nnyyxxxx** [comment]
This would conflict with the users shell configuration

**Comment by mathe00** [comment]
> This would conflict with the users shell configuration

We just have to put a warning in this case

**Comment by nnyyxxxx** [comment]
/close not planned

This will conflict with the users shell configuration. Also this is very unnecessary for people who use GUI based text editors.

I'll look into it and re-open this in the future if I think it can be viable.
