### ISSUE TITLE
[Feature request] Seamless Conversion Between GRUB and systemd-boot

### ISSUE THREAD

**Issue by mathe00** [ChrisTitusTech/linutil#256]
**Title:** Add an option to seamlessly switch between GRUB and systemd-boot

**Comment:**

**Is your feature request related to a problem? Please describe.**

Switching between GRUB and systemd-boot can be tricky, with the risk of leaving the system unbootable if something goes wrong. A clean and safe way to convert between these bootloaders would be incredibly useful for users looking to experiment or optimize their setup.

**Describe the solution you'd like**

It would be great if Linutil could provide an option to easily switch from GRUB to systemd-boot (and vice versa) while creating a backup of the current bootloader configuration. This way, users can safely test different bootloaders without worrying about breaking their system.

**Describe alternatives you've considered**

While manual bootloader switching is possible, it involves several complex steps. Automating this process in Linutil would significantly reduce the chances of errors and improve usability.

**Additional context**

Offering a safe bootloader switching option would add great flexibility for users. Thank you for all the effort you've put into making Linux easier to use!

---

Thank you so much for all the hard work you've put into this project. Linutil is an amazing tool, and it’s truly making Linux more accessible and user-friendly. I’ve also suggested a few other features in separate issues that might interest you, and I’d be excited to see any of these improvements considered.

Again, I really appreciate the dedication and effort from the development team. Keep up the great work, and thanks for making the Linux experience better for everyone! 🙌

**Comment by nnyyxxxx** [comment]
This could brick systems if we're not careful, so this is not planned for now.
