### ISSUE TITLE
[Feature request] Help Identify and Set the Correct Microphone Input Source

### ISSUE THREAD

**Issue by mathe00** [ChrisTitusTech/linutil#257]
**Title:** Assist in identifying and setting the correct microphone input source

**Comment:**

**Is your feature request related to a problem? Please describe.**

Configuring the correct microphone input source on Linux can sometimes be a challenge, especially on systems with multiple input devices. This can cause frustration, particularly when using applications that require a functioning microphone.

**Describe the solution you'd like**

It would be helpful to add a feature in Linutil that helps users identify and set the correct microphone input source. This could be done through an interactive interface or an automated script that detects available devices and allows the user to choose the right one.

**Describe alternatives you've considered**

While tools like `pavucontrol` allow users to configure the microphone manually, integrating this functionality into Linutil would make the process more straightforward, especially for less experienced users.

**Additional context**

This could be an optional feature, but it would definitely help users who struggle with audio input issues. Once again, thank you for all your amazing work on Linutil. It’s been incredibly helpful!

---

Thank you so much for all the hard work you've put into this project. Linutil is an amazing tool, and it’s truly making Linux more accessible and user-friendly. I’ve also suggested a few other features in separate issues that might interest you, and I’d be excited to see any of these improvements considered.

Again, I really appreciate the dedication and effort from the development team. Keep up the great work, and thanks for making the Linux experience better for everyone! 🙌

**Comment by adamperkowski** [comment]
> Configuring the correct microphone input source on Linux can sometimes be a challenge, especially on systems with multiple input devices.

A quick google search usually ends this "challange"

This would need to take different audio backends to consideration and install needed tools. In this case, a quick google search is a better solution.
