### ISSUE TITLE
Shell layout is grabled after installation on Linux Mint 21 and 22     

### ISSUE THREAD

**Issue by attilafelker** [ChrisTitusTech/linutil#263]
## Describe the bug
Shell layout is garbled after installation on Linux Mint 21 and 22 . It looks like certain fonts are not working properly.

**Comment by sonnycc** [comment]
Same here. I'm on Kubuntu. I ran the Bash prompt script with no errors after manually installing fastfetch.
![Screenshot_20240906_050504](https://github.com/user-attachments/assets/f8bd9677-50b8-495f-baa6-b6254da96074)

![Screenshot_20240906_050259](https://github.com/user-attachments/assets/adcb4d3b-6e01-466b-862a-e235fe86d00c)

**Comment by attilafelker** [comment]
interesting that we have different level of garbling. the arrows at the prompt look ok, mine don't.

**Comment by attilafelker** [comment]
Solution to this problem
https://github.com/ChrisTitusTech/linutil/issues/284.
Closing.Thanks!

**Comment by sonnycc** [comment]
I have the font installed. Ninth last line in my first screengrab. Do we need any other fonts?

**Comment by attilafelker** [comment]
You need to refresh your font cache :
fc-cache -f -v 

Then You also need to select this font in your terminal preferences :
![image](https://github.com/user-attachments/assets/d0ba1379-830c-41d6-8e93-93a9d335a327)
