### ISSUE TITLE
Failed Application Setup Neovim

### ISSUE THREAD

**Issue by J-eremy** [ChrisTitusTech/linutil#265]
## Describe the bug
After setting up Neovim in the application setup, when launching neovim it tries to install the plugins and fails from not being able to resolve github.com 

## To Reproduce
1. Go to Application Setup
2. Click on Neovim
3. Let install then launch nvim

## Expected behavior
I expect gold coins to rain from the sky, no insomnia, and world peace.
Oh, and neovim to work.

## Screenshots
![image](https://github.com/user-attachments/assets/bd6d376c-e591-4087-aceb-4feed38ddf58)

## Additional context
Here is a snippet of the above screenshot.
```
  Total: 40 plugins

  Failed (39)
    ○ alpha-nvim 
        Cloning into '/home/jeremy/.local/share/nvim/lazy/alpha-nvim'...
        remote: Enumerating objects: 1006, done.        
        remote: Counting objects: 100% (223/223), done.        
        remote: Compressing objects: 100% (96/96), done.        
        remote: Total 1006 (delta 136), reused 154 (delta 125), pack-reused 783 (from 1)        
        Receiving objects: 100% (1006/1006), 118.33 KiB | 3.38 MiB/s, done.
        Resolving deltas: 100% (248/248), done.
        fatal: unable to access 'https://github.com/goolord/alpha-nvim.git/': Could not resolve host: github.com
        fatal: could not fetch 5818065cfb64e932cebc45ed6d3819b7c3b80ca7 from promisor remote
        warning: Clone succeeded, but checkout failed.
        You can inspect what was checked out with 'git status'
        and retry with 'git restore --source=HEAD :/'
```
The rest is just like that x 39

This seems to be related to lazyvim trying to install the plugins after linutil put the configs in place and was on Manjaro.

The clone is successful, but the checkout fails. If you go into the directory its trying to do the checkout in, all the files are staged for deletion, if you reset to master/main the files show up. But then on launch they try to change to the nonexistent hash again.

**Comment by cartercanedy** [comment]
this looks like an issue with [Chris's neovim config](https://github.com/christitustech/neovim), so I'd put an issue in over there and close this one
