### ISSUE TITLE
Duplicate pre-release

### ISSUE THREAD

**Issue by nnyyxxxx** [ChrisTitusTech/linutil#266]
Might want to delete one of those @ChrisTitusTech

**Comment by lj3954** [comment]
I don't see duplicates. They're a few hours apart, and the one marked by today's date includes a rather major fix (#233).

**Comment by nnyyxxxx** [comment]
@lj3954 On my screen there are duplicates and both of them are marked as a Pre-Release.
![image](https://github.com/user-attachments/assets/200d1122-1fa8-4c6d-9c49-da886849665d)

**Comment by lj3954** [comment]
Those are not duplicates. Once again, read my reply.

**Comment by nnyyxxxx** [comment]
Yeah I see now, thanks for the explanation.
