### ISSUE TITLE
Setup for utility to take system file snapshots

### ISSUE THREAD

**Issue by Kingproone** [ChrisTitusTech/linutil#267]
**Describe the solution you'd like**
In one of his streams Chris mentioned a utility that does system backup, but only of the system files, no user data, this could be very helpful, especially since there have been quite a few bug reports about no option to revert changes made to ones system.
This could also be used, so if the script could somehow detect, that the app is installed on ones system, they would get prompted to install it and make a backup before doing any modifications.

**Comment by adamperkowski** [comment]
#228

**Comment by nnyyxxxx** [comment]
Timeshift setup has been added to Linutil, use that for this purpose.
