### ISSUE TITLE
Making it easier to setup up the Steam Deck OLED on vanilla arch.

### ISSUE THREAD

**Issue by defiling9046** [ChrisTitusTech/linutil#269]
**Is your feature request related to a problem? Please describe.**

Wi-Fi, Bluetooth as well as audio does not work on a base vanilla arch install for the Steam Deck OLED out of the box.

**Describe the solution you'd like**

A script to setup Wi-Fi, Bluetooth and the audio for the Steam Deck OLED on a vanilla arch install.

**Describe alternatives you've considered**

I've tried following the arch wiki with no luck after installing what it says to install to get the wi-fi etcetera working even after a restart.

Using something like Nobara which comes with steam deck Wi-Fi, Bluetooth and audio working out the box when using the Steam Deck version of Nobara.

Giving up and using SteamOS

**Additional context**
Edit: this might help as these were used in winesapos (which is based on arch linux) for the steam deck oled so a script to automatically insteall these would be great! You can find these being talked about on the winesapos github description where it talks about the steam deck being fully supported on winesapos.

**steam deck oled vanilla arch patches:**

https://pagure.io/kernel-fsync/blob/main/f/SOURCES/steamdeck-oled-audio.patch

https://aur.archlinux.org/packages/linux-firmware-valve

https://pagure.io/kernel-fsync/blob/main/f/SOURCES/steamdeck-oled-legion-go-bluetooth-hang.patch

https://pagure.io/kernel-fsync/blob/main/f/SOURCES/steamdeck-oled-wifi.patch

**Comment by nnyyxxxx** [comment]
If internet does not work on a base installation of Arch on the steam-deck oled how would you ``curl`` Linutil to then install the proposed features here?

**Comment by defiling9046** [comment]
> If internet does not work on a base installation of Arch on the steam-deck oled how would you `curl` Linutil to then install the proposed features here?

I would dock it and use ethernet to install the Wi-Fi driver via linutil and then undock it now having the ability to use the Steam Deck portably whilst being able to have internet via Wi-Fi. Hope I answered your question. Happy to answer any follow-up questions or a different question.

**Comment by defiling9046** [comment]
> > If internet does not work on a base installation of Arch on the steam-deck oled how would you `curl` Linutil to then install the proposed features here?
> 
> I would dock it and use ethernet to install the Wi-Fi driver via linutil and then undock it now having the ability to use the Steam Deck portably whilst being able to have internet via Wi-Fi (Edit:As well as hopefully the Bluetooth and Audio drivers). Hope I answered your question. Happy to answer any follow-up questions or a different question.
> 
> Edit: Sorry for replying a whole 20 hours after you commented. Haven’t checked GitHub in a while.

Edit 2: Since I can’t contribute any proper steps on how to implement this feature I just thought i’d sponsor the project as I feel like when I ask for something I should have to do something for it since I don’t like asking for stuff for free. I’m learning computer science/software development atm in college so maybe someday i’ll be able to help the project out through pull requests etc instead of just donations.

**Comment by adamperkowski** [comment]
> blue-tooth

💀

> shouldnt be an issue

poor word choice

**Comment by defiling9046** [comment]
> wifi-control and blue-tooth control already set up and install wifi / bluetooth for you, we could add a script to set up audio as well; shouldnt be an issue.

Thank you. Became a sponsor to show my love for the project as well as not liking to ask for something for free. $2 isn’t alot but I haven’t got alot tbh lol.

**Comment by defiling9046** [comment]
Hey. Just out of interest where do i go to enable these steam deck pacthes in linutil and is it in the stable or the unstable version of linutil?

**Comment by defiling9046** [comment]
> Hey. Just out of interest where do i go to enable these steam deck patches in linutil and is it in the stable or the unstable version of linutil?

Edit: Or do i wait for a new release of linutil?

**Comment by adamperkowski** [comment]
> Hey. Just out of interest where do i go to enable these steam deck patches in linutil and is it in the stable or the unstable version of linutil?

Like @nnyyxxxx mentioned, there is no universial Steam Deck script, but we have WiFi & Bluetooth manager setup (don't know what's going on with audio).

**Comment by defiling9046** [comment]
> > Hey. Just out of interest where do i go to enable these steam deck patches in linutil and is it in the stable or the unstable version of linutil?
> 
> Like @nnyyxxxx mentioned, there is no universial Steam Deck script, but we have WiFi & Bluetooth manager setup (don't know what's going on with audio). For manual audio setup, you can see the [Archwiki](https://wiki.archlinux.org/title/PipeWire#Installation).
> 
> EDIT: Audio Control got closed because it's gonna conflict with the existing audio software on user's system.



> > Hey. Just out of interest where do i go to enable these steam deck patches in linutil and is it in the stable or the unstable version of linutil?
> 
> Like @nnyyxxxx mentioned, there is no universial Steam Deck script, but we have WiFi & Bluetooth manager setup (don't know what's going on with audio). For manual audio setup, you can see the [Archwiki](https://wiki.archlinux.org/title/PipeWire#Installation).
> 
> EDIT: Audio Control got closed because it's gonna conflict with the existing audio software on user's system.

so does that mean it has the steam deck patches for wi-fi as i'm fairly sure it needs patches for wi-fi to work on vanilla arch for the steam deck OLED version which is the version of the steam deck i have got. You can see the arch wiki for more detail.

**Comment by defiling9046** [comment]
> > Hey. Just out of interest where do i go to enable these steam deck patches in linutil and is it in the stable or the unstable version of linutil?
> 
> Like @nnyyxxxx mentioned, there is no universial Steam Deck script, but we have WiFi & Bluetooth manager setup (don't know what's going on with audio). For manual audio setup, you can see the [Archwiki](https://wiki.archlinux.org/title/PipeWire#Installation).
> 
> EDIT: Audio Control got closed because it's gonna conflict with the existing audio software on user's system.

so does that mean it has the steam deck patches for wi-fi as i'm fairly sure it needs patches for wi-fi to work on vanilla arch for the steam deck OLED version which is the version of the steam deck i have got. You can see the arch wiki for more detail.

**Comment by defiling9046** [comment]
> > > Hey. Just out of interest where do i go to enable these steam deck patches in linutil and is it in the stable or the unstable version of linutil?
> > 
> > 
> > Like @nnyyxxxx mentioned, there is no universial Steam Deck script, but we have WiFi & Bluetooth manager setup (don't know what's going on with audio). For manual audio setup, you can see the [Archwiki](https://wiki.archlinux.org/title/PipeWire#Installation).
> > EDIT: Audio Control got closed because it's gonna conflict with the existing audio software on user's system.
> 
> so does that mean it has the steam deck patches for wi-fi as i'm fairly sure it needs patches for wi-fi to work on vanilla arch for the steam deck OLED version which is the version of the steam deck i have got. You can see the arch wiki for more detail.

As it states on the steam deck arch wiki "They can be made to work on the OLED models by using the neptune kernel from Valve's jupiter repository." which is what I think it needs for wi-fi to work on the steam deck OLED.

**Comment by defiling9046** [comment]
> > > Hey. Just out of interest where do i go to enable these steam deck patches in linutil and is it in the stable or the unstable version of linutil?
> > 
> > 
> > Like @nnyyxxxx mentioned, there is no universial Steam Deck script, but we have WiFi & Bluetooth manager setup (don't know what's going on with audio). For manual audio setup, you can see the [Archwiki](https://wiki.archlinux.org/title/PipeWire#Installation).
> > EDIT: Audio Control got closed because it's gonna conflict with the existing audio software on user's system.
> 
> so does that mean it has the steam deck patches for wi-fi as i'm fairly sure it needs patches for wi-fi to work on vanilla arch for the steam deck OLED version which is the version of the steam deck i have got. You can see the arch wiki for more detail.
> 
> As it states on the steam deck arch wiki "They can be made to work on the OLED models by using the neptune kernel from Valve's jupiter repository." which is what I think it needs for wi-fi to work on the steam deck OLED.

Edit: This is kind of the main point i made this feature request……. (so that the steam deck oled is able to connect to the wi-fi.) wether it be from a script that sets up the patches or something.

**Comment by adamperkowski** [comment]
>This is kind of the main point i made this feature request……. (so that the steam deck oled is able to connect to the wi-fi.) wether it be from a script that sets up the patches or something.

Okay I see. I'll try to craft something.

**Comment by defiling9046** [comment]
> > This is kind of the main point i made this feature request……. (so that the steam deck oled is able to connect to the wi-fi.) wether it be from a script that sets up the patches or something.
> 
> Okay I see. I'll try to craft something.

If you

> > This is kind of the main point i made this feature request……. (so that the steam deck oled is able to connect to the wi-fi.) wether it be from a script that sets up the patches or something.
> 
> Okay I see. I'll try to craft something.

If you managed to pull that off that would be awesome. I left some resources at the bottom of my issue description to guide you on how you might be able to do it.

**Comment by defiling9046** [comment]
> > This is kind of the main point i made this feature request……. (so that the steam deck oled is able to connect to the wi-fi.) wether it be from a script that sets up the patches or something.
> 
> Okay I see. I'll try to craft something.

If you managed to pull that off that would be awesome. I left some resources at the bottom of my issue description to guide you on how you might be able to do it.

**Comment by adamperkowski** [comment]
> If you managed to pull that off that would be awesome. I left some resources at the bottom of my issue description to guide you on how you might be able to do it.

We can just add valve's pacman repos and install their kernel.

**Comment by defiling9046** [comment]
Thanks. I couldn't appreciate this enough. As soon as this gets added to the next release I will try it straight away to test wether it works.

**Comment by adamperkowski** [comment]
> Thanks. I couldn't appreciate this enough. As soon as this gets added to the next release I will try it straight away to test wether it works.

You can clone my fork, checkout the `linux_neptune` branch, compile it for yourself and check if it works now if you want to.

**Comment by defiling9046** [comment]
> > Thanks. I couldn't appreciate this enough. As soon as this gets added to the next release I will try it straight away to test wether it works.
> 
> You can clone my fork, checkout the `linux_neptune` branch, compile it for yourself and check if it works now if you want to.

Thanks, I am sorry to be a pain but would you be able to give me a step to step guide on how to do that has I haven’t learnt how to do that but would love to learn and if you could also as one of your first steps show me where to find the linux_neptune branch that would be much appreciated as i’m new to github and have only just recently started using it as I am a college student who just recently started learning computer science.

**Comment by adamperkowski** [comment]
Okay, so assuming you're on Arch:
```bash
sudo pacman -S git base-devel rustup
rustup default stable
git clone -b linux_neptune https://github.com/adamperkowski/linutil linutil_neptune
cd linutil_neptune
cargo build --release
./target/release/linutil
```

**Comment by defiling9046** [comment]
> Okay, so assuming you're on Arch:
> 
> ```shell
> sudo pacman -S git base-devel rustup
> rustup default stable
> git clone -b linux_neptune https://github.com/adamperkowski/linutil linutil_neptune
> cd linutil_neptune
> cargo build --release
> ./target/release/linutil
> ```

Used this command on my steam deck which is running a vanilla arch install with kde. 

Can confirm it does indeed work. Thankyou very much. I can now use the steam deck OLED with vanilla arch with Wi-Fi as well as Bluetooth. I could not thank you enough. 

However audio is not working yet so if there is a fix for that and you give me a command to do it I will be sure to try it out and tell you wether it works(audio through bluetooth works fine though as I connected my sony headphones through bluetooth which worked perfectly). 

This below is what it states about the audio on the steam deck OLED and how to fix it from the arch wiki:

“ Since mainline kernel version 6.6.2, the built-in speakers, microphone, and headphone jack only work on the LCD models.
On OLED models, they can be made to work with the neptune kernel from the jupiter repository, but this additionally requires manually installing the relevant firmware and ALSA configuration files from the steamdeck-dsp and alsa-ucm-conf packages from jupiter.‘

**Comment by defiling9046** [comment]
> > Okay, so assuming you're on Arch:
> > ```shell
> > sudo pacman -S git base-devel rustup
> > rustup default stable
> > git clone -b linux_neptune https://github.com/adamperkowski/linutil linutil_neptune
> > cd linutil_neptune
> > cargo build --release
> > ./target/release/linutil
> > ```
> 
> Used this command on my steam deck which is running a vanilla arch install with kde.
> 
> Can confirm it does indeed work. Thankyou very much. I can now use the steam deck OLED with vanilla arch with Wi-Fi as well as Bluetooth. I could not thank you enough.
> 
> However audio is not working yet so if there is a fix for that and you give me a command to do it I will be sure to try it out and tell you wether it works(audio through bluetooth works fine though as I connected my sony headphones through bluetooth which worked perfectly).
> 
> This below is what it states about the audio on the steam deck OLED and how to fix it from the arch wiki:
> 
> “ Since mainline kernel version 6.6.2, the built-in speakers, microphone, and headphone jack only work on the LCD models. On OLED models, they can be made to work with the neptune kernel from the jupiter repository, but this additionally requires manually installing the relevant firmware and ALSA configuration files from the steamdeck-dsp and alsa-ucm-conf packages from jupiter.‘

**Comment by adamperkowski** [comment]
> However audio is not working yet so if there is a fix for that and you give me a command to do it I will be sure to try it out

Added it in b3865960789fccf1fffbad6b0ca3deca4f578d85. You can test it out if you want to.
To update your clone do:
```bash
cd linutil_neptune
git pull origin/linutil_neptune
```

**Comment by defiling9046** [comment]
Tried it out and it doesn’t seem to work and the audio device doesn’t appear in the kde audio section on the taskbar even after a restart. On the Arch Wiki it says this about audio:

“On OLED models, they can be made to work with the neptune kernel from the jupiter repository, but this additionally requires manually installing the relevant firmware and ALSA configuration files from the steamdeck-dsp and alsa-ucm-conf packages from jupiter.”

**Comment by adamperkowski** [comment]
Hey @defiling9046. Sorry to bother you. I added a precondition check for SteamDeck devices here: 1dc748fa490b3bbf277942828db7e145e16311af. 
Could you run linutil from my branch on your SteamDeck again to check if you still see the entry?

**Comment by defiling9046** [comment]
> Hey @defiling9046. Sorry to bother you. I added a precondition check for SteamDeck devices here: [1dc748f](https://github.com/ChrisTitusTech/linutil/commit/1dc748fa490b3bbf277942828db7e145e16311af). Could you run linutil from my branch on your SteamDeck again to check if you still see the entry?

yeah sure i’ll do it soon as I just need to finish my college assignment and I looked at your code and I don’t know wether you mean jupiter as in the repositry or the name of the device as the OLED model goes under the name of Galileo as Jupiter is just for the LCD.👍

**Comment by defiling9046** [comment]
> > I don’t know wether you mean jupiter as in the repositry or the name of the device as the OLED model goes under the name of Galileo as Jupiter is just for the LCD.👍
> 
> Thank's for clearing that out. The commit was sourced here: [#683 (comment)](https://github.com/ChrisTitusTech/linutil/pull/683#discussion_r1781852071).
> 
> > Edit: I still haven’t found a fix for the Steam Deck Audio but i’ll see if there is anything else I can do.
> 
> Thanks.

Busy doing my college assignment at the moment so i’ll hopefully update you within the next 6 hours on wether this works.

**Comment by defiling9046** [comment]
> Hey @defiling9046. Sorry to bother you. I added a precondition check for SteamDeck devices here: [1dc748f](https://github.com/ChrisTitusTech/linutil/commit/1dc748fa490b3bbf277942828db7e145e16311af). Could you run linutil from my branch on your SteamDeck again to check if you still see the entry?

yeah it still has the script in the linutil as I did a:

cd linutil_neptune
git fetch && git pull

which i’m fairly sure updates it. Correct me if i’m wrong.

and then did:

./target/release/linutil to open linutil and the setup script is still there after I went into the arch tab on linutil👍

**Comment by lj3954** [comment]
> > I don’t know wether you mean jupiter as in the repositry or the name of the device as the OLED model goes under the name of Galileo as Jupiter is just for the LCD.👍
> 
> Thank's for clearing that out. The commit was sourced here: [#683 (comment)](https://github.com/ChrisTitusTech/linutil/pull/683#discussion_r1781852071).
> 
> > Edit: I still haven’t found a fix for the Steam Deck Audio but i’ll see if there is anything else I can do.
> 
> Thanks.

"Jupiter" should be unnecessary; we're checking the board vendor (Valve) rather than the name of the board. I realized that a few hours after I suggested the precondition.

**Comment by adamperkowski** [comment]
> "Jupiter" should be unnecessary; we're checking the board vendor (Valve) rather than the name of the board. I realized that a few hours after I suggested the precondition.

Yeah that's what I thought. But I was like "Maybe some boards are done differently idk"

**Comment by adamperkowski** [comment]
62330334dedc94ab58eaae80e8f3da4c5ad274a4

**Comment by testc2n14** [comment]
hey so i am skimming this thread and it seems people got audio working on the oled moddel how exactly, i have been trying stuff out and i can't get alsa to even see the built in dac (external dacs work) and the neptune kerrnel from valves jupiter repo has kerrnel panic on boot so not useable. any help or advice would be great
