### ISSUE TITLE
Exit out of the script is missing.

### ISSUE THREAD

**Issue by guruswarupa** [ChrisTitusTech/linutil#27]
the script cannot be closed by any terminal shortcuts such as ctrl + [ c,x,z]. would be better to add a new node Exit in the list.rs

**Comment by salehabdullah216** [comment]
it is CTRL+q

**Comment by guruswarupa** [comment]
> it is CTRL+q

Ahh how'd a new user know this unless he reads the doc.

I've added a pr with working exit option in the menu as of now let's see.
