### ISSUE TITLE
ERROR: Downloading linutil on aarch64 when script is executed. 

### ISSUE THREAD

**Issue by esguerrag** [ChrisTitusTech/linutil#275]
## Describe the bug
The script fails when it is executed on a CPU based on aarch64 processor. 

## To Reproduce
Run the ´curl´ command on a computer or container running over a ARM-based CPU

## Expected behavior
Launch the dashboard and allow to install the components. 

## Screenshots
<img width="1226" alt="image" src="https://github.com/user-attachments/assets/27415385-6c0c-4f75-ad57-8ee53df94a6a">

**Comment by esguerrag** [comment]
The script was executed in the following environment:
- podman version 5.2.2
- registry.fedoraproject.org/fedora:latest 
- CPU Apple M1 Pro

**Comment by cartercanedy** [comment]
The prebuilt binary distribution is for amd64 only. You'll have to clone the repo and build from source until that changes
