### ISSUE TITLE
add and friends

### ISSUE THREAD

**Issue by ShalokShalom** [ChrisTitusTech/linutil#279]
Hi there :) 

I have written a bunch of abstractions on top of Pacman.

They all work in tandem, `add` is to install new software.

The benefit of it is, *that you never end up with a partial update* since it always checks if your system is up to date, before it installs anything.

It also is capable of doing the update alone, when you call it without an argument.

When you need to reboot your computer because of an update, it will tell you that, and even provide you a timer for that reminder, if you like to postpone that reboot.

Just look into it, I currently separate the versions for Arch, Garuda and KaOS, since they all have slightly different dependencies and commands they use (AUR and KCP are also supported) into different repos, and I can see myself uniting them.

I also have a Youtube downloader, but that already exists in other forms, so its not as unique as the pacman abstractions.

Its all written in Fish, so we could add a check, if the user has installed that, if they are trying to use those abstractions (and/or add fish to the dependency list in the Arch package)

Much fun

https://codeberg.org/ShalokShalom/add-and-friends

**Comment by adamperkowski** [comment]
In what way would your abstractions benefit Linutil? What insurance we have this is not malware?
I see that these "abstractions" are shell functions in fish config that rely on paru (and have no error handling by the way).
I think addition like this would be redundant.

**Comment by ShalokShalom** [comment]
> In what way would your abstractions benefit Linutil? What insurance we have this is not malware? I see that these "abstractions" are shell functions in fish config that rely on paru (and have no error handling by the way). I think addition like this would be redundant.

If you cant see that there is no malware in a 100 lines of fish code, I dont know what I can say.

The error handling is also taken care for, and you are free to do, whatever you want.

Also, this is the attempt to prepare a PR, and in that sense, every PR is a form of self advertising.
