### ISSUE TITLE
Icons are not working in Linux Mint using Gnome terminal

### ISSUE THREAD

**Issue by kurdtpage** [ChrisTitusTech/linutil#284]
## Describe the bug
The terminal GUI icons do not display properly using Linux Mint 21.3 (xfce) using Gnome terminal 3.44

## To Reproduce
1. Download zip file from github
2. Extract zip file
3. cd into folder
4. Type sh ./start.sh

## Expected behavior
Should see nice images, see crappy ones instead

## Screenshots
![Screenshot_2024-09-06_20-37-01](https://github.com/user-attachments/assets/d6424960-4628-4804-94ab-6208a7bd9319)

## Additional context
The icon looks like:
EA
B5

**Comment by Nightmare1984** [comment]
need to install nerd fonts for the icons to work

**Comment by kurdtpage** [comment]
Which one? (Please don't say all of them)
https://www.nerdfonts.com/font-downloads

**Comment by bungadrum** [comment]
Meslo thats the one Chris uses

**Comment by kurdtpage** [comment]
Yay that worked! Thanks!
