### ISSUE TITLE
A Titus title

### ISSUE THREAD

**Issue by JustLinuxUser** [ChrisTitusTech/linutil#285]
Hey @ChrisTitusTech What do you think about having a little more credit :)
![image](https://github.com/user-attachments/assets/578af32b-fa72-4314-b9e4-8175e481bbe7)
Should something like that be added?

**Comment by nnyyxxxx** [comment]
Looks good but will conflict with #239

**Comment by JustLinuxUser** [comment]
> Looks good but will conflict with #239

I think 239 is a cool idea, but is not fully finished, I think there should be a bottom line below everything where all keyboard shortcuts in the current context are listed, and it changes depending on the focused item

**Comment by JustLinuxUser** [comment]
I may or may not be working on that rn :) (I am)

**Comment by JustLinuxUser** [comment]
> > Looks good but will conflict with #239
> 
> I think 239 is a cool idea, but is not fully finished, I think there should be a bottom line below everything where all keyboard shortcuts in the current context are listed, and it changes depending on the focused item

I have created a prototype of that in #293

**Comment by Nightmare1984** [comment]
That does look Really

**Comment by adamperkowski** [comment]
This issue should be closed. Already implemented.

**Comment by nnyyxxxx** [comment]
As Adam said above this has been implemented.
