### ISSUE TITLE
Neovim Fails Install -- missing packages that aren't

### ISSUE THREAD

**Issue by muddyexport** [ChrisTitusTech/linutil#286]
## Describe the bug
Selecting the Neovim install I receive the following (and is the only failure I've encountered):

The following packages are not installed:
ripgrep, fzf, xclilp, neovim, python-virtualenv, luarocks,, go, shellcheck.

NOTE:  all I did was select.

I am running Linux Mint  and verified all the listed MIA pkgs were installed, even reinstalled, then tried with remove/installed, plus rebooted, cold booted after each try -- no joy.
The only error I got from any boot was when I tred tp install Neovim.
It is probably pilot error but I don't know why or what might cause the failure.  I am guessing that with all the possible configurations that the solution would be fresh install but that would mean a new ~/ folder as keeping the could be the culprit.  That would not be acceptable for me.  
Also, I am a Neovim user but I backed my configs to a different name and a folder not in the $PATH -- no joy.
If this should bubble up to a resolution or more info, please advise.
If no NONE then I can reivew CT's code and cherry pick out what is needed to make the Neovim environment like his.  Of course that will just be a starting point for my mods (if an)...

PS---
CTL -c, CTL-x does not cancel or close the Toolbox.  Is there a graceful way to exit vs close the TAB/Termnal?

**Comment by nnyyxxxx** [comment]
' Q ' is the current keybind to exit Linutil.

**Comment by nnyyxxxx** [comment]
This should be moved over to Chris's neovim repository
