### ISSUE TITLE
Bin/sh is stupid here is why

### ISSUE THREAD

**Issue by Meliketoaste** [ChrisTitusTech/linutil#29]
/bin/sh is the default shell. And ChrisTitus thought it was faster. It can technically be. But in Titus'es case it was not. 

In Arch bin/sh symlinked to bash. So its not actually faster. 
In Debian its symlinked to Dash which is faster than bash. 
This is why Titus thought bin/sh was faster... its not.

And if somebody tries to make their favourite shell fish. Making bin/sh fish will make it not work very well.

**Comment by Pigges** [comment]
You should never link /bin/sh to fish. That's almost as bad as linking it to python. It should be a posix compliant shell.
It's better to use /bin/sh than just bash since it may be the case that bash is not available.
Using /bin/sh may not always be faster, but it makes it more portable.

**Comment by Meliketoaste** [comment]
Very true but it still happens.
