### ISSUE TITLE
Flatpak & FlatHub setup

### ISSUE THREAD

**Issue by mak448a** [ChrisTitusTech/linutil#290]
**Is your feature request related to a problem? Please describe.**
Some distros don't come with Flatpak or Flathub preinstalled.
<s>Sometimes, distros don't ship with Flathub preconfigured.</s>
<s>I add Flathub to Fedora every time I install it</s>

**Describe the solution you'd like**
Could you add a script to install Flatpak and enable Flathub?
Enable flathub command:
`flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo`

**Describe alternatives you've considered**
Adding flathub normally.

**Comment by harshv5094** [comment]
actually fedora support flatpak packages by default without using the command above

**Comment by mak448a** [comment]
Really? I haven't reinstalled Fedora in a while.

**Comment by harshv5094** [comment]
No, I don't think other distros provide flatpak by default.

**Comment by mak448a** [comment]
Ok, changed to flatpak and flathub setup then.

**Comment by harshv5094** [comment]
I think, we need to make a scripf for it, the problem is user need to test all this in their distro

**Comment by sevu11** [comment]
Yes, it should probably belong in the gaming dependencies script. It needs to take into account of which distro/package manager the user are using. I'm working on a seperate PR for VM dependencies so I could start drafting on one for Flatpak. It's not a bad suggestion.

**Comment by mak448a** [comment]
> I think, we need to make a script for it, the problem is user need to test all this in different distro. VM may be a solution to test it

You can use distrobox for that.
