### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by AdamJedl** [ChrisTitusTech/linutil#31]
Linutil currently lacks a license.
Will it be licensed under MIT like Winutil?

**Comment by luca0N** [comment]
+1 for a LICENSE file. Though seeing as this repository already contains merged pull requests from other users, this must be done with care. Are other contributors okay with their code being distributed as MIT? I think Chris should get permission from these users (or rewrite their contributions) to keep this project from having potential legal issues in the future.

I can say ahead of time that I'm perfectly okay with my minor pull request on this repo being licensed as an FSF-approved license.

**Comment by JustLinuxUser** [comment]
I give all my contributions as CC0, so you can put whatever license you want on it (Creative Commons public no attribution license)

**Comment by ChrisTitusTech** [comment]
I'll just carry over the CC0 license from @JustLinuxUser - I want to make sure it is public and not restrictive as my main requirement.

**Comment by ChrisTitusTech** [comment]
Looked at CC0 and ended up just doing MIT as I liked its terms better.

**Comment by JustLinuxUser** [comment]
I put CC0 to make sure you can change the license to anything, CC0 is basically a non license license, public domain, MIT is a good choice
