### ISSUE TITLE
DWM-titus on Debian fails

### ISSUE THREAD

**Issue by crazycheetah42** [ChrisTitusTech/linutil#312]
## Describe the bug
In the Applications Setup menu, selecting DWM-titus errors out with this:
/tmp/linutil_scripts.CNUBhPinWip7/applications-setup/dwmtitus-setup.sh: 228: Syntax error: "(" unexpected (expecting "fi")

## To Reproduce
1. Run the script using the following command: curl -fsSL christitus.com/linux | sh
2. Go to Applications Setup if not already there
3. Go to DWM-titus and hit enter
4. The error will show.

## Expected behavior
I thought it would install and configure the packages for dwm.

**Comment by nnyyxxxx** [comment]
Will be solved with the merge of #282
