### ISSUE TITLE
cannot run the utility

### ISSUE THREAD

**Issue by HDTS1** [ChrisTitusTech/linutil#314]
## Describe the bug
when run, it returns error `\033[0;31mERROR: Downloading linutil\033[0m`

## To Reproduce
1. Run command `curl -fsSL https://christitus.com/linux | sh` (tried with bash and zsh)
2. returns error `\033[0;31mERROR: Downloading linutil\033[0m`

## Expected behavior
I would expect Linutil popup

## Screenshots
N/A

## Additional context
N/A

**Comment by jeevithakannan2** [comment]
Can you please confirm whether the issue persists?

**Comment by HDTS1** [comment]
it works now, thanks!

**Comment by jeevithakannan2** [comment]
Don't forget to close the issue
