### ISSUE TITLE
[Feature Request] Add package information in Bash Prompt

### ISSUE THREAD

**Issue by bungadrum** [ChrisTitusTech/linutil#315]
**Is your feature request related to a problem? Please describe.**
The Bash Prompt is great it displays all Hardware and Software information on your system, but can you also add the details for all the packages that you have installed as well.

**Describe the solution you'd like**
Similar when you use Neofetch you get details information how many Dpkgs, Packman, Flatpaks or Snaps are insatlled on your system can you also add that when you open your terminal Alacrity, Kitty or any other that information is displayed with your Hardware and Software information as well. I have to type all the time to check it it would be great for it to be always displayed as well. 

**Describe alternatives you've considered**

**Additional context**
It could be added between Software information and Uptime /Age. It could be called "Package Information"

![bash](https://github.com/user-attachments/assets/aeece56e-e907-4961-9c66-a7895212091b)

**Comment by jeevithakannan2** [comment]
This is part of CTT's mybash repo. Please create an issue in https://github.com/ChrisTitusTech/mybash
