### ISSUE TITLE
Is it ok to run linutil in the Linux subsystem for Windows?

### ISSUE THREAD

**Issue by billytwotone** [ChrisTitusTech/linutil#316]
I have watched CTT's recent YouTube video on linutil, and it sounds that is is designed to run on many distribution of Linux. Does that include the Lunux subsstem for Windows?

**Comment by nnyyxxxx** [comment]
Sure, why not.

**Comment by sevu11** [comment]
As long it passes the checks, I don't see why not.

**Comment by rudra-code-creator** [comment]
Yes it should work

**Comment by nnyyxxxx** [comment]
This issue has been answered.
