### ISSUE TITLE
Add "Set Refresh Rate" in Monitor Control

### ISSUE THREAD

**Issue by sevu11** [ChrisTitusTech/linutil#327]
**Is your feature request related to a problem? Please describe.**
It would be neat if we had a selection to set a custom Refresh Rate with `xrandr`, just like we can configure a lot of other things in Linutil for `xrandr`. 

**Describe the solution you'd like**
Similar to the other scripts for monitor options, simply list the top 5 or 10 available refresh rates for current resolution.

**Describe alternatives you've considered**

**Additional context**
I've attempted this on my own, but for some reason I never can manage to get a clear output on available refresh rates in bash. It might be a skill issue though.

**Comment by nnyyxxxx** [comment]
This functionality is already implemented in set_resolutions.sh

**Comment by nnyyxxxx** [comment]
/close not planned

This is already implemented in ``set-resolutions`` , setting only the refresh rate will be tricky with ``xrandr`` as it would only apply to the current resolution. 

I'll re-open this and look into it in the future if I can find a good way to implement this.
