### ISSUE TITLE
Parameterize command invocations

### ISSUE THREAD

**Issue by cartercanedy** [ChrisTitusTech/linutil#329]
### Is your feature request related to a problem? Please describe.
The ability to parameterize some of these scripts would greatly improve the effectiveness of some of the commands. I'm not sure how this is best implemented, but generally being able to provide constrained customization could open up some neat possibilities

### Other issues that might benefit from this:
- #327
- #308 
- #289 

### Describe the solution you'd like
Tbd

**Comment by nnyyxxxx** [comment]
Great idea, I could probably get working on something like this sooner or later.

**Comment by nnyyxxxx** [comment]
Not planned for now, Chris said he wants the interactions between the scripts as minimal as possible.
