### ISSUE TITLE
Multi-Selection suggestion

### ISSUE THREAD

**Issue by jeevithakannan2** [ChrisTitusTech/linutil#334]
Guys I need your suggestion for this. I have been working on multi selection feature https://github.com/ChrisTitusTech/linutil/pull/338

I have added an indicator that pops up near the text when the command is selected.
I can't decide whether i have to make the text bold or not and should I add the symbol for regular mode as shown below please help me out.

> [!NOTE]
> I cannot make the symbol bold. Though it is a nerd font symbol I couldn't make it bold

### Without bold:

![image](https://github.com/user-attachments/assets/7a3c4202-4e45-40c5-82e8-6e7a2409fa3e)

### With bold:

![image](https://github.com/user-attachments/assets/4c684710-551d-4bd6-aec0-d6141c9d3c59)

### Without bold:

![image](https://github.com/user-attachments/assets/2b246f64-1a01-417e-97d7-63f9c8175e14)

### With bold:

![image](https://github.com/user-attachments/assets/e09a57ce-fd1f-48ac-94d1-4c8bca6321de)

> [!IMPORTANT]
> **Please check out the PR and if you have any suggestions related to the PR let me know...!**

**Comment by jeevithakannan2** [comment]
@ChrisTitusTech @lj3954 @afonsofrancof @JustLinuxUser Please consider to take a look and provide your feedback !!

**Comment by nnyyxxxx** [comment]
From a first glance at the pictures I'd say it looks good.
