### ISSUE TITLE
Backspace ARCHTITUS Setup

### ISSUE THREAD

**Issue by MyDrift-user** [ChrisTitusTech/linutil#344]
## Describe the bug
Backspace not working in ARCHTITUS Setup

## To Reproduce
1. Go to 'System Setup'
2. Click on 'Arch Server Setup'
3. write something
4. press backsoace
5. see not removing characters

## Expected behavior
Should remove characters as normal

## Screenshots
![image](https://github.com/user-attachments/assets/b1675eef-0475-4ae6-af89-06b185832ac5)

**Comment by nnyyxxxx** [comment]
@MyDrift-user This Issue should already be solved on the dev branch.

**Comment by MyDrift-user** [comment]
nice, thanks :)
