### ISSUE TITLE
Archtitus btrfs subvolume issue

### ISSUE THREAD

**Issue by Jaredy899** [ChrisTitusTech/linutil#345]
## Describe the bug
when trying to run timeshift, it says @ and @home are not correct. When I run the archinstall, it forms it correctly in btrfs.

**Comment by nnyyxxxx** [comment]
Can you send screenshots? I could not reproduce.

**Comment by Jaredy899** [comment]
Sorry. Should have included this before. This is on a fresh install of arch on a proxmox vm. With BTRFS selected. 


<img width="1292" alt="Screenshot 2024-09-20 at 8 22 51 AM" src="https://github.com/user-attachments/assets/86922705-410b-4b7e-ae5b-bbedead48799">

**Comment by nnyyxxxx** [comment]
> Sorry. Should have included this before. This is on a fresh install of arch on a proxmox vm. With BTRFS selected.
> <img alt="Screenshot 2024-09-20 at 8 22 51 AM" width="1292" src="https://private-user-images.githubusercontent.com/76603258/369402006-86922705-410b-4b7e-ae5b-bbedead48799.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4MzcxMDcsIm5iZiI6MTcyNjgzNjgwNywicGF0aCI6Ii83NjYwMzI1OC8zNjk0MDIwMDYtODY5MjI3MDUtNDEwYi00YjdlLWFlNWItYmJlZGVhZDQ4Nzk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDEyNTMyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwNzY2MDU1YWFhZTE3NGYxMGMwNTViNTMxMmEyNmVhZmZmOGUwYTg2NTI5YmM5ZDAzZDAxMWQyZDVhMTk5YmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.PtzF3NeXw5nv4NKa-FqGJWzAWcKeytuA7nDnC3ADQno">

thanks i caught the error, fixing it now

**Comment by adamperkowski** [comment]
#560

**Comment by jeevithakannan2** [comment]
@Jaredy899 Is the issue resolved?

**Comment by Jaredy899** [comment]
@jeevithakannan2 To my knowledge no. I think @nnyyxxxx was working on it. I made a similar script that uses Chris' with the help of Cursor that fixed it if someone wants to look at it to see why that one works but Chris' doesn't. I'm not knowledgable enough to figure it out...

**Comment by jeevithakannan2** [comment]
@Jaredy899 sorry for the late reply can you create a gist or something I will take a look !!

**Comment by Jaredy899** [comment]
https://gist.github.com/Jaredy899/118fa2ca60ba412debb7dece07d114c2

**Comment by hikkidev** [comment]
Why not refind...? It is much simpler...

**Comment by jeevithakannan2** [comment]
Found the issue working on fix. Timeshift has issues with LABELS https://github.com/linuxmint/timeshift/issues/142
