### ISSUE TITLE
Add alias for linutil in bashrc

### ISSUE THREAD

**Issue by pupeesh** [ChrisTitusTech/linutil#349]
Can someone add a simple alias to .bashrc

alias linutil="curl -fsSL https://christitus.com/linux | sh"

**Comment by adamperkowski** [comment]
There should be a script that checks if a `linutil` package exists on the system (that's gonna conflict), checks for user's login shell / installed shells (like bash, zsh or fish) and creates aliases respectively.

**Comment by pupeesh** [comment]
yeah that would be lovely, thank you

**Comment by adamperkowski** [comment]
@pupeesh We've decided not to do this and package linutil instead. It's already up on AUR and it's going to be on crates.io soon too.
See #333
