### ISSUE TITLE
linutil doesn't handle old version of Alacrity

### ISSUE THREAD

**Issue by radek-chramosil** [ChrisTitusTech/linutil#364]
## Describe the bug
I run this OS:
`Linux pop-os 6.9.3-76060903-generic`

Pop OS only has Alacrity 0.12.2 available, which doesn't support Toml files (supported from v1.0.0 - I think).

```
$ alacritty --version
alacritty 0.12.2
```

Hence, these lines of code are useless for my OS setup.

 https://github.com/ChrisTitusTech/linutil/blob/9dba90986e43d6ec528cdd604cf0e0f31ba44b99/tabs/applications-setup/alacritty-setup.sh#L23-L25

## To Reproduce
1. Install a current version of Pop OS (some VM/container is enough)
2. Check the version of Alacrity

## Expected behavior
I was expecting that the bash script would apply your default settings, however, I didn't remember I run on old Alacrity.

## Screenshots
N/A

## Additional context
N/A

**Comment by adamperkowski** [comment]
> Pop OS only has Alacrity 0.12.2 available, which doesn't support Toml files (supported from v1.0.0 - I think).

It's [v0.13.0](https://alacritty.org/changelog_0_13_0.html#Changed). I'll open a PR.

**Comment by RazoBeckett** [comment]
I have created two PRs: one on Dwm-titus [#66](https://github.com/ChrisTitusTech/dwm-titus/pull/66) and another, #369, on this repository, which closes this issue. Instead of not supporting older versions, these changes allow users with newer versions of Alacritty to migrate from the old YAML format to TOML. The PRs have been created to fulfill that purpose.

**Comment by adamperkowski** [comment]
@RazoBeckett You shouldn't just yoink the code from my PR and create yours. Doesn't work that way. 
Besides, the script would need an update if [#66](https://github.com/ChrisTitusTech/dwm-titus/pull/66) is merged.

**Comment by RazoBeckett** [comment]
yes script also has update check #369

**Comment by RazoBeckett** [comment]
And hell nah you just copied my shit and calling its yours, thank god its all git controlled i can show the timings of my commits you even copied my comment of 'using 'command' to avoid alias'

**Comment by adamperkowski** [comment]
> i didn't looked into PRs for that issue i don't care if ChrisTitusTech Rejects my PRs because i am here to just help him maintain the projects not for Getting my PRs merged.

You should probably check for duplicates before submitting anything. You can suggest changes to PRs on GitHub.

**Comment by RazoBeckett** [comment]
> > i didn't looked into PRs for that issue i don't care if ChrisTitusTech Rejects my PRs because i am here to just help him maintain the projects not for Getting my PRs merged.
> 
> You should probably check for duplicates before submitting anything. You can suggest changes to PRs on GitHub.

as i said i don't care if he closes my PRs.

**Comment by adamperkowski** [comment]
> And hell nah you just copied my shit and calling its yours, thank god its all git controlled i can show the timings of my commits you even copied my comment of 'using 'command' to avoid alias'

I literally added you as a co-author. cdb6f3dcc8f999061e7853b36684b0900308bf27, https://github.com/ChrisTitusTech/linutil/pull/369#issuecomment-2349693129

**Comment by RazoBeckett** [comment]
😢 okay you know what sorry for being shitty as i said i don't care about he closing my PRs i will close the #369 one by myself .. @adamperkowski

**Comment by nnyyxxxx** [comment]
Adding support for older versions of applications will be a hassle, Chris said that he does not want to, and I also do not want to due to how tricky it will be to implement.

/close
