### ISSUE TITLE
GLIBC Version Error When Running Script on Windows WSL 2.1.5.0

### ISSUE THREAD

**Issue by tonytech83** [ChrisTitusTech/linutil#37]
## Environment
- **Operating System**: Windows Subsystem for Linux (WSL) 2.1.5.0
- **Distribution**: Debian

## Issue Description
I am experiencing a version mismatch error related to GLIBC when attempting to run a script on Windows WSL. Below are the error messages that are displayed when I try to execute the script:
```sh
/tmp/tmp.w9U597xQHU: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/tmp.w9U597xQHU) 
/tmp/tmp.w9U597xQHU: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /tmp/tmp.w9U597xQHU)
/tmp/tmp.w9U597xQHU: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/tmp.w9U597xQHU)
ERROR: Executing linutil
```

**Comment by afonsofrancof** [comment]
This is normal as the tool dynamically links to GLIBC.
To fix this we would have to compile linutil on a system with that GLIBC version (most likely WSL itself) and then add that to the releases.
The tool then would download the correct version depending if it was in WSL or not.
Maybe something can be done using github actions, but I have no idea.
We need chris' input on this.

**Comment by lj3954** [comment]
> This is normal as the tool dynamically links to GLIBC. To fix this we would have to compile linutil on a system with that GLIBC version (most likely WSL itself) and then add that to the releases. The tool then would download the correct version depending if it was in WSL or not. Maybe something can be done using github actions, but I have no idea. We need chris' input on this.

No need for that. You can statically link a rust binary with the musl libc, which gives it essentially universal compatibility with linux systems. In fact, that should definitely be the case here, to ensure compatibility with distros that don't ship with the GNU C Library.

**Comment by afonsofrancof** [comment]
Well yes, but some libraries don't work well with musl.
I didn't try to switch to it tho, so I will give it a try and if it works I will submit a PR

**Comment by lj3954** [comment]
> but some libraries don't work well with musl.

Linutil is not a library. Running a binary which is statically linked with musl does not remove glibc from the system, therefore there's no compatibility issues with other libraries. Linutil is a TUI which launches shell scripts, it doesn't include a copy of any library. I'm preparing a PR.

**Comment by afonsofrancof** [comment]
@lj3954 Wait. There is a simple method to statically link glibc, instead of musl.
I said some libraries don't work with it because linutil obviously uses external libraries, and sometimes those are the ones incompatible with musl.

**Comment by lj3954** [comment]
glibc definitely is not intended to be statically linked. Once again, the only thing being built and linked against anything is the TUI which launches scripts. The scripts are launched through the system's shell, whatever /bin/sh is symlinked to. That shell is almost certainly linked to whatever the system's C library is, which also doesn't matter. The external programs those shell scripts call, which are not libraries, also are built by the distro. 

I don't believe linutil is shipping a binary of curl, wget, git, every package manager, and everything else called by the shell scripts. If it is, I think there are far more important things to be concerned about than what a TUI is linked to.

**Comment by afonsofrancof** [comment]
Yup, you seem to be correct. Although you can link against glibc, linking against musl is generally more recommended.
