### ISSUE TITLE
Both yay installations and paru installations fail but say success

### ISSUE THREAD

**Issue by bl4xe** [ChrisTitusTech/linutil#377]
## Describe the bug
I was trying to reinstall yay as I received an unrelated error reading something like it couldn't load libalpm.so.14. So I wanted to just reinstall them with this script and I ran into an error reading error: 
failed to run custom build command for `alpm v3.0.4 (https://github.com/archlinux/alpm.rs?rev=306342#306342ef)`

Caused by:
  process didn't exit successfully: `/opt/paru/src/paru-2.0.3/target/release/build/alpm-fe8130be9696cf00/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at /home/bl4ze/.cargo/git/checkouts/alpm.rs-a0070a235cf20bfa/306342e/alpm/build.rs:25:13:
  this version of alpm.rs does not support libalpm v15.0.0 only v14.x.x is supported 
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
==> ERROR: A failure occurred in build().
    Aborting...
Paru installed

## Expected behavior
just install normally

## Screenshots
![image](https://github.com/user-attachments/assets/6f43a567-5256-49f2-a0bc-adadc6a7eb15)

![image](https://github.com/user-attachments/assets/c427b3b9-bc88-45d4-955c-955006c6fe45)

## Additional context
I'm currently converting a shit ton of files with ffmpeg, maybe that caused the error

**Comment by nnyyxxxx** [comment]
Could not reproduce.

**Comment by adamperkowski** [comment]
#374 could fix this with paru

**Comment by Linuxury** [comment]
I can confirm the same issue as @bl4xe on a new arch installation.

**Comment by nnyyxxxx** [comment]
Paru is not updated to the current pacman version right now, I just tested on my system and could only reproduce the libalpm issue. Yay works like a charm.
