### ISSUE TITLE
Error when running linutil for DWM-Titus | dwmtitus-setup.sh: 228:

### ISSUE THREAD

**Issue by firespydr** [ChrisTitusTech/linutil#383]
## Describe the bug

Error when running linutil for DWM-Titus

```
/tmp/linutil_scripts/applications-setup/dwmtitus-setup.sh: 228:
Syntax error: "(" unexpected (expecting "fi")

```

## To Reproduce
1. Use either stable or dev branch of linutil 
2. Applications Setup > DWM-Titus

## Expected behavior
Installing DWM-Titus

## Screenshots
![System](https://github.com/user-attachments/assets/a39f2521-463c-4f72-ab01-b47dde926f86)
![Error](https://github.com/user-attachments/assets/0d3e0e9c-6795-4b62-ba66-27120f2012bc)

## Additional context
Fresh install of Debian 12 Mate Live, all packages were updated prior to trying.

**Comment by jeevithakannan2** [comment]
It should be fixed with PR https://github.com/ChrisTitusTech/linutil/pull/282

**Comment by zakgdg** [comment]
This is an issue specific to debian

**Comment by zakgdg** [comment]
because it worked fine for me fine with nobara

**Comment by jeevithakannan2** [comment]
Does the issue still persist?

**Comment by zakgdg** [comment]
> Does the issue still persist?

I think so

**Comment by jeevithakannan2** [comment]
It should be fixed in the dev branch but dev branch introduced a new bug https://github.com/ChrisTitusTech/linutil/issues/420. The issue will be fixed with https://github.com/ChrisTitusTech/linutil/pull/421

**Comment by jeevithakannan2** [comment]
It should be fixed in the dev branch. You can try it with 

`curl -fsSL christitus.com/linuxdev | sh`

**Comment by firespydr** [comment]
I will try this out tonight. I have a test vm running Linux Mint Cinnamon
that needs to be setup.

Thank you,
Chris

**Comment by firespydr** [comment]
This is what I get now.
[image: image.png]

Thank you,
Chris
