### ISSUE TITLE
terminal interaction 

### ISSUE THREAD

**Issue by DevHolako** [ChrisTitusTech/linutil#4]
I don't know if it's only me, but I can't interact with the inside terminal to type my user password. It's just stuck there. I tried moving the window and switching it to another workspace, but it's still not working.

![image](https://github.com/ChrisTitusTech/linutil/assets/70993209/0eb90131-685e-46c4-a2dc-45737b4e2a07)

**Comment by karthick-kk** [comment]
Same here. Can't input any key in the nested window
![image](https://github.com/ChrisTitusTech/linutil/assets/1493364/a9b2dd3e-c3c3-447b-beca-4ad21b727603)

**Comment by TheGamingWinner** [comment]
<details><summary>Details</summary>
<p>

The Problem has been registered and is been worked on so please be paitent future updates will fix this issue

</p>
</details>

**Comment by ChrisTitusTech** [comment]
Fixed thanks to @JustLinuxUser
