### ISSUE TITLE
Feature request Do checkEnv in start.sh

### ISSUE THREAD

**Issue by Subarctic2796** [ChrisTitusTech/linutil#40]
I think that you should do `checkEnv` in the `start.sh` that way you don't have to check the environment in every script that linutil runs. This also means that we can get the package manager before.

The only thing is that you will have to pass the package manager to the rust binary we it gets invoced from `start.sh`. I tried to add reading the package manager from the cli but I couldn't figure out how to do it.

**Comment by afonsofrancof** [comment]
Chris chose a different approach and that now gets checked on the common-script.
/close
