### ISSUE TITLE
Add a seperate option for fastfetch and it's customization

### ISSUE THREAD

**Issue by zakgdg** [ChrisTitusTech/linutil#400]
Instead of integrating it into bash setup instead make it in it's seperate menu and add an option to add it to either zsh or bash (aka when launching terminal)

**Comment by nnyyxxxx** [comment]
Solved with #335

**Comment by nnyyxxxx** [comment]
I'm going to implement this.

**Comment by nnyyxxxx** [comment]
Solved with #404 && #335
