### ISSUE TITLE
Ability to change color scheme for the bash prompt

### ISSUE THREAD

**Issue by pupeesh** [ChrisTitusTech/linutil#418]
When installing the bash prompt from the linux utility can there be a user interaction with options for different color schemes for basic colors like: red, blue, green, purple ... etc.

Oh and i forgot about kitty/alacritty also

**Comment by nnyyxxxx** [comment]
Only the installation scripts are included in Linutil at the moment, you would have to request this in the mybash repository on ChrisTitusTech's profile if you want to see this implemented. Those projects will be moved over to this repository in the future though.
