### ISSUE TITLE
userkeys not persistent on Archtitus install

### ISSUE THREAD

**Issue by Glen-Sumner** [ChrisTitusTech/linutil#429]
On install of Archtitus uk userkeys selected but on reboot back to US

## To Reproduce
Steps to reproduce the behavior: I have tried several times with VM's each time same behaviour ( I have reported this before )

## Expected behavior
A clear and concise description of what you expected to happen. I would like UK keys! lol

## Additional context
maybe some conflict between #517 and #520 where keymaps are set to US then $user for whatever reason Keymaps are left at US not changed to user also maybe put --no-convert in there to to prevent wandering keymaps.

**Comment by nnyyxxxx** [comment]
> On install of Archtitus uk userkeys selected but on reboot back to US
> ## To Reproduce
> 
> Steps to reproduce the behavior: I have tried several times with VM's each time same behaviour ( I have reported this before )
> 
>     1. Go to '...'
> 
>     2. Click on '....'
> 
>     3. Scroll down to '....'
> 
>     4. See error
> 
> 
> ## Expected behavior
> 
> A clear and concise description of what you expected to happen. I would like UK keys! lol
> ## Screenshots
> 
> If applicable, add screenshots to help explain your problem.
> ## Additional context
> 
> maybe some conflict between #517 and #520 where keymaps are set to US then $user for whatever reason Keymaps are left at US not changed to user also maybe put --no-convert in there to to prevent wandering keymaps.

I could reproduce this issue, going to fix it now.

**Comment by Glen-Sumner** [comment]
cheers
