### ISSUE TITLE
Fedora fresh install

### ISSUE THREAD

**Issue by Linuxury** [ChrisTitusTech/linutil#431]
## Describe the bug
I believe it is missing the git command here.

## To Reproduce
1. Go to 'curl -fsSL https://christitus.com/linuxdev | sh'
2. Click on 'any of the application setup'
3. See error

## Expected behavior
It's not able to pull the git to initiate the installation, if for example you go into my bash directly and run that one first they all will work.

## Screenshots
![Screenshot_20240916_175324](https://github.com/user-attachments/assets/c7262c75-ed2c-410a-81df-10ea8ab56ecf)

## Additional context
Also, it's not able to download the fonts either, tested on Arch and it was able to complete but not in Fedora.

**Comment by nnyyxxxx** [comment]
Git is not being installed inside of the scripts, that can be changed in the future; for now you will have to install git manually before running the script. #335 includes some fixes for mybash and nvim, but they do not fix this issue.
