### ISSUE TITLE
Feature request: migrate from sudo to doas.

### ISSUE THREAD

**Issue by Kingproone** [ChrisTitusTech/linutil#44]
smaller footprint, possibly more secure
down the line maybe to run0

**Comment by AlbydST** [comment]
I added support for doas and even regular su in #41. I also did the same thing for the mybash project in commit [e9382f6b861824ec0ed1d233113ebdd90ea17b9e](https://github.com/ChrisTitusTech/mybash/commit/e9382f6b861824ec0ed1d233113ebdd90ea17b9e).

**Comment by Kingproone** [comment]
I meant it, to have a script that migrates the users system from one to the other.

**Comment by jeevithakannan2** [comment]
Please close this issue as it has been resolved in https://github.com/ChrisTitusTech/linutil/pull/193

**Comment by Kingproone** [comment]
#193 supports doas, not migrates from sudo to it.

**Comment by jeevithakannan2** [comment]
It checks for sudo and if not available it uses doas

**Comment by adamperkowski** [comment]
This issue should be closed. Already implemented.

**Comment by adamperkowski** [comment]
There you go

**Comment by nnyyxxxx** [comment]
Already implemented, we now support both sudo and doas.
