### ISSUE TITLE
Does not work for aarch64 ARM right now

### ISSUE THREAD

**Issue by Furyfree** [ChrisTitusTech/linutil#444]
## Describe the bug
When i try to run the curl command on a Debian 12 ARM i get the error: \033[0;31mERROR: Downloading linutil\033[0m
This happens because the URL that the start.sh script tries to reach does not exist

## To Reproduce
1. Go on a ARM based linux machine (I tried Debian 12)
2. Run the curl command "curl -fsSL https://christitus.com/linux | sh"

## Expected behavior
Should run the linutil

## What actually happens
You will get an error because the URL "https://github.com/ChrisTitusTech/linutil/releases/latest/download/linutil-aarch64" gives an 404 error page

## Screenshots
![CleanShot 2024-09-17 at 14 13 18@2x](https://github.com/user-attachments/assets/3da8f5e3-6695-4dfa-b98e-21afe66c8471)

**Comment by adamperkowski** [comment]
This is not a bug. Linutil dropped ARM support a while ago. You can try and build it for yourself if you want to.

**Comment by adamperkowski** [comment]
> it's just still in the start.sh code

Yes it is... for some reason. I'll open a PR

**Comment by adamperkowski** [comment]
> I will close this as it does not support ARM and does not intend to support ARM

I think you can reopen this. We think about adding ARM64 support back. https://github.com/ChrisTitusTech/linutil/pull/445#pullrequestreview-2309761724

**Comment by adamperkowski** [comment]
> Don't think I have permission to reopen this case. Can anybody reopen it or do I need to make a new issue?

Make a new one then.
