### ISSUE TITLE
Does not work for aarch64 ARM

### ISSUE THREAD

**Issue by Furyfree** [ChrisTitusTech/linutil#450]
## To Reproduce
1. Go on a ARM based linux machine (I tried Debian 12)
2. Run the curl command "curl -fsSL https://christitus.com/linux | sh"

## Expected behavior
Should run the linutil

## What actually happens
You will get an error because the URL "https://github.com/ChrisTitusTech/linutil/releases/latest/download/linutil-aarch64" gives an 404 error page

## Screenshots
![CleanShot 2024-09-17 at 14 13 18@2x](https://github.com/user-attachments/assets/c05557bf-3b52-44b8-8e99-f1bbf6ca0e87)

## Additional context
I will reference #444 because i got told to close it and then open it again but i don't have permission to open it again

**Comment by adamperkowski** [comment]
@Furyfree ARM support got merged. Check now.
