### ISSUE TITLE
DWM-Titus not installing in Debian....

### ISSUE THREAD

**Issue by sarathdm** [ChrisTitusTech/linutil#457]
DWM-Titus not installing in Debian Virtual Image....
it is showing error...........
![brave_xCouvmYuVM](https://github.com/user-attachments/assets/64859401-c8b9-4386-b9c1-bf2d99ab4a7f)

**Comment by nnyyxxxx** [comment]
> DWM-Titus not installing in Debian Virtual Image.... it is showing error........... ![brave_xCouvmYuVM](https://private-user-images.githubusercontent.com/117918597/368462900-64859401-c8b9-4386-b9c1-bf2d99ab4a7f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NDQ3MTEsIm5iZiI6MTcyNjY0NDQxMSwicGF0aCI6Ii8xMTc5MTg1OTcvMzY4NDYyOTAwLTY0ODU5NDAxLWM4YjktNDM4Ni1iOWMxLWJmMmQ5OWFiNGE3Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOFQwNzI2NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01Mjc2ZWQ0YjM1Yzg1ZTdhNzI3OGE5Y2ExMDJmZGE0NTU0OGYxMTYxMDEzZjk4YzEwYTcyZmEzZDM4NzE0ZmI0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5mhZQ5z66wU79p41wvJd6XYts04alegRFXPMGmo4hXs)

This bug has already been solved in #282 Please use the dev branch instead of the regular branch if you want the fixes applied.
