### ISSUE TITLE
Feature suggestion and pull request idea: Docker FreshRSS setup and k8s default cluster setup

### ISSUE THREAD

**Issue by CarlosR759** [ChrisTitusTech/linutil#46]
Hi @ChrisTitusTech : 

Since you show me FreshRSS to replace my newsboat and increase my productivity a lot, I really want to know if you would like a PR with that feature. I could try to make it in the coming weeks because I'm a little busy right now but I really want to help you with this proyect when I can. Also since I have a devops background: It's fine now or for this project to put a  default kubernetes installation using kubeadm like this https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/ ? 
Please let me know if putting this kind of stuff and devops tools in general  is fine for your project or not.

Nevertheless thanks for your knowledge in the past years !
Have a nice week
Cheers

**Comment by Jak2k** [comment]
On July 17, 2024 12:32:52 AM GMT+02:00, CarlosR759 ***@***.***> wrote:
>Hi Chris: 
>
>Since you show me FreshRSS to replace my newsboat and increase my productivity a lot, I really want to know if you would like a PR with that feature. I could try to make it in the coming weeks because I'm a little busy right now but I really want to help you with this proyect when I can. Also since I have a devops background: It's fine now or for this project to put a  default kubernetes installation using kubeadm like this https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/ ? 
>Please let me know if putting this kind of stuff and devops tools in general  is fine for your project or not.
>
>Nevertheless thanks for your knowledge in the past years !
>Have a nice week
>Cheers
>

I think kubernetes is is an overkill, but a docker install script including adding the user to the correct group would be nice.

**Comment by CarlosR759** [comment]
> On July 17, 2024 12:32:52 AM GMT+02:00, CarlosR759 ***@***.***> wrote: Hi Chris: Since you show me FreshRSS to replace my newsboat and increase my productivity a lot, I really want to know if you would like a PR with that feature. I could try to make it in the coming weeks because I'm a little busy right now but I really want to help you with this proyect when I can. Also since I have a devops background: It's fine now or for this project to put a default kubernetes installation using kubeadm like this https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/ ? Please let me know if putting this kind of stuff and devops tools in general is fine for your project or not. Nevertheless thanks for your knowledge in the past years ! Have a nice week Cheers
> I think kubernetes is is an overkill, but a docker install script including adding the user to the correct group would be nice.

I agree, installing freshRSS in a simple way, and be able to import a previous data base easily will save me a lot of time each time I need to install it. I could do it with the quick run option and without using the docker-compose approach so less yaml files for the script :D 

About the k8s stuff, Since also cloud providers have quick setups configurations I know that could be overkill as you said, that's why I'm asking first. I'm suggesting this because Installing locally an only functional k8s cluster + Prometheus + grafana will take you some time if you want to do that, but probably this requirement will be use only by a niche group of people that want to learn this tools in a home environment. But if it's not needed I could work with the docker stuff and helping with scripting in general. But I'll wait for Chris response so I could know how to work the FreshRSS installation ( And also I need to learn how to use the new Rust gui ) and where to put this in the program, because maybe if we are going to put a lot of docker containers in the feature it could be usefull to have some special folder for that :upside_down_face: .

**Comment by nnyyxxxx** [comment]
/close

Docker has been added into Linutil #317
