### ISSUE TITLE
Add an option for debian users to upgrade from debian stable to debian sid

### ISSUE THREAD

**Issue by TuxManxD** [ChrisTitusTech/linutil#460]
self explanatory

**Comment by TuxManxD** [comment]
I wish I can write rust because I really wanted to contribute but I guess I'm limited by suggestions :/

**Comment by nnyyxxxx** [comment]
@TuxManxD Knowing rust is not required to contribute, rust is only the back-end of the project that manages the TUI's behavior and somewhat influences the scripts behavior. If you want to contribute you'll have to learn shell scripting (if you know shell scripting already then this wont be an issue) then you will have to review our contributing guidelines, make a foundation for the new addition you want to add and then make a PR for that (Only after working out all bugs in your foundation) Have fun contributing!

**Comment by TuxManxD** [comment]
> > I wish I can write rust because I really wanted to contribute but I guess I'm limited by suggestions :/
> 
> @TuxManxD Knowing rust is not required to contribute, rust is only the back-end of the project that manages the TUI's behavior and somewhat influences the scripts behavior. If you want to contribute you'll have to learn shell scripting (if you know shell scripting already then this wont be an issue) then you will have to review our contributing guidelines, make a foundation for the new addition you want to add and then make a PR for that (Only after working out all bugs in your foundation) Have fun contributing!

I kinda know shell scripting like a basic knowledge

**Comment by adamperkowski** [comment]
> I kinda know shell scripting like a basic knowledge

Then go ahead and open a PR if your shell scripting knowledge is sufficient to do this :)

**Comment by TuxManxD** [comment]
imma start workin on this one new to committing to projects on github but I can get this workin

**Comment by nnyyxxxx** [comment]
/close not planned

this could brick peoples systems, its best this should be done manually and not in a script
