### ISSUE TITLE
Brew

### ISSUE THREAD

**Issue by kittenvr** [ChrisTitusTech/linutil#47]
Can you make it support brew.sh?

**Comment by Jak2k** [comment]
Brew isn't really a good package manager for Linux. Always prefer your distro's one ornthird party repos, if possible.

**Comment by kittenvr** [comment]
Yeah my distro reccomends brew

**Comment by RazoBeckett** [comment]
@kittenvr what distro you use ?

**Comment by kittenvr** [comment]
bazzite

**Comment by Jak2k** [comment]
Isn't the recommendation order Flatkpak, Distrobox, ostree?

**Comment by iax7** [comment]
I work at a macOS-first company. Having Homebrew on Fedora allows me to use the same scripts to initialize my distro. It might not be the best, but it works flawlessly.

Another thing is that DNF's versions tend to be outdated, while Homebrew almost always has the latest ones.

**Comment by nnyyxxxx** [comment]
/close not planned

Linutil currently supports all necessary package managers, adding support for ``brew`` could happen in the future but is **highly unnecessary** as it's a **third party** package manager.
