### ISSUE TITLE
Shebangs are completely ignored

### ISSUE THREAD

**Issue by lj3954** [ChrisTitusTech/linutil#489]
## Describe the bug
All scripts launched from linutil are run directly with `sh -e`, completely disregarding the shebang on each script. This should be fixed to allow for future scripts which may require to be launched with a different shell or other executable program. We must not go too far with this approach, especially when implementing reversion which may involve a major restructure. Relevant to the topic: @adamperkowski, @nnyyxxxx.

## Checklist
- [x] I checked for duplicate issues.
- [x] I checked already existing discussions.
- [x] This issue is not included in the roadmap.

**Comment by nnyyxxxx** [comment]
Interesting

**Comment by nnyyxxxx** [comment]
We could try and make the shebangs more dynamic for every script via making a function in common-script depending on the distribution. Only in theory though I would have to test further.
