### ISSUE TITLE
Steam Installation Fails During Gaming Dependencies Install on Debian 12

### ISSUE THREAD

**Issue by DragonChrist** [ChrisTitusTech/linutil#49]
Description:
On Debian 12 Mate (using main, non-free, contrib, non-free-firmware), Steam fails during the installation of gaming dependencies. The package candidate is steam-installer, which lacks i386 libraries.

Workaround:
The issue is resolved by adding the i386 architecture:
`sudo dpkg --add-architecture i386`

Suggestion:
Consider modifying linutil to add `contrib` and `non-free` to `/etc/apt/sources.list` on Debian. Concerns aside about modifying pure-libre Debian installs, you have to do this anyway if you're installing Steam.

**Comment by afonsofrancof** [comment]
Fixed by #72
