### ISSUE TITLE
Build Essentials Fails During Git on Debian 12

### ISSUE THREAD

**Issue by DragonChrist** [ChrisTitusTech/linutil#50]
Description:
Build essentials fails during the cloning process, prompting for username/password (which in my experience usually means I typed the repo in wrong; but I'm far from an expert). It appears to be requesting a `linux-setup` repository, but shouldn't it be looking for the repository named `linutil`?

Sorry--not trying to spam the issues, but I thought I'd take Chris' advice on contribution so I took notes on what didn't work with linutils on a fresh Debian 12 Bullseye install.

**Comment by afonsofrancof** [comment]
This can now be closed.
