### ISSUE TITLE
Bashisms exist in d2r lootfilters

### ISSUE THREAD

**Issue by ghost** [ChrisTitusTech/linutil#506]
![image](https://github.com/user-attachments/assets/e81e2185-dc49-4cbf-b9f8-bae65b9ae0e4)

If anyone plays Diablo II and knows basic shell scripting can you help out with this?

I unfortunately cannot remove these and test without owning / playing the game.

**Comment by adamperkowski** [comment]
@nnyyxxxx I think you can link a branch to an issue
here
![image](https://github.com/user-attachments/assets/88517aef-dd62-44c2-ae82-46c0edc51ab7)

**Comment by ChrisTitusTech** [comment]
Fixed in PR #531
