### ISSUE TITLE
[Feature suggestion]: A full system upgrade script for Debian

### ISSUE THREAD

**Issue by bungadrum** [ChrisTitusTech/linutil#51]
Next year Debian 13 Trixie will roll out would it be possible to add a script that will do a full system upgrade from Debian 12 Bookworm to the latest one. Since Debian does not have any kinda GUI tool for a easy upgrade you have to manually do everything in the CLI. Having this script would make it easier for users to just run it, reboot the system when it's finished and they will be on the latest version. This will only be used once every few years when a new version rolls out, but it would make upgrading easier then using the terminal.

This would run in the background:

```
sudo apt update && sudo apt upgrade -y
sudo apt --purge autoremove
        
sudo cat /etc/apt/sources.list
sudo sed -i 's/bookworm/trixie/g' /etc/apt/sources list
        
sudo apt update
sudo apt upgrade --without-new-pkgs -y
        
sudo apt full-upgrade -y
        
sudo reboot

sudo apt --purge autoremove -y
```

![debian3](https://github.com/user-attachments/assets/5c352364-9f75-4bdc-9882-cc53b55dce10)

Not sure if theese are all the commands for doing a full system upgrade. Any additional stuff could be added like non free firmware:

```
sudo sed -i '/deb http:\/\/deb.debian.org\/debian\/ trixie main/ s/$/ contrib non-free-firmware/' /etc/apt/sources.list
sudo sed -i '/deb-src http:\/\/deb.debian.org\/debian\/ trixie main/ s/$/ contrib non-free-firmware/' /etc/apt/sources.list
```

**Comment by lj3954** [comment]
This could be useful for far more than just debian. Ubuntu and Fedora have similar processes which could be automated.

**Comment by bungadrum** [comment]
The advantage that Ubuntu has is that it redirects you with a GUI and does everything for you. while on Debian or anything that's based on it you have to do everything yourself. Thats the only reason I still hesitate to switch to it would be nice if there is a easy upgradable method for it I would ditch Ubuntu and never look back.

**Comment by nnyyxxxx** [comment]
This has been implemented already.
