### ISSUE TITLE
script does not check if git is installed

### ISSUE THREAD

**Issue by smogan** [ChrisTitusTech/linutil#52]
tried the script for the first time (dietpi  **X86_64** , based on debian 12). wanted to have the fancy command line. got the error message that git is not a known command. after  I installed git manually, the script ran. 

guess the script should (like the winutil script) check for the presence of needed tools and install them if needed.

**Comment by Nicky-M** [comment]
Hi,

I got the same "git error" on a brand new install of Ubuntu 24.04.

The nerd fonts are not installed either :-). I really enjoyed your video on bash.

Good job and thanks a lot.

**Comment by smogan** [comment]
same problem on OpenSUSE tumbleweed

**Comment by afonsofrancof** [comment]
This is because git is used to clone the yay repo, to install it.
Please also open an issue in https://github.com/ChrisTitusTech/mybash, explaining this.
