### ISSUE TITLE
Rust code is really unreadable for beginners who want to add new functionality.

### ISSUE THREAD

**Issue by guruswarupa** [ChrisTitusTech/linutil#564]
## Is your feature request related to a problem? Please describe.
I was trying to add a new feature into rust but then the code seems very poor in commenting what it does except few lines.

## Describe the solution you'd like
Proper documenting and Commenting required to promote more growth in the Script.

## Additional context
![image](https://github.com/user-attachments/assets/47f9a4c7-c178-47b5-8469-f1b4f39b7b37)

**Comment by nnyyxxxx** [comment]
@lj3954 @adamperkowski I think you two could best implement detailed comments in the rust codebase.

**Comment by adamperkowski** [comment]
There's 1843 total lines written in Rust in Linutil as of 006326afa9a6f98f00d1672280e38ceecb139847. 1605 in `tui` and 238 in `core`. A lot to comment.

**Comment by cartercanedy** [comment]
> There's 1843 total lines written in Rust in Linutil as of 006326afa9a6f98f00d1672280e38ceecb139847. 1605 in `tui` and 238 in `core`. A lot to comment.

Not to mention that those lines are extremely volatile. It's understandable that someone would want an easy experience with contributing, but there are times when the only way to really understand the code is to actually read the code. 

Comments get old, people get lazy, and all of a sudden the once helpful comments are just bloat.

Just as a comment from my own experience, this codebase is actually pretty good. There's a lot of meaningful semantic variable naming, there's not a whole lot of macros, and the code itself follows a pretty linear path. I've actually had a very pleasant experience contributing to this project for these reasons.

**Comment by cartercanedy** [comment]
Also, that's not too say that the internal interfaces shouldn't be documented, but I'm not sure that's what your point is, @guruswarupa

**Comment by afonsofrancof** [comment]
This is actually one of the few open source codebases where I don't get lost.
You can easily follow the flow and get to wherever you want to.

I do understand about newcomers tho, and maybe the more stable parts of the tool could be better documented. I can work on that if we agree that it should be worked on.

**Comment by nnyyxxxx** [comment]
/close not planned

Adding comments will clutter the codebase and updating those comments will be a hassle, especially with the rate Linutil has been going, things change, things change fast and we can't constantly be managing and updating comments in the src.
