### ISSUE TITLE
Setup bash prompt aliases lack requisite packages (Debian 12)

### ISSUE THREAD

**Issue by DragonChrist** [ChrisTitusTech/linutil#57]
Many aliases that replace OoB functionality in Bash have requisite packages that should be installed while setting up the ~/.bashrc. Off the _bat_, it does need `bat`, `fzf` for Zoxide, `trash-cli` and neovim installed. Might also suggest omitting aliases for other editors like nano which is perfect for simple conf files I wouldn't otherwise use nvim for.

**Comment by afonsofrancof** [comment]
I can work on this. 
Will make a PR soon

**Comment by afonsofrancof** [comment]
This issue should be opened on [ChrisTitusTech/mybash](https://github.com/ChrisTitusTech/mybash).
As far as I can tell, setup.sh already installs almost everything you need, with the only thing missing being trash-cli.
