### ISSUE TITLE
Fastfetch fails to install 

### ISSUE THREAD

**Issue by Glen-Sumner** [ChrisTitusTech/linutil#570]
## Describe the bug
Fastfetch fails to install linutil says success but doesn't install (this is in Debian 12)
![fastfetchfail](https://github.com/user-attachments/assets/e2f500d3-1acc-4352-a44c-7a559b4469e2)

## Checklist
- [ ] I checked for duplicate issues.
- [ ] I checked already existing discussions.
- [ ] This issue is not included in the roadmap.
- [ ] This issue is present on both stable and development branches.

**Comment by nnyyxxxx** [comment]
fastfetch is not an official package for Debian 12.
