### ISSUE TITLE
Neovim Setup

### ISSUE THREAD

**Issue by abdullahazmy** [ChrisTitusTech/linutil#578]
## The bug
![image](https://github.com/user-attachments/assets/65f2baae-24cf-4119-8531-e59963731482)

Am using Debian .. i think it's because nvim version at Debian is old, but not sure of the reason.

**Comment by nnyyxxxx** [comment]
Could not reproduce.

**Comment by abdullahazmy** [comment]
Am using Debian ..

**Comment by adamperkowski** [comment]
`lazy.nvim requires Neovim >= 0.8.0`

This is not really a bug. I'll open a PR to check nvim version before installtion.
