### ISSUE TITLE
Pressing ENTER on `..` shows a "Success" message

### ISSUE THREAD

**Issue by jinliu** [ChrisTitusTech/linutil#579]
## To Reproduce
1. Enter a submenu.
2. Press ENTER.

## Expected behavior
Go back.

## Actual behavior
A messagebox says "Success"

## Checklist
- [X] I checked for duplicate issues.
- [X] I checked already existing discussions.
- [X] This issue is not included in the roadmap.
- [x] This issue is present on both stable and development branches.

**Comment by lj3954** [comment]
Whoops. I introduced this in https://github.com/ChrisTitusTech/linutil/pull/490/commits/73235d90025861a9d50e9ea6fd5a6a6be413ee43. I'll put out a fix tomorrow.
