### ISSUE TITLE
Fedora/Nobara 40 nerd fonts issue?

### ISSUE THREAD

**Issue by ArchKaine** [ChrisTitusTech/linutil#58]
Installing font 'FiraCode Nerd Font'                         │                    │
│                    │Failed to resolve 'nerd' (Name or service not known)         │                    │
│                    │Failed to resolve 'nerd' (Name or service not known)         │                    │
│                    │Failed to resolve 'nerd' (Name or service not known)         │                    │

Not sure what is going on here, but I suspect this isn't intended behavior.

**Comment by RazoBeckett** [comment]
can you tell which script you ran ? from the list ...

**Comment by MEGA-Dawg68** [comment]
Having same issue. I ran this
curl -fsSL https://christitus.com/linux | sh

**Comment by ArchKaine** [comment]
> i mean what script from the list you ran for example:
> 
>     * bash setup
> 
>     * alacritty setup
> 
>     * anyother from the list
>       which one ?

Happens with the bash prompt setup. Sorry for slowness, busy lately.

**Comment by MEGA-Dawg68** [comment]
Bash setup
________________________________

**Comment by RazoBeckett** [comment]
I think wget is having trouble downloading the FiraCode Nerd Font. The URL might not be accessible. I initially thought this was because the font had new updates and the URL targeted an older version, but I realized that the files are hosted on GitHub and are accessible. I don't know what's wrong with Fedora. I would suggest trying to download the font zip manually using wget to see if that works, because as far as I can tell, there is no issue with the script.


Here's how:
run:
```bash
wget https://github.com/ryanoasis/nerd-fonts/releases/download/v2.3.3/FiraCode.zip
```

I will create a PR in which wget will check first if the file is accessible or not to avoid errors on screen.

**Comment by jamesthespud** [comment]
> I think wget is having trouble downloading the FiraCode Nerd Font. The URL might not be accessible. I initially thought this was because the font had new updates and the URL targeted an older version, but I realized that the files are hosted on GitHub and are accessible. I don't know what's wrong with Fedora. I would suggest trying to download the font zip manually using wget to see if that works, because as far as I can tell, there is no issue with the script.
> 
> Here's how: run:
> 
> ```shell
> wget https://github.com/ryanoasis/nerd-fonts/releases/download/v2.3.3/FiraCode.zip
> ```
> 
> I will create a PR in which wget will check first if the file is accessible or not to avoid errors on screen.

I'm also running fedora 40 and following your suggestion to download the fonts then installing them manually allowed the bash setup installer to skip the error message and all worked perfectly.

**Comment by aarjaycreation** [comment]
its fixed 
check now

**Comment by jeevithakannan2** [comment]
If the issue is resolved kindly close the issue

**Comment by adamperkowski** [comment]
This issue should be closed. Already fixed.
