### ISSUE TITLE
Programs from the linux world as inspiration. A collection from everyone.

### ISSUE THREAD

**Issue by Kingproone** [ChrisTitusTech/linutil#59]
I just wanted to start a collection from the community about cool pieces of software that could be inspiration for the utility. Pleases share, everyone!

https://discovery.endeavouros.com/endeavouros-tools/welcome - shown pictures are outdated
https://github.com/endeavouros-team
https://github.com/v1cont/yad

**Comment by 4yman-0** [comment]
Issues are for Bug reports and feature requests.
You can start a [Discussion](https://github.com/ChrisTitusTech/linutil/discussions) instead.

**Comment by Kingproone** [comment]
True, at the time there was no section for it, will do.
