### ISSUE TITLE
feat: disclaimer-like script descriptions

### ISSUE THREAD

**Issue by adamperkowski** [ChrisTitusTech/linutil#590]
## Is your feature request related to a problem? Please describe.
A lot of users like to know what's going "behind the scenes" and are not neccessarily familiar with shell scripting / don't want to scroll through code. 

## Describe the solution you'd like
Adding a new keybind / a visible warning that would open a popup showing the list of "important" tasks a script performs.
For example:
- Installs X
- Moves Y to Z
- Installs a kernel module

I could start working on this but I need some opinions first. 

## Checklist
- [x] I checked for duplicate issues.
- [x] I checked already existing discussions.
- [x] This feature is not included in the roadmap.

**Comment by ChrisTitusTech** [comment]
Yeah I think that would make it much more approachable so noobs don't think we are "hacking the matrix" lol
