### ISSUE TITLE
Titus-DWM usage issues on Debian 12

### ISSUE THREAD

**Issue by fg-personal** [ChrisTitusTech/linutil#609]
## Describe the bug
After installing the titus DWM through linutil and getting into it from the Debian 12 "login manager" on startup, almost nothing can be done in the new desktop environment. There is a button to take screenshots that is still working but I cannot open a terminal and every key combination I try to use does not produce any output.

## To Reproduce
1. Install Debian 12 on a new machine
2. Install browsers, kitty, flatpak, bottles, firewall baselines (CTT), do timeshift backup through linutil
3. Adjust Grub through linutil.
4. Install DWM-Titus (NO ISSUES DURING INSTALL)
5. (install other minor irrelevant applications for everyday usage)
6. Reboot PC into Debian 12 (I have a dual boot setup with windows)
7. On the bottom left corner of the Debian login screen, click on dwm
8. Described bug
(steps 1-5 are probably irrelevant, but I wanted to give the full picture anyway)

## Expected behavior
I expected to enter the new desktop manager and be able to open a terminal or any of the installed applications I can see on my KDE desktop manager (please consider I am a neophyte, I installed Debian mainly because this utility came out).

## Screenshots
I could get one, but I can just describe I only had a status bar with:
non-clickable icon of a terminal / empty space / working clock & system utilization info / button to take screenshots
the "Mountains" wallpaper was on by default

## Additional context
output of file .xsession-error
`
Xsession: X session started for %username% at Sat Sep 21 11:50:00 PM CEST 2024
dbus-update-activation-environment: setting DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
dbus-update-activation-environment: setting DISPLAY=:0
dbus-update-activation-environment: setting XAUTHORITY=/home/%username%/.Xauthority
dbus-update-activation-environment: setting XDG_CURRENT_DESKTOP=
localuser:%username% being added to access control list
dbus-update-activation-environment: setting GTK_MODULES=gail:atk-bridge
dbus-update-activation-environment: setting QT_ACCESSIBILITY=1
dwm: execvp /usr/lib/mate-polkit/polkit-mate-authentication-agent-1
 failed: No such file or directory
dwm: execvp dunst
dwm: execvp synergy
 failed: No such file or directory
 failed: No such file or directory
qt.qpa.xcb: Unhandled client message:  "_NET_WM_NAME"
QPainter::begin: Paint device returned engine == 0, type: 2
QPainter::setRenderHint: Painter must be active to set rendering hints
QPainter::setCompositionMode: Painter not active
QPainter::translate: Painter not active
QPainter::setPen: Painter not active
QPainter::setBrush: Painter not active
QPainter::setBrush: Painter not active
QPainter::begin: Paint device returned engine == 0, type: 2
QPainter::setRenderHint: Painter must be active to set rendering hints
QPainter::setCompositionMode: Painter not active
QPainter::translate: Painter not active
QPainter::setPen: Painter not active
QPainter::setBrush: Painter not active
QPainter::setBrush: Painter not active
Simple mixer control 'Master',0
  Capabilities: pvolume pswitch pswitch-joined
  Playback channels: Front Left - Front Right
  Limits: Playback 0 - 65536
  Mono:
  Front Left: Playback 46531 [71%] [off]
  Front Right: Playback 46531 [71%] [off]
Simple mixer control 'Master',0
  Capabilities: pvolume pswitch pswitch-joined
  Playback channels: Front Left - Front Right
  Limits: Playback 0 - 65536
  Mono:
  Front Left: Playback 43254 [66%] [on]
  Front Right: Playback 43254 [66%] [on]
Simple mixer control 'Master',0
  Capabilities: pvolume pswitch pswitch-joined
  Playback channels: Front Left - Front Right
  Limits: Playback 0 - 65536
  Mono:
  Front Left: Playback 46531 [71%] [on]
  Front Right: Playback 46531 [71%] [on]
/bin/sh: 1: xbacklight: not found
/bin/sh: 1: xbacklight: not found
flameshot: error: Invalid path, must be an existing directory or a new file in an existing directory
flameshot: error: Invalid path, must be an existing directory or a new file in an existing directory.
See flameshot --help.
`

## Checklist
- [x] I checked for duplicate issues.
- [x] I checked already existing discussions.
- [x] This issue is not included in the roadmap.
- [x] This issue is present on both stable and development branches.

**Comment by jeevithakannan2** [comment]
The default terminal is alacritty for dwm-titus. After installing alacritty you can open it using `SUPER+X` (Super is windows key)

**Comment by fg-personal** [comment]
I see, I didn't really follow a guide either, I just jumped into it. Although I tried mashing my keyboard, for some reason SUPER+R didn't register before. 
I am still having issues with the start, since I don't know which guide to follow to learn dwm and how much does the titus-dwm differ from whatever I google online.

Also having issues with the displays, but I see new scripts about monitor control appearing in the linutil, although they don't really enable my second monitor in the correct way.

I suppose this discussion shouldn't be open anymore, but I would appreciate some shorter resources compared to the full video of titus-DWM. 
I suppose this will be part of the documentation. However, making the documentation is a step mentioned in the roadmap so yeah.

Feel free to close the topic with or without suggestions.

**Comment by jeevithakannan2** [comment]
The keybindings are defined in the config.h file. Sorry I don't have a multi monitor setup so I can't help with monitor problem.  A user guide with the list of hotkeys must be made. This issue will be kept open until dwm-titus user guide is made. As for the monitor issue can you please open a new issue, so that other contributors maybe able to help you with that.

**Comment by adamperkowski** [comment]
From what I understand (TLDR), this is an issue with dwm-titus, not Linutil. Post this on the dwm-titus repo.

**Comment by nnyyxxxx** [comment]
/close not planned

This should be opened on the dwm-titus repository, as the documentation for dwm-titus is over there.
