### ISSUE TITLE
[Feature Request] Adding option to install Openbox directly from Linutil

### ISSUE THREAD

**Issue by bungadrum** [ChrisTitusTech/linutil#635]
## Is your feature request related to a problem? Please describe.
Is possible to add a option to install Openbox? It's not as light as DWM, but it's good enough for those who want to switch to something ligher and more graphical instead of TilingWM.

## Describe the solution you'd like
Maybe Linutil could get a new category called "DE Install" or "Desktop Enviroment" by runing Openbox it will install it and give you the option in the login session to use it or installed on bare metal. This would also get installed as additional stuff:

rofi, obconf, lxappearance, tint2, compton, nitrogen, menumaker or any other additional stuff.

## Describe alternatives you've considered
Archraft is the best example of a Openbox out of the box experience for reference it doesn't have to be that bloated maybe just a few themes if possible.

## Checklist
- [x] I checked for duplicate issues.
- [x] I checked already existing discussions.
- [x] This feature is not included in the roadmap.

**Comment by adamperkowski** [comment]
Merge this with #636.
