### ISSUE TITLE
Display a separate output window for SSH Commands

### ISSUE THREAD

**Issue by w-ndscar** [ChrisTitusTech/linutil#639]
## Issue's Description
When running a command on Utilities -> SSH Commands (say "View SSH configuration"), the output displays and then immediately the options to select an SSH operation displays underneath it. 

## Suggestion
Instead it would be neat if the output displays in a separate window and press a hotkey to get back to the command selection Menu

## Additional context
Here's a screenshot for a reference
![ssh_command_output](https://github.com/user-attachments/assets/3420c4fa-2fad-481f-a4b8-dd6b3ef303b4)

## Checklist
- [ X] I checked for duplicate issues.
- [ X] I checked already existing discussions.
- [ X] This feature is not included in the roadmap.

**Comment by jeevithakannan2** [comment]
I get the suggestion but creating a new window is tricky as the TUI is made in rust and the bash script runs in a wrapped environment. The script has no access or link to the TUI.

**Comment by nnyyxxxx** [comment]
/close not planned

this is not possible
