### ISSUE TITLE
Changing how applications are installed

### ISSUE THREAD

**Issue by Angxddeep** [ChrisTitusTech/linutil#652]
## Describe the solution you'd like
The thing is, Linux is moving to a unified way to package apps, and flatpaks are the prominent one (if you are not on Ubuntu). We should really push flatpak instead of Distro packages. We all already know about the security benefits that come with Flatpak, and those aren't the only benefits. At least flatpak should be the default for apps like telegram, Discord, OBS which recommend using the flatpak version as the default. Even for apps like signal, like on fedora, it would be much better to get a flatpak instead of enabling someone's Copr repo and do it that way. I would like to have a discussion on this, as personally most of my GUI application are Flatpak, but I get why someone might want to use distro package too or even AUR Build.

## Describe alternatives you've considered
If things were done my way I would probably make all application installation to flatpaks, but that isn't the reality so at least giving a choice between flatpak and distro package would be nice, and for apps that recommend flatpaks that should be the default.

## Checklist
- [x] I checked for duplicate issues.
- [x] I checked already existing discussions.
- [x] This feature is not included in the roadmap.

**Comment by Angxddeep** [comment]
And if we all agree to some sort of decision, I will do a PR on this later on

**Comment by Linuxury** [comment]
There are features that will be missing if run as a flatpak, for example if you use Discord you are unable to share what game/application you are currently using since it's contained. For some that's a desirable feature.

**Comment by Angxddeep** [comment]
> There are features that will be missing if run as a flatpak, for example if you use Discord you are unable to share what game/application you are currently using since it's contained. For some that's a desirable feature.

I get that why i said i can be choice in this scenario, but there are applications in which flatpaks are a no-brainer like telegram desktop

**Comment by adamperkowski** [comment]
> We all already know about the security benefits that come with Flatpak, and those aren't the only benefits. At least flatpak should be the default for apps like telegram, Discord, OBS which recommend using the flatpak version as the default.

I do not agree. Yes, flapak has security advantages over "standard" distro packages **but**

1. In most cases, Flatpak is noticeably slower than the "standard" packages
2. Packages installed through Flatpak are a pain to manage
3. Another non-neccessary dependency
4. Some people just don't like Flatpak by design (me), and prefer alternatives (the AUR for example)

> If things were done my way I would probably make all application installation to flatpaks

This is a opinion thing. I personally don't think Linutil should depend on Flatpak.

**Comment by adamperkowski** [comment]
If you wish to continue the discussion on this topic, open a [new discussion](https://github.com/ChrisTitusTech/linutil/discussions/new/choose) (obviously).
