### ISSUE TITLE
Command List cuts off - Needs 3 Lines

### ISSUE THREAD

**Issue by ChrisTitusTech** [ChrisTitusTech/linutil#653]
## Describe the bug
Command list is too long and doesn't always display the shortcut keys

## To Reproduce
Run at 1920x1080

## Screenshots
![image](https://github.com/user-attachments/assets/f6262aaa-6b9d-4c25-ac59-1f7d8b0fc3b7)

## Checklist
- [x] I checked for duplicate issues.
- [ ] I checked already existing discussions.
- [x] This issue is not included in the roadmap.
- [x] This issue is present on both stable and development branches.

**Comment by ChrisTitusTech** [comment]
Add L for Legend or ? for Help for the GUIDE which is currently assigned to G and not displayed in screenshot

**Comment by adamperkowski** [comment]
Adding another line is easy, but there's an issue, empty space:
![image](https://github.com/user-attachments/assets/c36e1a4f-8dcd-458d-aa7e-4371eea902cb)
It'd be nice to make the Constraint dynamically assign the lines needed.

**Comment by RazoBeckett** [comment]
> Adding another line is easy, but there's an issue, empty space: ![image](https://private-user-images.githubusercontent.com/75480869/370085919-c36e1a4f-8dcd-458d-aa7e-4371eea902cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxNzg5NDEsIm5iZiI6MTcyNzE3ODY0MSwicGF0aCI6Ii83NTQ4MDg2OS8zNzAwODU5MTktYzM2ZTFhNGYtOGRjZC00NThkLWFhN2UtNDM3MWVlYTkwMmNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI0VDExNTA0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2YTc1NWMzMzIzN2IzZWNjOGJjMjMyYjVlNzBhOWE0YzlmMzdiNDg3ODM3NTVlYWYzYzZjODY4YzRjMWI2ZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.n-Lp6QX2YJr2EknazShjnqgUCal5Rn2G2idQetLA0TM) It'd be nice to make the Constraint dynamically assign the lines needed.

is it possible to make it dynamic depending on the screen size ?

**Comment by cartercanedy** [comment]
Resolved with #668
