### ISSUE TITLE
AutoLogin not working

### ISSUE THREAD

**Issue by ChrisTitusTech** [ChrisTitusTech/linutil#654]
## Describe the bug
Using SDDM and DWM does not configure autologin and I suspect the script doesn't work on many systems as it does not check for `autologin` group, nor does it add the group, or assign the group to the user. 

## Expected behavior
Auto Login

## Screenshots
![image](https://github.com/user-attachments/assets/8b7b59c8-a932-4b84-8791-3b642634eedf)

## Checklist
- [x] I checked for duplicate issues.
- [x] I checked already existing discussions.
- [x] This issue is not included in the roadmap.
- [x] This issue is present on both stable and development branches.

**Comment by adamperkowski** [comment]
this should be using `tee` instead of `>`
