### ISSUE TITLE
Curl errors when installing applications

### ISSUE THREAD

**Issue by jeevithakannan2** [ChrisTitusTech/linutil#664]
## Describe the bug
Curl errors when installing applications due to existing configs

## To Reproduce
1. Go to application setup
2. Click on applications with config cloning
3. You will see error when already existing config is found

## Expected behavior
To clone the config and work 

## Screenshots
![curl-error](https://github.com/user-attachments/assets/414f7754-9c19-4c48-85aa-2f0da9422454)

## Checklist
- [x] I checked for duplicate issues.
- [x] I checked already existing discussions.
- [x] This issue is not included in the roadmap.
- [x] This issue is present on both stable and development branches.

**Comment by nnyyxxxx** [comment]
could not reproduce
![image](https://github.com/user-attachments/assets/07804ce6-4a66-4564-9d9c-43af37cac065)

ran multiple times, success each time.
