### ISSUE TITLE
Adding confirmation to Alacritty config setup

### ISSUE THREAD

**Issue by ACR-Jeff** [ChrisTitusTech/linutil#674]
## Is your feature request related to a problem? Please describe.

I've tested linutil for the first time, When hitting enter on Alacritty it began the installation process, I already have Alacritty installed and configured to my personal preference, Prior to executing I was unaware it would change the configuration, It would be nice to have some sort of confirmation to allow or deny this process if Alacritty is already installed.

## Describe the solution you'd like
If Alacritty is already installed, Give the user the options to reconfigure: Y = Continue, or N = Exit Process

https://github.com/ChrisTitusTech/linutil/blob/main/core/tabs/applications-setup/alacritty-setup.sh#L17C9-L17C69

Example: 
`printf "%b\n" "${GREEN}Alacritty is already installed.${RC}"
prompt_for_input() {
    while true; do
        echo -n "Do you want to reconfigure Alacritty? (y/n): "
        read -r response
        case "$response" in
            [Yy]* )
                echo "You selected Yes."
                return 0
                ;;
            [Nn]* )
                echo "You selected No."
                return 1
                ;;
            * )
                echo "Invalid input. Please enter y, n."
                ;;
        esac
    done
}`

## Additional context

This is just an example, I am not a script guru. So I am unsure this would work. This is untested code so may need to be modified. Yet the above is an example to get an idea of this Feature Request.

## Checklist
- [x] I checked for duplicate issues.
- [x] I checked already existing discussions.
- [ ] This feature is not included in the roadmap.

**Comment by nnyyxxxx** [comment]
/close not planned

Chris wants minimum user-interaction so this won't happen anytime soon, other than that your configuration gets backed up to ~/.config

**Comment by ACR-Jeff** [comment]
Well in that case could add a simple return below 
`printf "%b\n" "${GREEN}Alacritty is already installed.${RC}"
return 1`

Without it's just causing users to have to go change what may not have been expected or wanted. I simply executed the command to open linutil for the first time and hit enter and it executes commands without being aware/warned. IMO That doesn't sound too secure. Luckily I am smart enough to know where that config is. Yet not everyone may.
