### ISSUE TITLE
Add an option to easily set up bridged networking for Virt-Manager (if possible)

### ISSUE THREAD

**Issue by sabamdarif** [ChrisTitusTech/linutil#677]
## Is your feature request related to a problem? Please describe.
Recently, I tried setting up Virt-Manager using Chris Titus's blog, but I ran into a problem with the bridge networking section. 
Although I managed to fix it, but it took a lot of time to understand how it works. That’s why I’m asking if it’s possible to add a script to simplify this process then it would be great.

## Checklist
- [x] I checked for duplicate issues.
- [x] I checked already existing discussions.
- [x] This feature is not included in the roadmap.

**Comment by jeevithakannan2** [comment]
label /script

**Comment by jeevithakannan2** [comment]
label 'script'

**Comment by nnyyxxxx** [comment]
/close not planned

this is a rather tedious process, and could potentially brick networking, its best that its not done through a script and rather done manually. We do not want to be bricking peoples systems.
