### ISSUE TITLE
GRUB THEME Does not work on Nobara Project

### ISSUE THREAD

**Issue by Jeetkunndo** [ChrisTitusTech/linutil#678]
I was tryng to change my grub theme on Nobara Project a Fedora Basde Distro so I thought instead doing Manually use your tool but the Themes are not install and when i reboot i get the basic
 It seems that in fedora the theme has to be installed on a different folder i tried a solution i found on fedora forums but didnt work either im not sure if its a Fedora Problem or a Nobara Problem
![Screenshot](https://github.com/user-attachments/assets/650a1ee5-320a-423f-b860-76526d49840e)

**Comment by adamperkowski** [comment]
@guruswarupa

**Comment by adamperkowski** [comment]
That's probably an issue with [this script](https://github.com/ChrisTitusTech/Top-5-Bootloader-Themes/blob/main/install.sh). Not sure what exactly may be the problem here, you didn't provide any information other than "does not work" so it's kinda hard to troubleshoot.

**Comment by Jeetkunndo** [comment]
ok thanks dindt see the issue will read there
