### ISSUE TITLE
Fedora 41 - Gaming Dependencies

### ISSUE THREAD

**Issue by Linuxury** [ChrisTitusTech/linutil#679]
## Describe the bug
Testing on Fedora 41 the script, encountered the following issue. Dont know if its just a wait till release issue or something that needs to be addressed in the script itself.

## To Reproduce
1. Update to Fedora 41
2. Run the script.

## Screenshots
![image](https://github.com/user-attachments/assets/c9f260b6-7d2b-438b-9f53-ddb3172048c2)

## Checklist
- [x] I checked for duplicate issues.
- [x] I checked already existing discussions.
- [x] This issue is not included in the roadmap.
- [x] This issue is present on both stable and development branches.

**Comment by Nightmare1984** [comment]
Here Is A Work around Go To Terminal And Type In   sudo dnf install ffmpeg ffmpeg-libs -y   Red hat Changed How it's Done They Put In There Repo Enabled Already
