### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by janszafranski** [ChrisTitusTech/linutil#685]
## Describe the bug
I'm running a clean install of EndeavourOS on bare metal, and have tried installing it via yay, pacseek, as instructed, and it always fails in the build (using the 3 lines of code in the terminal... after the [makepkg -si] line

## To Reproduce
1. In Terminal, Enter [git clone https://aur.archlinux.org/linutil.git]
2. Then change directory to [linutil]
3. Then run [makepkg -si]
4. See error...
          
  = note: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
  = note: use the `-l` flag to specify native libraries to link
  = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#rustc-link-lib)

error: could not compile `linutil_tui` (bin "linutil") due to 1 previous error
==> ERROR: A failure occurred in build().
    Aborting...

## Expected behavior
Not to error, and instead complete installation

## Checklist
- [ ] I checked for duplicate issues.
- [ ] I checked already existing discussions.
- [ ] This issue is not included in the roadmap.
- [/] This issue is present on both stable and development branches.

**Comment by cartercanedy** [comment]
Do you mind verifying that you have pulled the most recent commits?

**Comment by janszafranski** [comment]
@cartercanedy Thanks for that.I should've added I'm a noob at this... can you tell me how to do "a shallow clone of the github repo directly and building from the most recent commit". Sorry for being so inept

**Comment by cartercanedy** [comment]
`git clone --depth 1 https://github.com/christitustech/linutil.git`

**Comment by janszafranski** [comment]
Sorry again... do I still do the [makepkg -si] again?

**Comment by janszafranski** [comment]
I got a cargo error: error: rustup could not choose a version of cargo to run, because one wasn't specified explicitly, and no default is configured.

**Comment by cartercanedy** [comment]
might have to run `rustup toolchain install stable`

**Comment by janszafranski** [comment]
Also couldn't install rustchain, got error: error: cannot install while Rust is installed

**Comment by cartercanedy** [comment]
try `rustup default stable`

**Comment by janszafranski** [comment]
Just did (followed what it said onscreen ) it errored, did it again and it installed. re-ran the [cargo run --profile release] again and the terminal cleared and loaded linutil. Does this mean that it's installed locally?

**Comment by janszafranski** [comment]
You've been great/very patient BTW

**Comment by cartercanedy** [comment]
To get the `linutil` binary installed locally, run `cargo install --path ./tui` in the root dir of the repo

**Comment by adamperkowski** [comment]
@janszafranski We're aware the AUR packages might not always work. It's because the last 2024.09.22 and 2024.09.23 have broken dependencies. We're now waiting for the next stable release. I'm sorry I forgot to remove 2024.09.23 from the AUR. I will do that now.

**Comment by janszafranski** [comment]
Thanks for the update :-) BTW... where is the root dir of the repo (sorry for being so dumb... steep learning curve ahead)

**Comment by cartercanedy** [comment]
> where is the root dir of the repo

the linutil directory that git cloned the repository into

no worries, we like to see that people are able to use and abuse the tools. That's why we're here :)

**Comment by adamperkowski** [comment]
The AUR package is now fixed with [febbc2a](https://aur.archlinux.org/cgit/aur.git/commit/?h=linutil&id=febbc2af2b34ecf416a75ab0614faf3bc149df7f).

**Comment by adamperkowski** [comment]
The package is fixed, I will close this issue now.
/unlabel 'bug'
/close

**Comment by adamperkowski** [comment]
> I just saw that you are using the AUR distribution, I believe that there was an issue with building from source in that release.

@cartercanedy Please @ me next time there's an AUR issue. Thanks.

**Comment by cartercanedy** [comment]
> @cartercanedy Please @ me next time there's an AUR issue. Thanks.

np, will do
