### ISSUE TITLE
Neovim version compatibility is not checked when setting it up

### ISSUE THREAD

**Issue by NomadicPython** [ChrisTitusTech/linutil#70]
## Describe the bug
Neovim version installed on RHEL9 using official repos (including EPFL) is 0.8* which is not compatible with the packages used for customizing nvim. Basically, setup neovim option gives an error for older versions of neovim < 0.9.4.

One error: which-key.nvim requires Neovim >= 0.9.4

## To Reproduce
1. Install RHEL9
2. run linutil > setup neovim
3. See error on first run of nvim after installation

## Expected behavior
A clear and concise description of what you expected to happen: Check if version provided by the distribution is supported.

## Screenshots
![Screenshot from 2024-07-25 14-10-04](https://github.com/user-attachments/assets/47be4e63-0172-41f2-84a8-5742f232c2e2)
![Screenshot from 2024-07-25 14-03-13](https://github.com/user-attachments/assets/a464588a-d216-4deb-b38a-c6f92decd73d)

## Additional context
I used setup bash before doing this. That was the only part of linutil I used before doing this. This is also a new installation without any serious config changes and did not have nvim installed previously.
I can download nvim 0.10.* from official github repository and run it without a problem with this system.

**Comment by afonsofrancof** [comment]
This happens because of [this](https://github.com/ChrisTitusTech/mybash/blob/0d8b97164dd848296a46922a289a3079673e7862/setup.sh#L103) line
It only checks if nvim exists and not it's version.
I suggest you open an issue on that repository.

**Comment by NomadicPython** [comment]
I think even if that line is changed to check for versions, the package manager installation would still do nothing since this is the most up to date version of neovim for the distribution. I can not find where the plugins for neovim are being installed by linutil, but I think that may be the place to make changes.
