### ISSUE TITLE
[Feature Request]: Add option to make Monday the first day of week in your calendar 

### ISSUE THREAD

**Issue by bungadrum** [ChrisTitusTech/linutil#703]
## Is your feature request related to a problem? Please describe.
Whenever I install Debian, Arch or latest Ubuntu LTS I notice that in the calendar the first day of the week is always sunday. I have tried changing the locales from "en_US.utf8" to "en_GB.utf8", but that didn't solve the problem. In latest Ubuntu LTS flutter installer I have the same problem while in the previous LTS ubiquiti  I didn't have to do anything it did everything for me it even put my on language in calendar. Is this a latest kernel issue or installer thing that defaults to en_US.utf8 no matter what your location is?. I use "CEST" having Sunday as first day of week instead of Monday is very confusing. No matter what distro or installer you use even if your location is european or any other it will always default to Sunday as first day of week in your calendar.

## Describe the solution you'd like
Can you add a option in Linutil under Utilities, "First day of week" Monday or Sunday for those that use it to appear in your calendar.

## Describe alternatives you've considered
N/A

## Additional context
https://forums.debian.net/viewtopic.php?t=151978
https://wiki.debian.org/Locale#First_day_of_week

![locale](https://github.com/user-attachments/assets/2495f1ca-3ffe-4421-a365-dc999e4bd68d)

## Checklist
- [x] I checked for duplicate issues.
- [x] I checked already existing discussions.
- [x] This feature is not included in the roadmap.

**Comment by nnyyxxxx** [comment]
/close not planned

there is no actual way to do this other than setting the locale, which did not work for you. Sorry.

Also there are conflicts that can happen with making a script that will do this such as: some desktop environments such as kde or gnome have this built into their settings applications and will conflict with them; this is the issue we had with the global theming script before as well.

if you are using a desktop environment try checking your settings app for date and time and set it there, or your calender application settings (if you are not using the built-in cmd "cal")
