### ISSUE TITLE
Simple alias addition

### ISSUE THREAD

**Issue by janszafranski** [ChrisTitusTech/linutil#704]
## Is your feature request related to a problem? Please describe.
Hi... Not a problem as such, rather a quick addition to the bash script

## Describe the solution you'd like
Add an extra 'alias' line... this time so that typing 'linutil' launches the linutil app itself, such as

alias linutil='curl  - fsSL  https://christitus.com/linux  |  sh'

I may be just a noob, but I'm a lazy noob   ;-)

## Checklist
- [ ] I checked for duplicate issues.
- [ ] I checked already existing discussions.
- [ / ] This feature is not included in the roadmap.

**Comment by nnyyxxxx** [comment]
/close not planned

use the linutil aur package or crates io package for this functionality

**Comment by adamperkowski** [comment]
Take a look at #349 & #354
