### ISSUE TITLE
Issue when making heavy use of Linutil with Ubuntu 24.04

### ISSUE THREAD

**Issue by Lurchicus** [ChrisTitusTech/linutil#708]
## Describe the bug
I wish I could be more detailed on the exact steps to reproduce this (too many steps to isolate the cause). The symptom, after making heavy use of the stable release of Liinutil, then restarting, When I get the password prompt, enter my password and press return, it flickers and goes back to the login screen (the one with my name). All attempts fron then on don't allow me to login (including a restart and dropping to root and changing my password. The machine I'm using is a Dell XPS-9320 laptop that I bought with Ubuntu installed. The end result, I have to do a full reinstall of Ubuntu 24.04.

## To Reproduce
1. Run an update/upgrade and restart
2. Run the stable release of Linutil via the curl command in github
3. Install a LOT of stuff with Linutil
4. Restart the system
5. Login and password screen loop endlessly with my not being able to log in.

## Expected behavior
After entering the password, go to the Gnome desktop (Wayland)

## Screenshots
Nothing to see here (see 4 above)

## Additional context
My system only has the Intel built-in GPU, 32 GB of RAM, a 2TB NVME SSD, an external 4TB hard drive (for backups), a docking port that supplies an external keyboard, mouse, two additional screens, a wired net connection, headphone/mic (Blackwire), and the backup drive. Running a 13th gen I7 (i7-1360P).

I did not try the dev branch as it take a long time to reinstall and configure the system

## Checklist
- [X] I checked for duplicate issues.
- [ X} I checked already existing discussions.
- [X ] This issue is not included in the roadmap.
- [ ?] This issue is present on both stable and development branches.

![image](https://github.com/user-attachments/assets/32f53380-b656-4f01-9135-279a634a2c4a)

**Comment by Lurchicus** [comment]
Things that don't appear to break Ubuntu 24.04:

- Bash prompt
- Docker
- FastFetch
- Timeshift backup

**Comment by Lurchicus** [comment]
One of these broke Ubuntu 24.04 (as described above):

- Github Desktop
- Meld
- Discord
- Zoom (install failed)

Back to rebuilding my system again.

**Comment by adamperkowski** [comment]
Well, that's unexpected. The scripts you listed above are very unlikely to "break" the system in that capacity. 

---
GitHub Desktop setup uses gpg but does not check if it's installed. (that should be fixed, redirecting to other contributors)

---
Meld Setup does this weird thing for some reason:
https://github.com/ChrisTitusTech/linutil/blob/a9a678fc116a3d15e35a2c30c723f2a012867394/core/tabs/applications-setup/Developer-tools/meld-setup.sh#L5-L8
I don't think that this could be the issue here though.

---
Discord script (for Ubuntu) downloads and installs the deb package so that couldn't be an issue.

---
And Zoom. The script for Zoom uses flatpak (incorrectly -  #705) so it in theory should:
1. check for flatpak and install it
2. install zoom from flathub 

---
Now for the flatpak script, it's just garbage in my opinion. Half of the code is pure 100% bloat.

I'm really sorry this happened to you. I don't see any direct issue that could cause that...

Most of the scripts you listed are by @guruswarupa I think.

**Comment by adamperkowski** [comment]
I will try to recreate this in a VM.

**Comment by Lurchicus** [comment]
I'm going to take one more pass through the last four with a restart between each one. 

Just FYI, this doesn't seem to bother my Linux Mint Cinnamon system (latest version) or my WSL2 24.04 install... until my windows system (11 pro) ate it's boot sector. 

Also by trade I'm a (retired) C#/SQL server developer, but except for games and WinForm development, I've become more and more focused on Linux.

**Comment by adamperkowski** [comment]
> I'm going to take one more pass through the last four with a restart between each one.

Okay, let me know how it went.

> this doesn't seem to bother my Linux Mint Cinnamon system (latest version) or my WSL2 24.04 install... until my windows system (11 pro) ate it's boot sector.

Yeah, typical for windows.
I'm not up to date with the mint stuff but I heard they're trying to go Debian-based. I assume yours is still on Ubuntu, right?

**Comment by Lurchicus** [comment]
Looks like Meld is the issue, for my system anyway. Have not checked Discord or Zoom yet. Git Desktop was fine (and all the others I mentioned). 

It may not have any bearing, but I'm using Chrome, not Firefox. 

Also I'm running 3 laptops with Ubuntu 24.04, Linux Mint Cinnamon (11th Gen i7) and Debian 12 (old XPS i7-3517U). Windows 11 pro is on a desktop with an i9-10900K (with Winutils run on it... I'm still rebuilding this system... reinstalling software).

**Comment by Lurchicus** [comment]
Just FYI, Meld did not affect my Debian 12 laptop. I'm not going to try my Linux Mint system for now.

**Comment by adamperkowski** [comment]
Okay. #644 got merged today. The only thing that IMO could be an issue with the meld script got refactored. We do not have a new prerelease yet so the change won't be present on precomplied versions but you can build linutil from source (from the main branch) and check if it still persists if you want to.

**Comment by guruswarupa** [comment]
> ## Describe the bug
> I wish I could be more detailed on the exact steps to reproduce this (too many steps to isolate the cause). The symptom, after making heavy use of the stable release of Liinutil, then restarting, When I get the password prompt, enter my password and press return, it flickers and goes back to the login screen (the one with my name). All attempts fron then on don't allow me to login (including a restart and dropping to root and changing my password. The machine I'm using is a Dell XPS-9320 laptop that I bought with Ubuntu installed. The end result, I have to do a full reinstall of Ubuntu 24.04.
> 
> ## To Reproduce
> Steps to reproduce the behavior:
> 1. Run an update/upgrade and restart
> 2. Run the stable release of Linutil via the curl command in github
> 3. Install a LOT of stuff with Linutil
> 4. Restart the system
> 5. Login and password screen loop endlessly with my not being able to log in.
> 
> ## Expected behavior
> After entering the password, go to the Gnome desktop (Wayland)
> 
> ## Screenshots
> Nothing to see here (see 4 above)
> 
> ## Additional context
> My system only has the Intel built-in GPU, 32 GB of RAM, a 2TB NVME SSD, an external 4TB hard drive (for backups), a docking port that supplies an external keyboard, mouse, two additional screens, a wired net connection, headphone/mic (Blackwire), and the backup drive. Running a 13th gen I7 (i7-1360P).
> 
> I did not try the dev branch as it take a long time to reinstall and configure the system
> 
> ## Checklist
> - [X] I checked for duplicate issues.
> - [ X} I checked already existing discussions.
> - [X ] This issue is not included in the roadmap.
> - [ ?] This issue is present on both stable and development branches.
> 
> ![image](https://github.com/user-attachments/assets/32f53380-b656-4f01-9135-279a634a2c4a)
> 

Well am sorry to hear that! But yes the scripts I made doesn't seem to break things at that level.

**Comment by Lurchicus** [comment]
> Okay. #644 got merged today. The only thing that IMO could be an issue with the meld script got refactored. We do not have a new prerelease yet so the change won't be present on precomplied versions but you can build linutil from source (from the main branch) and check if it still persists if you want to.

I believe I will run the dev branch and only try installing Meld. If there are no issues, I will close this with a reference to #644

**Comment by Lurchicus** [comment]
I ran the Meld install (it didn't report any errors), from the Linutil dev branch, it's still munging Ubuntu 24.04 on my system. I'm going to reinstall Ubuntu, but I'll wait for the next release (or until someone wants me to test a fix specific for this issue). I'll keep checking in (though it will be sometime tomorrow before I get the system going again... I just don't have another reinstall/rebuild in me tonight).

**Comment by jeevithakannan2** [comment]
Any update on this issue?

**Comment by Lurchicus** [comment]
Hi All,

It's November 4th, 2024 and I just tested this again on my Ubuntu 24.04 system and the Meld install from Linutil is still munging my system (looping on entering the login password). System details above. Let me know next time you would like me to test this (once I get everything reinstalled and updated).

Thank you,
Dan

**Comment by cartercanedy** [comment]
That meld script is entirely f*cked up. Just shows a lack of understanding for whoever wrote it

**Comment by cartercanedy** [comment]
I just saw that this got fixed, I'm sorry that this ate your system. If you still need to recover, you might be able to boot into a live install of Ubuntu and modify the `/etc/environment` by removing the second line that was appended by the meld installer

**Comment by jeevithakannan2** [comment]
@cartercanedy Can you make a PR for it?

**Comment by cartercanedy** [comment]
> @cartercanedy Can you make a PR for it?

This should be closed, fixed with #644

**Comment by adamperkowski** [comment]
> > @cartercanedy Can you make a PR for it?
> 
> This should be closed, fixed with #644

Alright then

**Comment by jeevithakannan2** [comment]
@adamperkowski Can you create a new release for vt100-ctt.

The cargo.lock seems to use the old cached version `0.15.*` instead of the new one `0.16.0`. Or we should add rev={git sha}

**Comment by adamperkowski** [comment]
> @adamperkowski Can you publish a new release for vt100-ctt.
> 
> The cargo.lock seems to use the old cached version `0.15.*` instead of the new one `0.16.0`. Or we should add `rev={git sha}` in Cargo.toml

it's because v0.115.3 IS the latest release (i'm back btw)
would be easier if @ChrisTitusTech would give me access to the vt100 repo

updated

**Comment by jeevithakannan2** [comment]
> it's because v0.115.3 IS the latest release (i'm back btw)

No after the merge of latest PRs in both repos the latest is 0.16.0

**Comment by adamperkowski** [comment]
> > it's because v0.115.3 IS the latest release (i'm back btw)
> 
> No after the merge of latest PRs in both repos the latest is 0.16.0 . Just need to push the release to crates.io

🤦 that's exactly what i meant

**Comment by adamperkowski** [comment]
0.16 is not **technically** released anywhere

**Comment by jeevithakannan2** [comment]
> 0.16 is not **technically** released anywhere

That is what I asked you in the first place

> Can you publish a new release for vt100-ctt.

**Comment by nnyyxxxx** [comment]
> That meld script is entirely f*cked up. Just shows a lack of understanding for whoever wrote it
> 
> It should be something like
> 
> ```shell
> cat >> "$HOME/.bashrc" << EOF
> PATH=\$PATH:\$HOME/meld/bin
> EOF
> ```
> 
> Doesn't even need to use heredoc, but putting it in `/etc/environment` as if it's a shell script is just plain wrong. I've actually never seen that given, and it should _**NEVER BE GIVEN**_, as general advice for modifying `PATH`, _**EVER**_.

i think jeevi wrote that i might be wrong, or guruswarupa

**Comment by nnyyxxxx** [comment]
this is why you dont add a million scripts in one pr its just low quality at that point

**Comment by jeevithakannan2** [comment]
My guy just unblocks me to fire shots at me and then blocks me again
