### ISSUE TITLE
Distrubtion specific alias for "sudo package-manager" in .bashrc

### ISSUE THREAD

**Issue by NomadicPython** [ChrisTitusTech/linutil#71]
**Is your feature request related to a problem? Please describe.**
Setup bash option of linutil adds an `alias apt-get="sudo apt-get"` in .bashrc. It's a good idea but does not work outside debian tree.

**Describe the solution you'd like**
change apt-get to pacman/yum/dnf based on distribution's package manager.

**Describe alternatives you've considered**
Uninstalling RHEL

**Additional context**
Also not sure about `alias home="cd ~"` since it does the same thing as `cd` which is shorter.

**Comment by jeevithakannan2** [comment]
This issue is related to https://github.com/ChrisTitusTech/mybash repository. Open an issue in https://github.com/ChrisTitusTech/mybash

**Comment by NomadicPython** [comment]
Opened issue there.
