### ISSUE TITLE
Check Bashism Unit test isn't working

### ISSUE THREAD

**Issue by ChrisTitusTech** [ChrisTitusTech/linutil#711]
## Describe the bug
The bashism is checking random files, look at #699 and its unit test to see it checking a different sh file. 

## Screenshots
![image](https://github.com/user-attachments/assets/5ea5d9f4-3451-43df-8ac0-1d34f24cbb9a)

## Checklist
- [x] I checked for duplicate issues.
- [x] I checked already existing discussions.
- [x] This issue is not included in the roadmap.
- [x] This issue is present on both stable and development branches.

**Comment by adamperkowski** [comment]
AGAIN?? COME ON I REMEMBER IT WORKING AFTER THE LAST PR

**Comment by adamperkowski** [comment]
Fixed.

**Comment by adamperkowski** [comment]
I can feel my mental state level dividing by 5 every time this workflow doesn't work.
