### ISSUE TITLE
🦀 bug(?): Multi-select breaking in `System Setup` & `Utilities` tabs

### ISSUE THREAD

**Issue by adamperkowski** [ChrisTitusTech/linutil#712]
# This is not a bug. This is intentional behaviour.
I'm keeping this issue open for conversation about this.

## Describe the bug
See the video below.

## To Reproduce
1. Launch `linutil`
2. Enable multi-select mode
3. Change tabs to `System Setup` or `Utilities`
4. multi-select breaks :'(

## Additional context
https://github.com/user-attachments/assets/d6acb432-f2f7-4e49-be6b-a66b623212c1

Sorry for crappy internet, recorded this on my laptop.

## Checklist
- [x] I checked for duplicate issues.
- [x] I checked already existing discussions.
- [x] This issue is not included in the roadmap.
- [x] This issue is present on both stable and development branches.

**Comment by lj3954** [comment]
This is intentional behaviour, look in the tab data for those two. Why was it done? I'm not really sure. @jeevithakannan2 would have to help you out with that.

**Comment by adamperkowski** [comment]
> This is intentional behaviour, look in the tab data for those two. Why was it done? I'm not really sure. @jeevithakannan2 would have to help you out with that.

You're right. I should've looked. I'll update the issue.
I think I understand that we may not want multi-select in "more important" sections or whatever but
1. the average user doesn't know that their whole "queue" is just going to disintegrate like that
2. only some of the scripts in `System Setup` for example are really "dangerous". Most of `Utilities` scripts are very easily revertable

I think this should be removed **or** multi-select should be refactored.

**Comment by jeevithakannan2** [comment]
I am working on disabling multi selection for individual scripts. Will create a PR in a couple of days.

**Comment by adamperkowski** [comment]
Okay. Make sure to link the PR. I'll keep this issue open.

**Comment by jeevithakannan2** [comment]
Okay !!
