### ISSUE TITLE
📃 bug(monitor control): Set Brightness not working

### ISSUE THREAD

**Issue by adamperkowski** [ChrisTitusTech/linutil#714]
## Describe the bug
See the image below

1. Shows two separate monitors as one
2. Clearly doesn't work

#465 btw

## To Reproduce
1. Execute the script
2. Select a "display"

## Screenshots
![image](https://github.com/user-attachments/assets/43299666-1bb5-400e-ad7d-298d8b05f4e3)

## Checklist
- [x] I checked for duplicate issues.
- [x] I checked already existing discussions.
- [x] This issue is not included in the roadmap.
- [x] This issue is present on both stable and development branches.

**Comment by nnyyxxxx** [comment]
looks like the issue stems if you have more than one monitor
