### ISSUE TITLE
panic when scrolling

### ISSUE THREAD

**Issue by jeevithakannan2** [ChrisTitusTech/linutil#731]
## Describe the bug
- When running a command the scrolling causes a panic.
- Turns out it is caused by a bug in vt100 https://github.com/doy/vt100-rust/pull/11

## To Reproduce
1. Run any command that outputs a very long message.
2. Press pageup 3 to 4 times.
4. See error.

## Expected behavior
- No panic and scroll up

## Screenshots
![image](https://github.com/user-attachments/assets/900d84ae-bc48-45bf-a5dd-2cf4ffc73898)

### Workarounds
- Limit the scroll offset up to the maximum number of rows of terminal https://github.com/ChrisTitusTech/linutil/blob/d3a801d49b6b60e92ac6f7d00b1edff211e6a721/tui/src/running_command.rs#L256
- Remove the scroll functionality for now.

### Solution
- Fork the vt100 and make our own crate just like the how other big projects are doing ( Big changes needed in linutil )
- Switching to a different parser ( Not ideal ). 

## Checklist
- [x] I checked for duplicate issues.
- [x] I checked already existing discussions.
- [x] This issue is not included in the roadmap.
- [x] This issue is present on both stable and development branches.

**Comment by jeevithakannan2** [comment]
label 'rust'

**Comment by nnyyxxxx** [comment]
@jeevithakannan2 its not a linutil issue i would just leave it how it is until it gets fixed in vt100

**Comment by jeevithakannan2** [comment]
Yeah it is not active that's why I created a issue here to get feedback. I could fork the vt100 and apply the fixes. Making our own version of vt100

**Comment by nnyyxxxx** [comment]
> Yeah it is not active that's why I created a issue here to get feedback. I could fork the vt100 and apply the fixes. Making our own version of vt100

we should let Chris decide

**Comment by nnyyxxxx** [comment]
we should add keybindings for arrow keys as well

**Comment by nnyyxxxx** [comment]
once this gets fixed

**Comment by jeevithakannan2** [comment]
Adding key bindings is bad as we use up and down keys in scripts

**Comment by nnyyxxxx** [comment]
> Adding key bindings for arrowkeys is bad as we use up and down keys in scripts

j and k dont work when  running scripts neither do arrow keys, + arrow keys is a good addition to avoid conflicts with j and  k

**Comment by adamperkowski** [comment]
@ChrisTitusTech we need you

**Comment by ChrisTitusTech** [comment]
Well shit. I guess for now we can remove scroll and if have the means to fix or fork we can do that in the future.

**Comment by adamperkowski** [comment]
i'll research this issue in some time. maybe there's a workaround

**Comment by cartercanedy** [comment]
mproc-vt100 looks like a recently updated fork, idk how much they've refactored the api

**Comment by jeevithakannan2** [comment]
Will keep this issue open until the scroll feature is fixed. Until then we can remove it. Just 6 lines of code is not a big deal. The biggest issue here is if a command is running and a panic happens the child is not killed leading to potential issues.

**Comment by jeevithakannan2** [comment]
> mproc-vt100 looks like a recently updated fork, idk how much they've refactored the api 

I looked at a bunch of forks the tui-term does not run with forks. Need to sort this out
