### ISSUE TITLE
Arch server NOT working

### ISSUE THREAD

**Issue by angryguy-win** [ChrisTitusTech/linutil#742]
## Describe the bug
arch server install NOT working

## Screenshots
![image](https://github.com/user-attachments/assets/d0937d6c-b48c-4b9e-8530-6a69fadc8581)

**Comment by adamperkowski** [comment]
Well that definitely looks like an issue. Could you provide more information?
1. What formal linutil version are you running
2. What branch
3. Logs (if any)
4. The output of `sh -x server-setup.sh` after `cd`ing into `core/tabs/system-setup/arch` if you're running linutil from source

This is clearly a bug but it's pretty hard to guess by a single screenshot.

/label 'script'

**Comment by angryguy-win** [comment]
git clone from main 
I'm checking and gathering what I can will get back to this...

**Comment by adamperkowski** [comment]
The output of

```bash
cd core/tabs/system-setup/arch
sh -x server-setup.sh
```

would provide all info needed.

**Comment by angryguy-win** [comment]
Sorry I figured it out

**Comment by nnyyxxxx** [comment]
you cannot run it from the graphical interface it has to be run through the tty
