### ISSUE TITLE
Mybash deps check is bugged

### ISSUE THREAD

**Issue by cartercanedy** [ChrisTitusTech/linutil#750]
## Describe the bug
`mybash-setup.sh` uses `command_exists "bash" "bash-completion" ...` as if it fails if one of the dependencies does not exist, but this won't work as written. Also, `bash-completion` and `fontconfig` aren't executables, so the check would always fail if it did work as intended...

## To Reproduce
1. run the bash prompt script
2. install fails if deps aren't installed, most likely to happen on fresh distro installs

## Checklist
- [x] I checked for duplicate issues.
- [x] I checked already existing discussions.
- [x] This issue is not included in the roadmap.
- [x] This issue is present on both stable and development branches.

**Comment by cartercanedy** [comment]
I have a fix incoming, but I'm busy atm. Will post when I can

**Comment by nnyyxxxx** [comment]
you're wrong, the ! means if even all are installed it will still install, same for if none are found or if only 1 / 2 are found 

can not **reproduce** this issue as well. there is really no issue here

**Comment by cartercanedy** [comment]
It is an issue, it's reproducible using both openSUSE and Kali

**Comment by cartercanedy** [comment]
> same for if none are found or if only 1 / 2 are found 

`command -v <arg1> <arg2>...` will only evaluate `<arg1>` without examining the rest of the arguments, which is problematic for several reason, namely `fc-cache` from fontconfig, which is not installed on headless distros like kali-headless and others

**Comment by nnyyxxxx** [comment]
> > same for if none are found or if only 1 / 2 are found
> 
> `command -v <arg1> <arg2>...` will only evaluate `<arg1>` without examining the rest of the arguments, which is problematic for several reason, namely `fc-cache` from fontconfig, which is not installed on headless distros like kali-headless and others

read what i said please

**Comment by cartercanedy** [comment]
@nnyyxxxx I'm don't understand why all of my contributions have been met with such fierce criticism on your part. 

You're free to say that I'm wrong, but the fundamental issue still remains, regardless.

**Comment by nnyyxxxx** [comment]
> @nnyyxxxx I don't understand why all of my contributions have been met with such fierce criticism on your part.
> 
> You're free to say that I'm wrong, but the fundamental issue still remains, regardless.

i cant reproduce the issue you're having man... all that PR is doing is bloating up the func, if you want a clear-cut solution to your nonexistent problem then remove every other dep from the command_exists var

**Comment by cartercanedy** [comment]
> > @nnyyxxxx I don't understand why all of my contributions have been met with such fierce criticism on your part.
> > 
> > You're free to say that I'm wrong, but the fundamental issue still remains, regardless.
> 
> i cant reproduce the issue you're having man... all that PR is doing is bloating up the func, if you want a clear-cut solution to your nonexistent problem then remove every other dep from the command_exists var

Ok, close the issue then, if you're insisting that there's no issue

**Comment by cartercanedy** [comment]
Steps to reproduce: 
1. Using WSL, install openSUSE Leap 15.6 via`wsl --install -d openSUSE-Leap-15.6 --web-download` and complete out-of-box setup wizard
2. Install cargo + git + gcc with zypper via `sudo zypper install cargo gcc git`
3. clone main branch of LinUtil via `git clone --depth 1 https://github.com/christitustech/linutil.git`
4. Run with `cargo r`
5. Attempt to run `Bash prompt` script, which fails when attempting to invoke fc-cache
