### ISSUE TITLE
Running zsh setup resulted in error below in screenshot

### ISSUE THREAD

**Issue by TuxManxD** [ChrisTitusTech/linutil#770]
## Describe the bug
Self explanatory

## Screenshots
![swappy-20241005-201858](https://github.com/user-attachments/assets/ad9e1b51-ac83-4e94-bd7c-db785d77835a)

**Comment by TuxManxD** [comment]
note I have ohmyzsh atm

**Comment by adamperkowski** [comment]
Fixed in #771
