### ISSUE TITLE
Numlock on Startup half working

### ISSUE THREAD

**Issue by rockpat** [ChrisTitusTech/linutil#777]
## Describe the bug
Numlock gets enabled in sddm but gets disabled as soon as login into KDE Plasma (works for DWM though!).

## To Reproduce

**0. System: Debian (Testing), sddm & KDE X11**
1. Run LinUtil "NumLock on Startup"
2. Reboot
3. Login to KDE
4. See Numlock getting disabled.

## Expected behavior
It should stay enabled when get to the Desktop.

## Screenshots
Not applicable.

## Additional context
Not needed.

## Checklist
- [x] I checked for duplicate issues.
- [x] I checked already existing discussions.
- [ ] This issue is not included in the roadmap.
- [x] This issue is present on both stable and development branches.

**Comment by jeevithakannan2** [comment]
Some DE have their own num lock configuration in settings. For KDE you need to enable it in the settings. Go to System Settings > Input Devices > Keyboard, in the Hardware tab, in the NumLock on Plasma Startup section, choose the desired NumLock behavior

**Comment by nnyyxxxx** [comment]
/close
solved

**Comment by rockpat** [comment]
OK, Thanks for the Explanation! I would only suggest changing the description of NumLock to really highlight this. (Which it already does, but without this knowledge you don't really think it only works on boot.)
