### ISSUE TITLE
Install packages via rpm-ostree or flatpak

### ISSUE THREAD

**Issue by yeeboi0** [ChrisTitusTech/linutil#779]
## Is your feature request related to a problem? Please describe.
Tried to use `linutil` to install packages on atomic desktop version of Fedora (Kinoite), but `rpm-ostree` and `flatpak` are not supported.

## Describe the solution you'd like
Include `rpm-ostree` or `flatpak` as supported package managers for installing packages.

## Describe alternatives you've considered
n/a

## Additional context
Atomic desktops are the future, man!

## Checklist
- [X] I checked for duplicate issues.
- [X] I checked already existing discussions.
- [X] This feature is not included in the roadmap.

**Comment by adamperkowski** [comment]
I'm 99% sure Fedora Kinoite comes with `rpm-ostree` **and** the standard `rpm`. I don't see the issue here.

**Comment by yeeboi0** [comment]
@adamperkowski  I don’t mean download the package managers, I mean download the other applications (alacrity, vscode, etc.) with rpm-ostree or flatpak. linutil only supports downloads with apt, pacman, or dnf (I think). Kinoite does not use those package managers.

**Comment by adamperkowski** [comment]
I get what you mean. What I'm saying is I'm 99% sure Kinoite does also use the standard `rpm`. Linutil supports `rpm`:

https://github.com/ChrisTitusTech/linutil/blob/26d0adc829ac59893666559f1c126d05b7fddc6b/core/tabs/common-script.sh#L130

**Comment by yeeboi0** [comment]
Sorry, I don’t see rpm in that list. Am I missing something?

**Comment by adamperkowski** [comment]
Oh wait, you're right.
Well, we use `dnf` becuase it's based on `rpm`. In the current script layout, we'd need to add `rpm-ostree` as a separate package manager and modify **every** script.
Technically, we could also add `rpm` at the end of the list (this way when user has `dnf` and `rpm` on their system, `dnf` is selected).

**Comment by leventbesli** [comment]
i'm not using atmoic OS, but as far as i know this is called "layering" and it's not recommended in the community. adding as default may not be a right choice. using classic packages in distrobox is more common. 

@adamperkowski do you think adding a flatpak check in every script is a good idea? maybe script can install flatpak if user agrees, or use dnf/apt/etc.. if not.

**Comment by adamperkowski** [comment]
> this is called "layering" and it's not recommended in the community. adding as default may not be a right choice.

I agree.

> do you think adding a flatpak check in every script is a good idea? maybe script can install flatpak if user agrees, or use dnf/apt/etc.. if not.

If we were to do this, certainly not by adding a flatpak check in every script.
It should be done like this:
1. add flatpak to the package manager check in common script (make sure it's the last package manager being checked)
2. integrate it with the existing flatpak setup
3. make every script support it

Albeit there is one small issue I see with this: we don't want linutil to be a flatpak wrapper (this has been discussed over several times before).
I get that *using* flatpak != *relying* on flatpak but I still think idea this needs more input / a bigger general discussion.

Let me try and summon @nnyyxxxx @lj3954 @guruswarupa here.

**Comment by yeeboi0** [comment]
I just think the ability to use linutil would be nice for us users that use atomic desktops like Fedora Silverblue, Bazzite, etc. Though, I can understand the hesitancy of building support for flatpaks or rpm-ostree (layering).

**Comment by jeevithakannan2** [comment]
> > this is called "layering" and it's not recommended in the community. adding as default may not be a right choice.
> 
> I agree.
> 
> > do you think adding a flatpak check in every script is a good idea? maybe script can install flatpak if user agrees, or use dnf/apt/etc.. if not.
> 
> If we were to do this, certainly not by adding a flatpak check in every script. It should be done like this:
> 
>     1. add flatpak to the package manager check in common script (make sure it's the last package manager being checked)
> 
>     2. integrate it with the existing flatpak setup
> 
>     3. make every script support it
> 
> 
> Albeit there is one small issue I see with this: we don't want linutil to be a flatpak wrapper (this has been discussed over several times before). I get that _using_ flatpak != _relying_ on flatpak but I still think idea this needs more input / a bigger general discussion.
> 
> Let me try and summon @nnyyxxxx @lj3954 @guruswarupa here.

Check for flatpak is implemented in https://github.com/ChrisTitusTech/linutil/pull/705 but only for the scripts and distros that require flatpak installation as of now.

If we were to implement it for every script along with existing package manager it depends we should discuss this over before adding them to every script

**Comment by solomoncyj** [comment]
i am packing for fedora. currently we are in dependency hell. the seial-* crates are so old that we have to repackage everting. staging copr: https://copr.fedorainfracloud.org/coprs/solomoncyj/rust
buglist: https://bugzilla.redhat.com/buglist.cgi?bug_status=NEW&bug_status=ASSIGNED&columnlist=product%2Ccomponent%2Cassigned_to%2Cstatus%2Csummary%2Clast_change_time%2Cseverity%2Cpriority&email1=solomoncyj%40gmail.com&emailreporter1=1&emailtype1=substring&list_id=13517944&order=status%2C%20priority%2C%20assigned_to%2C%20id%2C%20&query_format=advanced&short_desc=rust&short_desc_type=anywordssubstr

**Comment by solomoncyj** [comment]
@decathorpe he is a packager and package reviewer for fedora

**Comment by nnyyxxxx** [comment]
/close not planned

while flatpak support exists in some scripts in linutil its best we do not add global support for them, not many people will want the packages being installed as flatpak. I'm pretty sure we have semi-support for detecting flatpak pkgs as of right now ( or i might be wrong and it hasn't been merged yet ).
