### ISSUE TITLE
[Feature request] Add a PPA section in Linutil for Ubuntu users

### ISSUE THREAD

**Issue by bungadrum** [ChrisTitusTech/linutil#786]
## Is your feature request related to a problem? Please describe.
If you use Ubuntu and remove Snaps then you won't have any browser at hand since Firefox ships as Snap. Would it be possible to add PPA's for Ubuntu, it's oficial flavours and other Ubuntu based distros.

## Describe the solution you'd like
In Linutil there could be a PPA section there it would list Firefox-esr, Thunderbird and other PPA packages. This would be mostly for Ubuntu users I don't know if all based distros support PPA I know that you can install PPA on Linux Mint, but not on other distros. Some users use PPA the same way Arch users use AUR. Also if possible adding the option for uninstalling and removing the PPA completly since a full system upgrade tends to break PPA's as well. When I upgraded to the latest LTS I kept getting error for Firefox-esr every time I did update/upgrade. After removing it you can reinstall it later.

## Describe alternatives you've considered
Installing the deb packages that is supported by Mozilla which requires adding keyrings.

## Additional context

https://launchpad.net/ubuntu/+ppas

Firefox official Deb:

```
sudo install -d -m 0755 /etc/apt/keyrings

wget -q https://packages.mozilla.org/apt/repo-signing-key.gpg -O- | sudo tee /etc/apt/keyrings/packages.mozilla.org.asc > /dev/null

echo "deb [signed-by=/etc/apt/keyrings/packages.mozilla.org.asc] https://packages.mozilla.org/apt mozilla main" | sudo tee -a /etc/apt/sources.list.d/mozilla.list > /dev/null

echo '
Package: *
Pin: origin packages.mozilla.org
Pin-Priority: 1000

Package: firefox*
Pin: release o=Ubuntu
Pin-Priority: -1' | sudo tee /etc/apt/preferences.d/mozilla

sudo apt update && sudo apt remove firefox

sudo apt install firefox
```

## Checklist
- [x] I checked for duplicate issues.
- [x] I checked already existing discussions.
- [x] This feature is not included in the roadmap.

**Comment by adamperkowski** [comment]
See
https://github.com/ChrisTitusTech/linutil/blob/79eb7525529c405cf4cd05ee28a5aba520e81f53/core/tabs/applications-setup/browsers/firefox.sh#L10
/close
