### ISSUE TITLE
newlines in docs

### ISSUE THREAD

**Issue by nnyyxxxx** [ChrisTitusTech/linutil#795]
![image](https://github.com/user-attachments/assets/afc9fc44-5a01-4c82-9016-e9925125d45f)
![image](https://github.com/user-attachments/assets/2d1209c8-8746-40f2-ba3b-39028ed86cf6)

@adamperkowski probably has something to do with this

**Comment by nnyyxxxx** [comment]
> What's the issue here?

take a look at the images
![image](https://github.com/user-attachments/assets/399438de-d3ca-4e25-9e15-720b28f1eeb6)

**Comment by adamperkowski** [comment]
oh yeah

**Comment by adamperkowski** [comment]
that's an issue

**Comment by adamperkowski** [comment]
will fix in a sec

**Comment by adamperkowski** [comment]
> take a look at the images

You updated the images
![image](https://github.com/user-attachments/assets/5808aa80-3c76-4ad8-9668-f841823684ba)

**Comment by nnyyxxxx** [comment]
> > take a look at the images
> 
> You updated the images ![image](https://private-user-images.githubusercontent.com/75480869/375386170-5808aa80-3c76-4ad8-9668-f841823684ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1NjY2NjAsIm5iZiI6MTcyODU2NjM2MCwicGF0aCI6Ii83NTQ4MDg2OS8zNzUzODYxNzAtNTgwOGFhODAtM2M3Ni00YWQ4LTk2NjgtZjg0MTgyMzY4NGJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEwVDEzMTkyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmNjRkMWU5MWY4MDMyZTcyYTFhOTczNjE4ZDFjZjMxZGEzOTI0MDU4MDI3MTQ0ODQ5YTBmNjE3ZjFiNmVjYWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Ofyfn6WhxFVQaoj2564OOWvxM-voh2mHuh--JgaBSJc)

the issue is in both of them

**Comment by nnyyxxxx** [comment]
![image](https://github.com/user-attachments/assets/e10632a7-f70d-4fdf-89b0-bee19d442f01)
