### ISSUE TITLE
Fedora 40/41 - Gaming Dependencies

### ISSUE THREAD

**Issue by Linuxury** [ChrisTitusTech/linutil#804]
## Describe the bug
Installation fails have been occurring for a few weeks now, can't tell if it's related to Fedora getting ready to move into 41 or a modification to the script.

## Expected behavior
Installation to complete

## Screenshots
![image](https://github.com/user-attachments/assets/6de6a54c-ce4e-4ce7-99ed-f6485c7843e6)

## Additional context
This might be a similar issue as [803](https://github.com/ChrisTitusTech/linutil/issues/803) as the Fedora 41 release is so close or something in the script. It's unknown to me.

## Checklist
- [x] I checked for duplicate issues.
- [x] I checked already existing discussions.
- [ ] This issue is not included in the roadmap.
- [ ] This issue is present on both stable and development branches.

**Comment by jeevithakannan2** [comment]
Are you using fedora 41?

**Comment by lj3954** [comment]
This was fixed in https://github.com/ChrisTitusTech/linutil/commit/c3312dcc742775ca85c46ba40683c79776fee9a7. It was caused due to quoting a variable containing a list of packages to install, passing it as one argument into the package manager rather than space-delimited arguments.

**Comment by jeevithakannan2** [comment]
@lj3954 Didn't chris create a release after that merge?

**Comment by lj3954** [comment]
No. The latest full release is from the 28th of September (as you can see in the provided screenshot), 2 days before your fix was merged.

**Comment by Linuxury** [comment]
> Are you using fedora 41?

I am currently on 40, but I tested this on 41 a few days back and received the same issue.

**Comment by jeevithakannan2** [comment]
> > Are you using fedora 41?
> 
> I am currently on 40, but I tested this on 41 a few days back and received the same issue.

It was fixed in the main branch. A new release will resolve this issue. If you want you can compile linutil from source to avoid this issue.
