### ISSUE TITLE
Failed to Enable Signal Copr Repo

### ISSUE THREAD

**Issue by Tamir-K** [ChrisTitusTech/linutil#808]
## Describe the bug
Installing Signal in Fedora fails, failing to enable the relevant copr repo.
It seems that the copr repo no longer exists, and linutil needs to be reconfigured to either use an alternative repo, or install the flatpak version.

## To Reproduce
1. Launch linutil on fedora
2. Go to "Applications Setup" > "Communication Apps"
3. Scroll down to "Signal"
4. Press Enter
5. Press "Y" and Enter to enable repo
6. See error

## Expected behavior
Signal client installs

## Screenshots
![Screenshot from 2024-10-12 16-19-21](https://github.com/user-attachments/assets/6796ace0-7c51-402f-b35e-336630de5638)

## Additional context
Ran on Fedora 40

## Checklist
- [x] I checked for duplicate issues.
- [x] I checked already existing discussions.
- [x] This issue is not included in the roadmap.
- [x] This issue is present on both stable and development branches.

**Comment by nnyyxxxx** [comment]
@guruswarupa again...

**Comment by guruswarupa** [comment]
> @guruswarupa again...

Your pointing at me as if I maintain those projects. At times as time pass by, you'll see scripts breaking down. I tested as much as possible. Instead of tagging me, just fix it.
