### ISSUE TITLE
fastfetch causing midnight commander process to hang

### ISSUE THREAD

**Issue by ioannedelea** [ChrisTitusTech/linutil#809]
## Describe the bug
If you use midnight commander with the .bashrc provided by the script, you might notice that mc hangs for a few seconds before starting. The issue seems to be with mc and using fastfetch in .bashrc.

## To Reproduce
1. type mc in console
2. wait for the process to start

## Additional context
if you use mc with the -u or the --subshell flag, the process will start instantly.

## Workaround
Add alias mc = "mc -u" to your .bashrc file.

## Checklist
- [ x] I checked for duplicate issues.
- [ x] I checked already existing discussions.
- [ x] This issue is not included in the roadmap.
- [ x] This issue is present on both stable and development branches.

**Comment by jeevithakannan2** [comment]
It has nothing to do with fastfetch. When using subshell it loads the .bashrc so it takes time for it to open. It has been an issue for a long period of time. The bash prompt setup is done via https://github.com/ChrisTitusTech/mybash you can open an issue there.
