### ISSUE TITLE
Add Vision or Roadmap of the project to Readme

### ISSUE THREAD

**Issue by Marterich** [ChrisTitusTech/linutil#81]
I'd welcome a section to be added to the readme of the repo detailing a rough vision or maybe even a roadmap for linutil.

Why:
I haven't followed the development of linutil until now (stayed mainly over on winutil) but I'm open on contributing here as well, but at the moment I have a hard time wrapping my head around the vision for what linutil should become in the future and therefore cannot really quantify what is worth to be worked on.

**Comment by afonsofrancof** [comment]
I agree. I am adding some PRs, but mostly just closing issues.
If I knew exactly what the project is supposed to grow into, I can create more relevant PRs.
This is very needed

**Comment by adamperkowski** [comment]
Already added.
/close
