### ISSUE TITLE
"build requsites" command not working

### ISSUE THREAD

**Issue by solomoncyj** [ChrisTitusTech/linutil#817]
## To Reproduce
execute the script

## Expected behavior
Command completes sucssefullt

## Screenshots
![image](https://github.com/user-attachments/assets/99234698-e577-4ee3-991d-9f575d44bc98)

## Checklist
- [*] I checked for duplicate issues.
- [*] I checked already existing discussions.
- [*] This issue is not included in the roadmap.
- [*] This issue is present on both stable and development branches.

**Comment by jeevithakannan2** [comment]
This was fixed with https://github.com/ChrisTitusTech/linutil/commit/89bbc52712553274f1826889dc9398e654657102 .Try compiling from source until a new release.
