### ISSUE TITLE
Bug Report: Lynx Gets Installed Instead of Vivaldi

### ISSUE THREAD

**Issue by kokamisama** [ChrisTitusTech/linutil#833]
Issue: When selecting Vivaldi for installation, Lynx gets installed instead.

Steps to reproduce:

  1. Select Vivaldi for installation.  
  2. Proceed with the installation.
  3.  Notice that Lynx is installed instead of Vivaldi.

Expected behavior: Vivaldi should be installed when selected.

Actual behavior: Lynx is installed instead of Vivaldi.

![linutilbug](https://github.com/user-attachments/assets/afa0eb5b-28e3-4ef9-9cd6-9136f1aa4fbb)

**Comment by adamperkowski** [comment]
Fixed in #718
