### ISSUE TITLE
Not installing game dependencies; cannot handle repository shortcut

### ISSUE THREAD

**Issue by mcmurphy8097234789** [ChrisTitusTech/linutil#851]
## Describe the bug
Attempt to install Gaming Dependencies under System Setup

## To Reproduce
1. Go to System Setup > Gaming dependencies
2. Click on Gaming dependencies
3. Enter password and attempt to install dependencies
4. See error "Unable to handle repository shortcut 'contrib'"

## Expected behavior
I expect dependencies to be sorted and installed

## Checklist
- [ X] I checked for duplicate issues.
- [ X] I checked already existing discussions.
- [ X] This issue is not included in the roadmap.

## Additional information
![Screenshot from 2024-10-20 00-17-03](https://github.com/user-attachments/assets/5c151fcd-1426-4b5d-b139-b80d467f7912)

Computer is running PopOS 22.04 LTS

**Comment by adamperkowski** [comment]
/label 'script'

Please change the title to a more accurate one and provide more information (ex. screenshots) thanks
