### ISSUE TITLE
Full system cleanup tries to remove sudo in feora

### ISSUE THREAD

**Issue by solomoncyj** [ChrisTitusTech/linutil#857]
## Describe the bug
when executing full system cleanup, the scipt errors out as it tries to remove sudo

## To Reproduce
execute the full cleanup script 
## Expected behavior
scripts runs as normal

## Screenshots
![image](https://github.com/user-attachments/assets/d6aba8f6-c5f6-4769-a30e-45e534b366a1)

## Checklist
- [ ] I checked for duplicate issues.
- [ ] I checked already existing discussions.
- [ ] This issue is not included in the roadmap.
- [ ] This issue is present on both stable and development branches.

**Comment by solomoncyj** [comment]
maybe we can make it more verbose a bit?

**Comment by jeevithakannan2** [comment]
> maybe we can make it more verbose a bit?

Agreed

**Comment by jeevithakannan2** [comment]
```sh
"$ESCALATION_TOOL" "$PACKAGER" autoremove -y
```

Should not remove sudo package. Maybe a bug with dnf ??

**Comment by solomoncyj** [comment]
1 moment contacting upstream

**Comment by jeevithakannan2** [comment]
`dnf autoremove` removes dependencies that are no longer needed. Upon surfing online many people face issues with `dnf autoremove` maybe we should remove this to prevent issues like this https://www.reddit.com/r/Fedora/comments/1cbmofj/comment/l0zjx15/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

**Comment by solomoncyj** [comment]
![image](https://github.com/user-attachments/assets/b42b7f63-9839-4b5f-8f88-da1f379141d6)
no wonder

**Comment by lj3954** [comment]
This is an issue with fedora, not linutil.
