### ISSUE TITLE
Grub theme does not appear if `GRUB_TERMINAL_OUTPUT="console"` is set in `/etc/default/grub`

### ISSUE THREAD

**Issue by solomoncyj** [ChrisTitusTech/linutil#858]
## Describe the bug
when the line is present, the theme will not load on bootup

## To Reproduce
1. set the line in /etc/default/grub
2. execute grub theme script
3. reboot
4. stock grub menu appears

## Expected behavior
the theme to appear on next bootup

## Checklist
- [ ] I checked for duplicate issues.
- [ ] I checked already existing discussions.
- [ ] This issue is not included in the roadmap.
- [ ] This issue is present on both stable and development branches.

**Comment by adamperkowski** [comment]
Please open an issue about this in [Top-5-Bootloader-Themes](https://github.com/ChrisTitusTech/Top-5-Bootloader-Themes) because Linutil does not actually install the themes:
![image](https://github.com/user-attachments/assets/1ff34c05-b93c-4f61-8834-80b79f3f5fd6)

/close not planned
