### ISSUE TITLE
Missing font for search icon for rofi install- EndeavourOS

### ISSUE THREAD

**Issue by onemustpersist** [ChrisTitusTech/linutil#86]
## Describe the bug
Magnifying glass in rofi appears as missing font icon

## To Reproduce
OS: EndevourOS
Run install script
Setup hotkey in short cuts
Trigger shortcut
Notice icon for search icon is missing  

## Expected behavior
Icon should be a magnifying glass

## Screenshots
![missingfont](https://github.com/user-attachments/assets/99474e4a-447c-42a2-89df-cda8e92a3de2)

## Additional context
Tried re-running on current build, still same issue persists

**Comment by adamperkowski** [comment]
Same here, those are icons from [Nerd Fonts](https://www.nerdfonts.com/cheat-sheet).

[Titus' Rofi theme](https://github.com/ChrisTitusTech/dwm-titus/tree/main/config/rofi).

From what I understand, linutil doesn't install nerd fonts. You can install manually: [package](https://archlinux.org/groups/x86_64/nerd-fonts/). You should choose one (or more) font you like from the group.

**Comment by onemustpersist** [comment]
I assumed this so attempted to install nerd-fonts already. It _kind_ of fixes it

![nerd-font-install](https://github.com/user-attachments/assets/16ba122a-6906-43d8-a24b-7ba965e1c1cc)

However, it still looks to not be using the magnifying glass icon.

If this is an install script to simplify, it should install the required font, not require the user to _know_ to install nerd fonts

**Comment by JustLinuxUser** [comment]
This is because nerd fonts broke the compatibility, and new versions use diferent codepoints for the same icon. You need to edit your rofi configs to use the new icons, and if the rofi configuration is from Titus, then somebody should probably update that

**Comment by onemustpersist** [comment]
> This is because nerd fonts broke the compatibility, and new versions use diferent codepoints for the same icon. You need to edit your rofi configs to use the new icons, and if the rofi configuration is from Titus, then somebody should probably update that

The only rofi I have config is from this tool. I set it up via linutil. Probably needs updating

**Comment by JustLinuxUser** [comment]
Ok all the configs for rofi come from [this](https://github.com/ChrisTitusTech/dwm-titus) repo, so create an issue there, I would also suggest make a bigger screenshot so it's easier to tell which rofi window exactly is open. You should mention that the icons need to be up to date with new nerd-fonts. Or if you want, you can make a merge request yourself fixing that. Good luck :)

**Comment by onemustpersist** [comment]
Submitted fixing PR on dwn-titus. Closing.
