### ISSUE TITLE
PLease patch out `portable-pty` from linutil

### ISSUE THREAD

**Issue by solomoncyj** [ChrisTitusTech/linutil#860]
the crate depends on serial which depends on serial-unix and serial-core which is 7 years old old and is a dead project

**Comment by lj3954** [comment]
portable-pty is part of the WezTerm project and is actively maintained. In fact, it's a dependency for the terminal emulator itself. If any issues arise, I'm sure they'll be worked out swiftly. Any alternative you'd find is essentially certain to have nowhere near the amount of testing.

**Comment by lj3954** [comment]
If you'd like to try to get the serial dependency removed, you should file an issue with WezTerm as well as reporting the crate unmaintained on https://github.com/rustsec/advisory-db. Major projects are usually rather quick to remove anything with the potential for security issues.
