### ISSUE TITLE
Failed to install Gaming Dependencies in Arch Linux!

### ISSUE THREAD

**Issue by moheladwy** [ChrisTitusTech/linutil#867]
## Describe the bug
I use Arch Linux and when I try to install the gaming dependencies, I got the following error:

## To Reproduce
1. Go to 'System Setup'
2. Click on 'Gaming Dependencies'
3. See error:
"
Using sudo for privilege escalation
Using pacman as package manager
Super user group wheel
Using yay as AUR helper
Installing dependencies...
Multilib is already enabled.
 -> No AUR package found for wine dbus                                                      
-> No AUR package found for gnutls lib32-gnutls base-devel gtk2 gtk3 lib32-gtk2 lib32-gtk3 
libpulse lib32-libpulse alsa-lib lib32-alsa-lib                 alsa-utils alsa-plugins lib3
2-alsa-plugins alsa-lib lib32-alsa-lib giflib lib32-giflib libpng lib32-libpng              
libldap lib32-libldap openal lib32-openal libxcomposite lib32-libxcomposite libxinerama 
b32-libxinerama                 ncurses lib32-ncurses vulkan-icd-loader lib32-vulkan-icd-lo
ader ocl-icd lib32-ocl-icd libva lib32-libva                 gst-plugins-base-libs lib32-gst
-plugins-base-libs sdl2                                                                    
there is nothing to do                                                                     
error: target not found: steam lutris goverlay                              
"

## Expected behavior
I should install all the gaming dependencies.

## Screenshots
![screenshot_22102024_062646](https://github.com/user-attachments/assets/3ed5fab6-1abe-48ba-a81d-85f400c2aab8)

## Checklist

- [] I checked for duplicate issues. ===> True
- [ ] I checked already existing discussions. ===> True
- [ ] This issue is not included in the roadmap. ===> True
- [ ] This issue is present on both stable and development branches.

**Comment by jeevithakannan2** [comment]
This was fixed in https://github.com/ChrisTitusTech/linutil/commit/c3312dcc742775ca85c46ba40683c79776fee9a7. It was caused due to quoting a variable containing a list of packages to install, passing it as one argument into the package manager rather than space-delimited arguments.

Try compiling from the source until a new release
