### ISSUE TITLE
Missing font for folder icons in installer ui  - EndeavourOS

### ISSUE THREAD

**Issue by onemustpersist** [ChrisTitusTech/linutil#87]
## Describe the bug
Folder icons and console icons appear as hollow boxes on run

## To Reproduce
Run script in EndeavourOS

## Expected behavior
Icons should appear as console icon and folders

## Screenshots
![missingfont-software](https://github.com/user-attachments/assets/8bc9f123-9666-47bf-b328-9aead52643ee)

## Additional context
Happens in current build

**Comment by adamperkowski** [comment]
Those are icons from [Nerd Fonts](https://www.nerdfonts.com/cheat-sheet).

https://github.com/ChrisTitusTech/linutil/blob/8e8476cda5ce2b9d1efcc2e031f19bc38132586a/src/theme.rs#L26-L27

From what I understand, linutil doesn't install nerd fonts. You can install manually: [package](https://archlinux.org/groups/x86_64/nerd-fonts/). You should choose one (or more) font you like from the group.

**Comment by onemustpersist** [comment]
Even with all nerd-fonts installed, this is still an issue :

![after-nerdfont-install](https://github.com/user-attachments/assets/82ab956d-c11e-44f7-8c1f-1a1362727a90)

linutil should install the font if it is going to use it else the presented UI and the screenshot of the  ui will differ

**Comment by adamperkowski** [comment]
You should check your terminal emulator settings for fonts. do you use tmux or anything similar?

**Comment by onemustpersist** [comment]
Required opening fresh terminal to address the issue. If that is the case, not sure how this can be address before running the script other then a prerequisite install of the fonts.

**Comment by JustLinuxUser** [comment]
Linutil is not causing fonts to not work somehow, but if you don't want to install the fonts, linutil has a compatibility mode with `linutil --compat` or `linutil -c`

**Comment by onemustpersist** [comment]
With the goal of this project being a tool to help people to migrate to Linux by removing a lot of configuration minutia, should _compatibility mode_ be the default mode? Most users in that user base would not have installed nerd-fonts.

**Comment by HeCodes2Much** [comment]
> With the goal of this project being a tool to help people to migrate to Linux by removing a lot of configuration minutia, should _compatibility mode_ be the default mode? Most users in that user base would not have installed nerd-fonts.

i totaly agree with you on this it should be default unless stated by the user.

**Comment by Kingproone** [comment]
After I installed `extra/ttf-jetbrains-mono-nerd 3.2.1-2` and relaunched my terminal, the icons show up for me. This is a 200 mb download though, which isn't really ideal, for 3 used icons. Can't those - or some similar icons be bundled?

**Comment by angryguy-win** [comment]
I'm Using EndeavourOS, my icons show up fine, but I have some Nerdfonts install for other s thing like Terminal ect..
maybe there is a more elegant solution for just the hand full of font/icons. then installing fonts that some people might not want to install..
![image](https://github.com/user-attachments/assets/a37bbf18-60d1-40fb-b36d-acf05ed7235e)

**Comment by onemustpersist** [comment]
> I'm Using EndeavourOS, my icons show up fine, but I have some Nerdfonts install for other s thing like Terminal ect.. maybe there is a more elegant solution for just the hand full of font/icons. then installing fonts that some people might not want to install.. ![image](https://private-user-images.githubusercontent.com/162399710/360091127-a37bbf18-60d1-40fb-b36d-acf05ed7235e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyNzM1OTgsIm5iZiI6MTcyNDI3MzI5OCwicGF0aCI6Ii8xNjIzOTk3MTAvMzYwMDkxMTI3LWEzN2JiZjE4LTYwZDEtNDBmYi1iMzZkLWFjZjA1ZWQ3MjM1ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMVQyMDQ4MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZjc1MzM2ZmY3MDgyMWEwY2I0Y2RkNzJkNjk1MzNmYzFmMThjYWEwNTNiNDNjOTM2YjAzYmJmZjNkMmM1NGU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WTkAuX24rlx_iJg_niWeiz0MgRBvJqCBwmvtDmVVIe4)

Yes, It is not an issue with nerd-fonts installed

**Comment by JustLinuxUser** [comment]
> maybe there is a more elegant solution for just the hand full of font/icons. then installing fonts that some people might not want to install.. 
There is not, this is a terminal app, not a gui app, it doesn't render text itself, it just writes stuff to stdout, and the terminal renders the text.
There are a couple of options here:
- Run with compatibility mode, so that the icons are never displayed in the first place,
- Have the setup script detect the OS, install a terminal and a font, update the terminal config to use that font, and launch linutil in that terminal, but I feel like this is too "invasive".
You run linutil in the compat mode if you don't want the icons, or you just install the font, that's not that hard of a problem tbh, and even without the fonts or the compat mode, you can still use it perfectly fine, its just ugly

**Comment by onemustpersist** [comment]
> > maybe there is a more elegant solution for just the hand full of font/icons. then installing fonts that some people might not want to install..
> 
> There is not, this is a terminal app, not a gui app, it doesn't render text itself, it just writes stuff to stdout, and the terminal renders the text. There are a couple of options here:
> 
>     * Run with compatibility mode, so that the icons are never displayed in the first place,
> 
>     * Have the setup script detect the OS, install a terminal and a font, update the terminal config to use that font, and launch linutil in that terminal, but I feel like this is too "invasive".
>       You run linutil in the compat mode if you don't want the icons, or you just install the font, that's not that hard of a problem tbh, and even without the fonts or the compat mode, you can still use it perfectly fine, its just ugly

The ideal would be detect compatible fonts and run in compatibility mode if they are not present

**Comment by JustLinuxUser** [comment]
@onemustpersist I don't think that would be possible, see [here](https://github.com/ryanoasis/nerd-fonts/discussions/829#discussioncomment-2720269)

**Comment by nnyyxxxx** [comment]
As discussed above this is not a linutil issue, also this issue has been fixed via the no icons keybind.
