### ISSUE TITLE
Auto cpu-freq fails to detect laptop

### ISSUE THREAD

**Issue by jeevithakannan2** [ChrisTitusTech/linutil#871]
## Describe the bug
Auto cpu-freq fails to detect laptop. And fails to apply tweaks after installation.

## To Reproduce
1. Go to 'utilites'
2. Click on 'Auto Power Profiling'
3. Install 'auto cpu-freq'
4. Apply tweaks
5. See error

## Expected behavior
Able to detect laptop.

## Screenshots
![image](https://github.com/user-attachments/assets/1d50f76f-8b93-4b95-a95e-975744536c24)

## Additional context
Some laptops does not have battery in BAT0 instead they have in BAT1 or BAT2.

## Checklist
- [x] I checked for duplicate issues.
- [x] I checked already existing discussions.
- [x] This issue is not included in the roadmap.
- [x] This issue is present on both stable and development branches.

**Comment by adamperkowski** [comment]
hmm that's funny. so you're saying what's exactly wrong? we need to detect the `BAT` device first?

**Comment by jeevithakannan2** [comment]
Also it fails to work because `sudo auto cpu-freq --install` should be ran before trying to apply tweaks

**Comment by adamperkowski** [comment]
Yeah so this here
https://github.com/ChrisTitusTech/linutil/blob/e3688e9b3d2f3594bf2367af87a800db9e2f1bbd/core/tabs/utils/power-profile.sh#L48

should be checking multiple `BAT`s

**Comment by jeevithakannan2** [comment]
> Yeah so this here
> 
> https://github.com/ChrisTitusTech/linutil/blob/e3688e9b3d2f3594bf2367af87a800db9e2f1bbd/core/tabs/utils/power-profile.sh#L48
> 
> should be checking multiple `BAT`s

Yeah it should be somewhat like `if [ -d /sys/class/power_supply/BAT* ]`

**Comment by jeevithakannan2** [comment]
I usually check with `dmidecode -s chassis-type` but it requires dmidecode to be installed

**Comment by infstate** [comment]
Hello, I have sent a PR to resolve this issue. I am now waiting for approval.

**Comment by jeevithakannan2** [comment]
> Hello, I have sent a PR to resolve this issue. I am now waiting for approval. #877

Also add fix for failing to apply fix
