### ISSUE TITLE
Use auto-cpufreq AUR package instead of git

### ISSUE THREAD

**Issue by jeevithakannan2** [ChrisTitusTech/linutil#872]
## Is your feature request related to a problem? Please describe.
Use AUR package of `auto-cpufreq` instead of using git for easier updates.
By using the git version and how it was implemented in the linutil there is no way it can be updated.

## Describe the solution you'd like
To use AUR version of `auto-cpufreq`
https://aur.archlinux.org/packages/auto-cpufreq

## Describe alternatives you've considered
Trying to manually clone the github repo of `auto-cpufreq` and update.

## Checklist
- [x] I checked for duplicate issues.
- [x] I checked already existing discussions.
- [x] This feature is not included in the roadmap.

**Comment by adamperkowski** [comment]
yeah good idea. there are also [snap](https://github.com/AdnanHodzic/auto-cpufreq?tab=readme-ov-file#snap-store) and [nix](https://github.com/AdnanHodzic/auto-cpufreq?tab=readme-ov-file#nixos) packages.

**Comment by cartercanedy** [comment]
> snap

ew

**Comment by adamperkowski** [comment]
> > snap
> 
> ew

agreed.
