### ISSUE TITLE
waydroid setup error

### ISSUE THREAD

**Issue by Yeon0007** [ChrisTitusTech/linutil#880]
## Describe the bug
installing waydroid in arch linux, it shows some error at the line "Setting up Waydroid...", maybe some dependency error? dont know exactly

## To Reproduce
1. Go to 'Applications Setup'
2. Click on 'Waydroid'
3. Scroll down to 'Setting up Waydroid...'
4. Setting up Waydroid...                                                                                            
         │[22:24:14] Failed to load binder driver                                                                           
         │[22:24:14] modprobe: FATAL: Module binder_linux not found in directory /lib/modules/6.11.5-arch1-1                  
         │[22:24:14] ERROR: Binder node "binder" for waydroid not found                                        
         │[22:24:14] See also: <https://github.com/waydroid>                                              
         │Run 'waydroid log' for details. 

## Screenshots
![20241027_22h34m41s_grim](https://github.com/user-attachments/assets/f69fec10-adf8-45a6-aa10-f542d312c5ef)

## Checklist
- [ yes] I checked for duplicate issues.
- [ yes]  checked already existing discussions.
- [ ] This issue is not included in the roadmap.
- [ ] This issue is present on both stable and development branches.

**Comment by adamperkowski** [comment]
That's a common issue on Arch. You need to install `binder_linux-dkms` from the AUR.

**Comment by adamperkowski** [comment]
Oh I know why. Fixing it now.

**Comment by Yeon0007** [comment]
i should wait? can you fix it?

**Comment by adamperkowski** [comment]
I'll fix it. Install dkms & linux-headers and rerun the script. Will work.

**Comment by Yeon0007** [comment]
ok

**Comment by Yeon0007** [comment]
after installing dkms, linux-headers & binder_linux-dkms, it worked but internet connectivity is not working inside waydroid container. 
may be this is the issue:

sudo waydroid session stop
sudo waydroid session start
[00:09:14] ERROR: org.freedesktop.DBus.Error.NotSupported: Using X11 for dbus-daemon autolaunch was disabled at compile time, set your DBUS_SESSION_BUS_ADDRESS instead
[00:09:14] See also: <https://github.com/waydroid>
Run 'waydroid log' for details.

**Comment by adamperkowski** [comment]
Weird. Make sure you have all 'essential' environment variables (like `LANG` or `XDG_SESSION_TYPE`) set properly on your system.
Other than that, I don't think I can help you with that. See https://github.com/waydroid/waydroid/issues/732.
