### ISSUE TITLE
Nala Full System Cleanup Fails

### ISSUE THREAD

**Issue by tranquil-tr0** [ChrisTitusTech/linutil#895]
## Describe the bug
If nala is detected and used, the action will fail, as nala does not have "autoclean"

## To Reproduce
1. Use nala package manager
2. Run linutil stable
3. Run "Full System Cleanup"

## Expected behavior
Finish selected job by ignoring nala, or other solution. Would expect the usage of apt to autoclean, or some other solution.

## Checklist
- [x] I checked for duplicate issues.
- [ ] I checked already existing discussions.
- [ ] This issue is not included in the roadmap.
- [ ] This issue is present on both stable and development branches.

**Comment by jeevithakannan2** [comment]
This was fixed in the latest Dev release.
