### ISSUE TITLE
Bash Prompt tweak doesn't apply

### ISSUE THREAD

**Issue by MarcoColomb0** [ChrisTitusTech/linutil#909]
## Describe the Bug
The bash prompt tweak does not apply on Raspberry Pi OS Lite due to the missing "fontconfig" package.

## To Reproduce
1. Use a system that does not include the "fontconfig" package by default.

## Expected Behavior
It should check if the package exists.

## Checklist
- [x] I have checked for duplicate issues.
- [x] I have reviewed existing discussions.
- [x] This issue is not included in the roadmap.
- [x] This issue is present on both stable and development branches.

**Comment by adamperkowski** [comment]
There already is a check present. Are you sure the issue is present on the dev release?
