### ISSUE TITLE
OpenSUSE Zoom install

### ISSUE THREAD

**Issue by xanaddams** [ChrisTitusTech/linutil#914]
## Describe the bug
Cannot install Zoom

## To Reproduce
ran script from youtube to launch application Linutil. Chose Application Setup >Zoom. returned Failed! Press <ENTER> to close this window. Error: /tmp/linutil_scripts.mDiokXWN8Rf5/applications-setup/communication-apps/zoom-setup.sh: line 13: ./setup-flatpak.sh: No such file or directory 

## Expected behavior
Zoom install

## Screenshots
![image](https://github.com/user-attachments/assets/01361961-4b85-4f99-b775-4a020a467c69)

## Additional context
I would also like to add that highlighting and copying the info is not possible (which is the point of it being for new users) as highlighting anything just copys the wording from the screen behind it. (Could not copy the error message it just pastes the lines in Linux toolbox section even though I did not highlight that. 

## Checklist
- [y ] I checked for duplicate issues.
- [ y] I checked already existing discussions.
- [ y] This issue is not included in the roadmap.
- [y ] This issue is present on both stable and development branches.

**Comment by adamperkowski** [comment]
Fixed in d4eacaeab3e771dd4e75f3ccc3d4334098629a4a.

**Comment by jeevithakannan2** [comment]
Try the Dev release
