### ISSUE TITLE
tui is noticably laggy with mouse interaction

### ISSUE THREAD

**Issue by nnyyxxxx** [ChrisTitusTech/linutil#936]
title

**Comment by nnyyxxxx** [comment]
needs reverted, or optimized, needs a toggle as well

**Comment by nnyyxxxx** [comment]
it lags without keyboard interaction as well, its just more noticable with keyboard interaction

**Comment by nnyyxxxx** [comment]
actually to rephrase this it lags extremely badly while the mouse is moving and not still

**Comment by nnyyxxxx** [comment]
to reproduce: 

move mouses up and down and scroll with either the keyboard or scroll wheel

**Comment by nnyyxxxx** [comment]
the cpu usage with this feature is crazy, i think this should just be reverted

**Comment by nnyyxxxx** [comment]
that's fine, but i clearly can and it's clearly noticeable on both release and debug

**Comment by lj3954** [comment]
> the cpu usage with this feature is crazy, i think this should just be reverted

Different than from holding a key? I see just about identical CPU usage (30% of a single Ryzen 7900x core) rapidly scrolling with a mouse & with a keyboard.
