### ISSUE TITLE
Adding Bluez installation

### ISSUE THREAD

**Issue by bungadrum** [ChrisTitusTech/linutil#957]
## Is your feature request related to a problem? Please describe.
Whenever I try to use bluetooth either directly from Linutil or bluetooth Manager it always gives me a Blueman manager connecting to Bluez failed error.

## Describe the solution you'd like
Can you add a option under Utilites for installing Bluez daemons.

## Describe alternatives you've considered
N/A

## Additional context
![bluez](https://github.com/user-attachments/assets/9ff801a4-d211-4728-835e-64fcdea147b0)

## Checklist
- [x] I checked for duplicate issues.
- [x] I checked already existing discussions.
- [x] This feature is not included in the roadmap.

**Comment by jeevithakannan2** [comment]
What did `systemctl status bluetooth` return. Also what distribution are you on ?

**Comment by bungadrum** [comment]
I am currently on Xubuntu 22.04 LTS which comes preinstalled with Bluetooth Adapters, Manager and Blueman.

Systemctl: 
![bluetooth](https://github.com/user-attachments/assets/6933391a-aef3-4f05-84cc-6f0a312899b4)

**Comment by jeevithakannan2** [comment]
Run `rfkill list`

**Comment by jeevithakannan2** [comment]
Running bluetooth manager in linutil will install the bluez if not installed and start the bluez daemon if not. This issue cannot be reproduced. This issue is not related to linutil. Still I will try to resolve your issue.

/close not planned
