### ISSUE TITLE
Cargo installation instructions incorrect

### ISSUE THREAD

**Issue by OvermindDL1** [ChrisTitusTech/linutil#963]
## Describe the bug

The cargo installation instructions state to run `cargo install linutil` but that is incorrect, it should be `cargo install linutil_tui`.  (See additional notes below as well.)

## To Reproduce

Look at the crates.io page.  Try copy pasting the cargo install line and run it.

## Expected behavior

Copy pasting the command to install should work

## Checklist
- [X] I checked for duplicate issues.

Additional notes: 

The version currently on crates.io does not compile anyway because someone broke semver.  You actually need to run `cargo install linutil_tui --locked` or it won't compile.

**Comment by adamperkowski** [comment]
hmm... i wonder who wrote that (it was me)
