### ISSUE TITLE
Wrong title for command list box

### ISSUE THREAD

**Issue by mikeiit** [ChrisTitusTech/linutil#976]
## Describe the bug
The command list box at the bottom has title "Tab List"

## To Reproduce
1. Launch linutil
2. Stay on the top level navigation, observe the command list box title at the bottom, it says "Tab list"

## Expected behavior
It should be "Command list"

## Screenshots
![image](https://github.com/user-attachments/assets/63c4c2bf-2fb2-430c-a2d9-ef52c0f60360)

## Additional context
N/A

## Checklist
- [x] I checked for duplicate issues.
- [x] I checked already existing discussions.
- [ ] This issue is not included in the roadmap.
- [ ] This issue is present on both stable and development branches.

**Comment by lj3954** [comment]
You're focused on the tab list, as can be seen from the highlight. This is intended behaviour.
